"""AWS AppConfig action node — AWS AppConfig — deploy + fetch runtime configuration.

REST at https://appconfig.{region}.amazonaws.com. See sim-parity roadmap Phase 4-close-5.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.aws_appconfig",
    name="AWS AppConfig",
    category="integration",
    description="AWS AppConfig — deploy + fetch runtime configuration.",
    icon_slug="aws_appconfig",
    color="#232F3E",
    base_url="https://appconfig.{region}.amazonaws.com",
    credential_type="aws_credentials",
    token_field=["api_key"],
    auth="aws_sigv4",
    aws_service="appconfig",
    fields=[
        FieldSpec(name="model", label="Model", type="string"),
        FieldSpec(name="messages", label="Messages (JSON array)", type="json", default=[]),
        FieldSpec(name="temperature", label="Temperature", type="number", default=1),
        FieldSpec(name="max_tokens", label="Max Tokens", type="number", default=0),
        FieldSpec(name="input", label="Input", type="string"),
        FieldSpec(name="instructions", label="Instructions", type="string"),
        FieldSpec(name="prompt", label="Prompt", type="string"),
        FieldSpec(name="size", label="Size", type="string", default="1024x1024"),
        FieldSpec(name="quality", label="Quality", type="string", default="high"),
        FieldSpec(name="n", label="Count", type="number", default=1),
        FieldSpec(name="file_url", label="File URL", type="string"),
        FieldSpec(name="image_url", label="Image URL", type="string"),
        FieldSpec(name="mask_url", label="Mask URL", type="string"),
        FieldSpec(name="voice_id", label="Voice ID", type="string"),
        FieldSpec(name="text", label="Text", type="string"),
        FieldSpec(name="model_id", label="Model ID", type="string"),
        FieldSpec(name="user_id", label="User ID", type="string"),
        FieldSpec(name="memory_id", label="Memory ID", type="string"),
        FieldSpec(name="metadata", label="Metadata (JSON)", type="json", default={}),
        FieldSpec(name="query", label="Query", type="string"),
        FieldSpec(name="limit", label="Limit", type="number", default=10, mode="advanced"),
        FieldSpec(name="session_id", label="Session ID", type="string"),
        FieldSpec(name="email", label="Email", type="string"),
        FieldSpec(name="first_name", label="First Name", type="string"),
        FieldSpec(name="last_name", label="Last Name", type="string"),
        FieldSpec(name="task_spec", label="Task Spec (JSON)", type="json", default={}),
        FieldSpec(name="processor", label="Processor", type="string", default="core"),
        FieldSpec(name="input_data", label="Input Data (JSON)", type="json", default={}),
        FieldSpec(name="run_id", label="Run ID", type="string"),
        FieldSpec(name="objective", label="Objective", type="string"),
        FieldSpec(name="page_size", label="Page Size", type="number", default=100),
        FieldSpec(
            name="person_fields",
            label="Person Fields",
            type="string",
            default="names,emailAddresses,phoneNumbers",
        ),
        FieldSpec(name="resource_name", label="Resource Name", type="string"),
        FieldSpec(name="given_name", label="Given Name", type="string"),
        FieldSpec(name="family_name", label="Family Name", type="string"),
        FieldSpec(name="phone", label="Phone", type="string"),
        FieldSpec(name="engine_id", label="Search Engine ID (cx)", type="string"),
        FieldSpec(name="num", label="Num Results", type="number", default=10),
        FieldSpec(name="start", label="Start Index", type="number", default=1),
        FieldSpec(name="search_type", label="Search Type (image or blank)", type="string"),
        FieldSpec(name="to", label="To", type="string"),
        FieldSpec(name="from_number", label="From", type="string"),
        FieldSpec(name="body_text", label="Body Text", type="string"),
        FieldSpec(name="media_url", label="Media URL", type="string"),
        FieldSpec(name="message_sid", label="Message SID", type="string"),
        FieldSpec(name="application_id", label="Application ID", type="string"),
        FieldSpec(name="environment_id", label="Environment ID", type="string"),
        FieldSpec(name="profile_id", label="Configuration Profile ID", type="string"),
        FieldSpec(name="version_number", label="Version Number", type="string"),
        FieldSpec(name="deployment_strategy_id", label="Deployment Strategy ID", type="string"),
        FieldSpec(name="visitor_id", label="Visitor ID", type="string"),
        FieldSpec(name="since", label="Since (ISO)", type="string"),
        FieldSpec(name="host", label="SAP Host", type="string"),
        FieldSpec(name="username", label="Username", type="string"),
        FieldSpec(name="business_partner", label="Business Partner ID", type="string"),
        FieldSpec(name="sales_order", label="Sales Order ID", type="string"),
        FieldSpec(name="top", label="Top", type="number", default=20, mode="advanced"),
        FieldSpec(name="filter", label="Filter", type="string", mode="advanced"),
        FieldSpec(name="application_name", label="Application Name", type="string"),
        FieldSpec(name="description", label="Description", type="string"),
        FieldSpec(name="environment_name", label="Environment Name", type="string"),
        FieldSpec(name="profile_name", label="Config Profile Name", type="string"),
        FieldSpec(name="location_uri", label="Location URI", type="string", default="hosted"),
        FieldSpec(name="content_body", label="Content (JSON)", type="json", default={}),
        FieldSpec(
            name="content_type_field",
            label="Content-Type",
            type="string",
            default="application/json",
        ),
        FieldSpec(name="client_id", label="Client ID", type="string"),
        FieldSpec(
            name="client_configuration_version", label="Client Config Version", type="string"
        ),
        FieldSpec(name="deployment_number", label="Deployment Number", type="string"),
    ],
    operations=[
        OpSpec(
            id="list_applications",
            label="List Applications",
            method="GET",
            path="/applications",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_environments",
            label="List Environments",
            method="GET",
            path="/applications/{application_id}/environments",
            visible_fields=["application_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_configuration_profiles",
            label="List Config Profiles",
            method="GET",
            path="/applications/{application_id}/configurationprofiles",
            visible_fields=["application_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_hosted_configuration_version",
            label="Get Hosted Config Version",
            method="GET",
            path="/applications/{application_id}/configurationprofiles/{profile_id}/hostedconfigurationversions/{version_number}",
            visible_fields=["application_id", "profile_id", "version_number"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="start_deployment",
            label="Start Deployment",
            method="POST",
            path="/applications/{application_id}/environments/{environment_id}/deployments",
            visible_fields=[
                "application_id",
                "environment_id",
                "deployment_strategy_id",
                "profile_id",
                "version_number",
            ],
            body_builder=lambda v: {
                "DeploymentStrategyId": getattr(v, "deployment_strategy_id", "") or "",
                "ConfigurationProfileId": getattr(v, "profile_id", "") or "",
                "ConfigurationVersion": str(getattr(v, "version_number", "") or ""),
            },
        ),
        OpSpec(
            id="get_configuration",
            label="Get Configuration",
            method="GET",
            path="/applications/{application_id}/environments/{environment_id}/configurations/{profile_id}",
            visible_fields=[
                "application_id",
                "environment_id",
                "profile_id",
                "client_id",
                "client_configuration_version",
            ],
            query_builder=lambda v: {
                k: val
                for k, val in {
                    "client_id": getattr(v, "client_id", None) or None,
                    "client_configuration_version": getattr(v, "client_configuration_version", None)
                    or None,
                }.items()
                if val
            },
        ),
        OpSpec(
            id="create_application",
            label="Create Application",
            method="POST",
            path="/applications",
            visible_fields=["application_name", "description"],
            body_builder=lambda v: {
                "Name": getattr(v, "application_name", "") or "",
                "Description": getattr(v, "description", None) or None,
            },
        ),
        OpSpec(
            id="get_application",
            label="Get Application",
            method="GET",
            path="/applications/{application_id}",
            visible_fields=["application_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="update_application",
            label="Update Application",
            method="PATCH",
            path="/applications/{application_id}",
            visible_fields=["application_id", "application_name", "description"],
            body_builder=lambda v: {
                k: val
                for k, val in {
                    "Name": getattr(v, "application_name", None) or None,
                    "Description": getattr(v, "description", None) or None,
                }.items()
                if val is not None
            },
        ),
        OpSpec(
            id="delete_application",
            label="Delete Application",
            method="DELETE",
            path="/applications/{application_id}",
            visible_fields=["application_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_environment",
            label="Create Environment",
            method="POST",
            path="/applications/{application_id}/environments",
            visible_fields=["application_id", "environment_name"],
            body_builder=lambda v: {"Name": getattr(v, "environment_name", "") or ""},
        ),
        OpSpec(
            id="get_environment",
            label="Get Environment",
            method="GET",
            path="/applications/{application_id}/environments/{environment_id}",
            visible_fields=["application_id", "environment_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="update_environment",
            label="Update Environment",
            method="PATCH",
            path="/applications/{application_id}/environments/{environment_id}",
            visible_fields=["application_id", "environment_id", "environment_name"],
            body_builder=lambda v: {"Name": getattr(v, "environment_name", "") or ""},
        ),
        OpSpec(
            id="delete_environment",
            label="Delete Environment",
            method="DELETE",
            path="/applications/{application_id}/environments/{environment_id}",
            visible_fields=["application_id", "environment_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_configuration_profile",
            label="Create Config Profile",
            method="POST",
            path="/applications/{application_id}/configurationprofiles",
            visible_fields=["application_id", "profile_name", "location_uri"],
            body_builder=lambda v: {
                "Name": getattr(v, "profile_name", "") or "",
                "LocationUri": getattr(v, "location_uri", None) or "hosted",
            },
        ),
        OpSpec(
            id="get_configuration_profile",
            label="Get Config Profile",
            method="GET",
            path="/applications/{application_id}/configurationprofiles/{profile_id}",
            visible_fields=["application_id", "profile_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="update_configuration_profile",
            label="Update Config Profile",
            method="PATCH",
            path="/applications/{application_id}/configurationprofiles/{profile_id}",
            visible_fields=["application_id", "profile_id", "profile_name"],
            body_builder=lambda v: {"Name": getattr(v, "profile_name", "") or ""},
        ),
        OpSpec(
            id="delete_configuration_profile",
            label="Delete Config Profile",
            method="DELETE",
            path="/applications/{application_id}/configurationprofiles/{profile_id}",
            visible_fields=["application_id", "profile_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_hosted_configuration_version",
            label="Create Hosted Config Version",
            method="POST",
            path="/applications/{application_id}/configurationprofiles/{profile_id}/hostedconfigurationversions",
            visible_fields=["application_id", "profile_id", "content_body", "content_type_field"],
            body_builder=lambda v: getattr(v, "content_body", None) or {},
        ),
        OpSpec(
            id="list_hosted_configuration_versions",
            label="List Hosted Config Versions",
            method="GET",
            path="/applications/{application_id}/configurationprofiles/{profile_id}/hostedconfigurationversions",
            visible_fields=["application_id", "profile_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="delete_hosted_configuration_version",
            label="Delete Hosted Config Version",
            method="DELETE",
            path="/applications/{application_id}/configurationprofiles/{profile_id}/hostedconfigurationversions/{version_number}",
            visible_fields=["application_id", "profile_id", "version_number"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_deployment_strategies",
            label="List Deployment Strategies",
            method="GET",
            path="/deploymentstrategies",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_deployment",
            label="Get Deployment",
            method="GET",
            path="/applications/{application_id}/environments/{environment_id}/deployments/{deployment_number}",
            visible_fields=["application_id", "environment_id", "deployment_number"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_deployments",
            label="List Deployments",
            method="GET",
            path="/applications/{application_id}/environments/{environment_id}/deployments",
            visible_fields=["application_id", "environment_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="stop_deployment",
            label="Stop Deployment",
            method="DELETE",
            path="/applications/{application_id}/environments/{environment_id}/deployments/{deployment_number}",
            visible_fields=["application_id", "environment_id", "deployment_number"],
            query_builder=lambda v: {},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "id", "type": "string"},
    ],
    allow_error=True,
)
