"""Brex action node — Brex — corporate cards + expense management.

REST at https://platform.brexapis.com/v2. See sim-parity roadmap Phase 4.24.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.brex",
    name="Brex",
    category="integration",
    description="Brex — corporate cards + expense management.",
    icon_slug="brex",
    color="#1c1c1c",
    base_url="https://platform.brexapis.com/v2",
    credential_type="brex_api_key",
    token_field=["api_key"],
    auth="bearer",
    fields=[
        FieldSpec(name="employee_id", label="Employee ID", type="string"),
        FieldSpec(name="worker_id", label="Worker ID", type="string"),
        FieldSpec(name="user_id", label="User ID", type="string"),
        FieldSpec(name="contact_id", label="Contact ID", type="string"),
        FieldSpec(name="tenant", label="Tenant", type="string"),
        FieldSpec(name="raas_url", label="RaaS Report URL", type="string"),
        FieldSpec(name="report_id", label="Report ID", type="string"),
        FieldSpec(name="expense_id", label="Expense ID", type="string"),
        FieldSpec(name="first_name", label="First Name", type="string"),
        FieldSpec(name="last_name", label="Last Name", type="string"),
        FieldSpec(name="email", label="Email", type="string"),
        FieldSpec(name="content", label="Content", type="string"),
        FieldSpec(name="limit", label="Limit", type="number", default=25, mode="advanced"),
        FieldSpec(name="offset", label="Offset", type="number", default=0, mode="advanced"),
        FieldSpec(name="expense_body", label="Expense Body (JSON)", type="json", default={}),
        FieldSpec(name="receipt_url", label="Receipt URL", type="string"),
        FieldSpec(name="account_id", label="Account ID", type="string"),
        FieldSpec(name="budget_id", label="Budget ID", type="string"),
        FieldSpec(name="spend_limit_id", label="Spend Limit ID", type="string"),
        FieldSpec(name="vendor_id", label="Vendor ID", type="string"),
        FieldSpec(name="transfer_id", label="Transfer ID", type="string"),
    ],
    operations=[
        OpSpec(
            id="list_transactions",
            label="List Card Transactions",
            method="GET",
            path="/transactions/card/primary",
            visible_fields=["limit"],
            query_builder=lambda v: {"limit": int(getattr(v, "limit", 25) or 25)},
        ),
        OpSpec(
            id="list_users",
            label="List Users",
            method="GET",
            path="/users",
            visible_fields=["limit"],
            query_builder=lambda v: {"limit": int(getattr(v, "limit", 25) or 25)},
        ),
        OpSpec(
            id="list_expenses",
            label="List Expenses",
            method="GET",
            path="/expenses/card",
            visible_fields=["limit"],
            query_builder=lambda v: {"limit": int(getattr(v, "limit", 25) or 25)},
        ),
        OpSpec(
            id="get_expense",
            label="Get Expense",
            method="GET",
            path="/expenses/card/{expense_id}",
            visible_fields=["expense_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_budgets",
            label="List Budgets",
            method="GET",
            path="/budgets",
            visible_fields=["limit"],
            query_builder=lambda v: {"limit": int(getattr(v, "limit", 25) or 25)},
        ),
        OpSpec(
            id="update_expense",
            label="Update Expense",
            method="PATCH",
            path="/v1/expenses/{expense_id}",
            visible_fields=["expense_id", "expense_body"],
            body_builder=lambda v: getattr(v, "expense_body", None) or {},
        ),
        OpSpec(
            id="upload_receipt",
            label="Upload Receipt to Expense",
            method="POST",
            path="/v1/expenses/{expense_id}/receipt_match",
            visible_fields=["expense_id", "receipt_url"],
            body_builder=lambda v: {"url": getattr(v, "receipt_url", "") or ""},
        ),
        OpSpec(
            id="match_receipt",
            label="Match Receipt",
            method="POST",
            path="/v1/expenses/receipt_match",
            visible_fields=["receipt_url"],
            body_builder=lambda v: {"url": getattr(v, "receipt_url", "") or ""},
        ),
        OpSpec(
            id="list_card_transactions",
            label="List Card Transactions",
            method="GET",
            path="/v2/transactions/card",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_cash_transactions",
            label="List Cash Transactions",
            method="GET",
            path="/v2/transactions/cash",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_card_accounts",
            label="List Card Accounts",
            method="GET",
            path="/v2/accounts/card",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_cash_accounts",
            label="List Cash Accounts",
            method="GET",
            path="/v2/accounts/cash",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_cash_account",
            label="Get Cash Account",
            method="GET",
            path="/v2/accounts/cash/{account_id}",
            visible_fields=["account_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_card_statements",
            label="List Card Statements",
            method="GET",
            path="/v2/statements/card",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_cash_statements",
            label="List Cash Statements",
            method="GET",
            path="/v2/statements/cash",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_user",
            label="Get User",
            method="GET",
            path="/v2/users/{user_id}",
            visible_fields=["user_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_current_user",
            label="Get Current User",
            method="GET",
            path="/v2/users/me",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_departments",
            label="List Departments",
            method="GET",
            path="/v2/departments",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_locations",
            label="List Locations",
            method="GET",
            path="/v2/locations",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_titles",
            label="List Titles",
            method="GET",
            path="/v2/titles",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_cards",
            label="List Cards",
            method="GET",
            path="/v2/cards",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_company",
            label="Get Company",
            method="GET",
            path="/v2/company",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_budget",
            label="Get Budget",
            method="GET",
            path="/v2/budgets/{budget_id}",
            visible_fields=["budget_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_spend_limits",
            label="List Spend Limits",
            method="GET",
            path="/v2/spend_limits",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_spend_limit",
            label="Get Spend Limit",
            method="GET",
            path="/v2/spend_limits/{spend_limit_id}",
            visible_fields=["spend_limit_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_vendors",
            label="List Vendors",
            method="GET",
            path="/v2/vendors",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_vendor",
            label="Get Vendor",
            method="GET",
            path="/v2/vendors/{vendor_id}",
            visible_fields=["vendor_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_transfers",
            label="List Transfers",
            method="GET",
            path="/v2/transfers",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_transfer",
            label="Get Transfer",
            method="GET",
            path="/v2/transfers/{transfer_id}",
            visible_fields=["transfer_id"],
            query_builder=lambda v: {},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "results", "type": "array"},
    ],
    allow_error=True,
)
