"""Spotify action node — Spotify — playback, playlists, tracks, artist metadata.

REST at https://api.spotify.com/v1. See sim-parity roadmap Phase 4.29.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.spotify",
    name="Spotify",
    category="integration",
    description="Spotify — playback, playlists, tracks, artist metadata.",
    icon_slug="spotify",
    color="#1DB954",
    base_url="https://api.spotify.com/v1",
    credential_type="spotify_api_key",
    token_field=["api_key"],
    auth="bearer",
    fields=[
        FieldSpec(name="query", label="Query", type="string"),
        FieldSpec(
            name="max_results", label="Max Results", type="number", default=10, mode="advanced"
        ),
        FieldSpec(name="type", label="Type", type="string"),
        FieldSpec(name="video_id", label="Video ID", type="string"),
        FieldSpec(name="channel_id", label="Channel ID", type="string"),
        FieldSpec(name="playlist_id", label="Playlist ID", type="string"),
        FieldSpec(name="post_id", label="Post ID", type="string"),
        FieldSpec(name="title", label="Title", type="string"),
        FieldSpec(name="content", label="Content (HTML)", type="string"),
        FieldSpec(name="status", label="Status", type="string", default="draft"),
        FieldSpec(name="per_page", label="Per Page", type="number", default=10, mode="advanced"),
        FieldSpec(name="text", label="Text", type="string"),
        FieldSpec(name="tweet_id", label="Tweet ID", type="string"),
        FieldSpec(name="username", label="Username", type="string"),
        FieldSpec(name="subreddit", label="Subreddit", type="string"),
        FieldSpec(name="sort", label="Sort", type="string", default="hot"),
        FieldSpec(name="limit", label="Limit", type="number", default=10, mode="advanced"),
        FieldSpec(name="url", label="URL", type="string"),
        FieldSpec(name="kind", label="Kind (self|link)", type="string", default="self"),
        FieldSpec(name="article", label="Article ID", type="string"),
        FieldSpec(name="track_id", label="Track ID", type="string"),
        FieldSpec(name="artist_id", label="Artist ID", type="string"),
        FieldSpec(name="user_id", label="User ID", type="string"),
        FieldSpec(name="playlist_name", label="Playlist Name", type="string"),
        FieldSpec(name="playlist_description", label="Playlist Description", type="string"),
        FieldSpec(name="public", label="Public Playlist", type="boolean", default=False),
        FieldSpec(name="track_uris", label="Track URIs (JSON)", type="json", default=[]),
        FieldSpec(name="prompt_image", label="Prompt Image URL", type="string"),
        FieldSpec(name="prompt_text", label="Prompt Text", type="string"),
        FieldSpec(name="duration", label="Duration (sec)", type="number", default=5),
        FieldSpec(name="ratio", label="Aspect Ratio", type="string", default="1280:768"),
        FieldSpec(name="task_id", label="Task ID", type="string"),
        FieldSpec(name="input_text", label="Input Text", type="string"),
        FieldSpec(name="format", label="Format", type="string", default="presentation"),
        FieldSpec(name="num_cards", label="Number of Cards", type="number", default=10),
        FieldSpec(name="text_amount", label="Text Amount", type="string", default="detailed"),
        FieldSpec(name="generation_id", label="Generation ID", type="string"),
        FieldSpec(name="ids", label="Comma-separated IDs", type="string"),
        FieldSpec(name="album_id", label="Album ID", type="string"),
        FieldSpec(name="show_id", label="Show ID", type="string"),
        FieldSpec(name="episode_id", label="Episode ID", type="string"),
        FieldSpec(name="market", label="Market (ISO country)", type="string", default="US"),
        FieldSpec(name="type_kind", label="Type (artist|user)", type="string", default="artist"),
        FieldSpec(name="position_ms", label="Position (ms)", type="number", default=0),
        FieldSpec(
            name="repeat_state",
            label="Repeat State (off|track|context)",
            type="string",
            default="off",
        ),
        FieldSpec(name="volume_percent", label="Volume Percent", type="number", default=50),
        FieldSpec(name="shuffle_state", label="Shuffle State", type="boolean", default=False),
        FieldSpec(name="spotify_user_id", label="Spotify User ID", type="string"),
        FieldSpec(name="category_id", label="Category ID", type="string"),
        FieldSpec(name="image_base64", label="Image Base64", type="string"),
    ],
    operations=[
        OpSpec(
            id="search",
            label="Search",
            method="GET",
            path="/search",
            visible_fields=["query", "type", "limit"],
            query_builder=lambda v: {
                "q": getattr(v, "query", "") or "",
                "type": getattr(v, "type", "track") or "track",
                "limit": int(getattr(v, "limit", 10) or 10),
            },
        ),
        OpSpec(
            id="get_track",
            label="Get Track",
            method="GET",
            path="/tracks/{track_id}",
            visible_fields=["track_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_artist",
            label="Get Artist",
            method="GET",
            path="/artists/{artist_id}",
            visible_fields=["artist_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_user_playlists",
            label="List My Playlists",
            method="GET",
            path="/me/playlists",
            visible_fields=["limit"],
            query_builder=lambda v: {"limit": int(getattr(v, "limit", 10) or 10)},
        ),
        OpSpec(
            id="create_playlist",
            label="Create Playlist",
            method="POST",
            path="/users/{user_id}/playlists",
            visible_fields=["user_id", "playlist_name", "playlist_description"],
            body_builder=lambda v: {
                "name": getattr(v, "playlist_name", "") or "",
                "description": getattr(v, "playlist_description", None) or None,
                "public": bool(getattr(v, "public", False)),
            },
        ),
        OpSpec(
            id="add_tracks_to_playlist",
            label="Add Tracks to Playlist",
            method="POST",
            path="/playlists/{playlist_id}/tracks",
            visible_fields=["playlist_id", "track_uris"],
            body_builder=lambda v: {"uris": getattr(v, "track_uris", []) or []},
        ),
        OpSpec(
            id="get_tracks",
            label="Get Several Tracks",
            method="GET",
            path="/tracks",
            visible_fields=["ids"],
            query_builder=lambda v: {"ids": getattr(v, "ids", "") or ""},
        ),
        OpSpec(
            id="get_album",
            label="Get Album",
            method="GET",
            path="/albums/{album_id}",
            visible_fields=["album_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_albums",
            label="Get Several Albums",
            method="GET",
            path="/albums",
            visible_fields=["ids"],
            query_builder=lambda v: {"ids": getattr(v, "ids", "") or ""},
        ),
        OpSpec(
            id="get_album_tracks",
            label="Get Album Tracks",
            method="GET",
            path="/albums/{album_id}/tracks",
            visible_fields=["album_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_artists",
            label="Get Several Artists",
            method="GET",
            path="/artists",
            visible_fields=["ids"],
            query_builder=lambda v: {"ids": getattr(v, "ids", "") or ""},
        ),
        OpSpec(
            id="get_artist_albums",
            label="Get Artist Albums",
            method="GET",
            path="/artists/{artist_id}/albums",
            visible_fields=["artist_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_artist_top_tracks",
            label="Get Artist Top Tracks",
            method="GET",
            path="/artists/{artist_id}/top-tracks",
            visible_fields=["artist_id", "market"],
            query_builder=lambda v: {"market": getattr(v, "market", None) or "US"},
        ),
        OpSpec(
            id="follow_artists",
            label="Follow Artists",
            method="PUT",
            path="/me/following",
            visible_fields=["ids", "type_kind"],
            body_builder=lambda v: {"ids": (getattr(v, "ids", "") or "").split(",")},
        ),
        OpSpec(
            id="unfollow_artists",
            label="Unfollow Artists",
            method="DELETE",
            path="/me/following",
            visible_fields=["ids", "type_kind"],
            query_builder=lambda v: {
                "type": getattr(v, "type_kind", None) or "artist",
                "ids": getattr(v, "ids", "") or "",
            },
        ),
        OpSpec(
            id="get_followed_artists",
            label="Get Followed Artists",
            method="GET",
            path="/me/following",
            visible_fields=["type_kind"],
            query_builder=lambda v: {"type": getattr(v, "type_kind", None) or "artist"},
        ),
        OpSpec(
            id="get_show",
            label="Get Show",
            method="GET",
            path="/shows/{show_id}",
            visible_fields=["show_id", "market"],
            query_builder=lambda v: {"market": getattr(v, "market", None) or "US"},
        ),
        OpSpec(
            id="get_show_episodes",
            label="Get Show Episodes",
            method="GET",
            path="/shows/{show_id}/episodes",
            visible_fields=["show_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_episode",
            label="Get Episode",
            method="GET",
            path="/episodes/{episode_id}",
            visible_fields=["episode_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_saved_tracks",
            label="Get Saved Tracks",
            method="GET",
            path="/me/tracks",
            visible_fields=["limit"],
            query_builder=lambda v: {"limit": int(getattr(v, "limit", 20) or 20)},
        ),
        OpSpec(
            id="save_tracks",
            label="Save Tracks",
            method="PUT",
            path="/me/tracks",
            visible_fields=["ids"],
            body_builder=lambda v: {"ids": (getattr(v, "ids", "") or "").split(",")},
        ),
        OpSpec(
            id="remove_saved_tracks",
            label="Remove Saved Tracks",
            method="DELETE",
            path="/me/tracks",
            visible_fields=["ids"],
            query_builder=lambda v: {"ids": getattr(v, "ids", "") or ""},
        ),
        OpSpec(
            id="get_playlist",
            label="Get Playlist",
            method="GET",
            path="/playlists/{playlist_id}",
            visible_fields=["playlist_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_playlist_tracks",
            label="Get Playlist Tracks",
            method="GET",
            path="/playlists/{playlist_id}/tracks",
            visible_fields=["playlist_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="remove_playlist_tracks",
            label="Remove Playlist Tracks",
            method="DELETE",
            path="/playlists/{playlist_id}/tracks",
            visible_fields=["playlist_id", "track_uris"],
            body_builder=lambda v: {
                "tracks": [{"uri": u} for u in (getattr(v, "track_uris", []) or [])]
            },
        ),
        OpSpec(
            id="play",
            label="Start / Resume Playback",
            method="PUT",
            path="/me/player/play",
            visible_fields=[],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="pause",
            label="Pause Playback",
            method="PUT",
            path="/me/player/pause",
            visible_fields=[],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="skip_next",
            label="Skip to Next Track",
            method="POST",
            path="/me/player/next",
            visible_fields=[],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="skip_previous",
            label="Skip to Previous Track",
            method="POST",
            path="/me/player/previous",
            visible_fields=[],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="get_currently_playing",
            label="Get Currently Playing",
            method="GET",
            path="/me/player/currently-playing",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_devices",
            label="Get Available Devices",
            method="GET",
            path="/me/player/devices",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_playback_state",
            label="Get Playback State",
            method="GET",
            path="/me/player",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="seek",
            label="Seek to Position",
            method="PUT",
            path="/me/player/seek",
            visible_fields=["position_ms"],
            body_builder=lambda v: {"position_ms": int(getattr(v, "position_ms", 0) or 0)},
        ),
        OpSpec(
            id="set_repeat",
            label="Set Repeat Mode",
            method="PUT",
            path="/me/player/repeat",
            visible_fields=["repeat_state"],
            body_builder=lambda v: {"state": getattr(v, "repeat_state", None) or "off"},
        ),
        OpSpec(
            id="set_volume",
            label="Set Volume",
            method="PUT",
            path="/me/player/volume",
            visible_fields=["volume_percent"],
            body_builder=lambda v: {"volume_percent": int(getattr(v, "volume_percent", 50) or 50)},
        ),
        OpSpec(
            id="toggle_shuffle",
            label="Toggle Shuffle",
            method="PUT",
            path="/me/player/shuffle",
            visible_fields=["shuffle_state"],
            body_builder=lambda v: {"state": bool(getattr(v, "shuffle_state", False))},
        ),
        OpSpec(
            id="add_to_queue",
            label="Add to Queue",
            method="POST",
            path="/me/player/queue",
            visible_fields=["track_uris"],
            body_builder=lambda v: {
                "uri": (getattr(v, "track_uris", None) or [""])[0]
                if getattr(v, "track_uris", None)
                else ""
            },
        ),
        OpSpec(
            id="get_recently_played",
            label="Get Recently Played",
            method="GET",
            path="/me/player/recently-played",
            visible_fields=["limit"],
            query_builder=lambda v: {"limit": int(getattr(v, "limit", 20) or 20)},
        ),
        OpSpec(
            id="get_top_tracks",
            label="Get User's Top Tracks",
            method="GET",
            path="/me/top/tracks",
            visible_fields=["limit"],
            query_builder=lambda v: {"limit": int(getattr(v, "limit", 20) or 20)},
        ),
        OpSpec(
            id="get_top_artists",
            label="Get User's Top Artists",
            method="GET",
            path="/me/top/artists",
            visible_fields=["limit"],
            query_builder=lambda v: {"limit": int(getattr(v, "limit", 20) or 20)},
        ),
        OpSpec(
            id="get_user",
            label="Get User Profile",
            method="GET",
            path="/users/{spotify_user_id}",
            visible_fields=["spotify_user_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_user_playlists",
            label="Get User Playlists (public)",
            method="GET",
            path="/users/{spotify_user_id}/playlists",
            visible_fields=["spotify_user_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_new_releases",
            label="Get New Releases",
            method="GET",
            path="/browse/new-releases",
            visible_fields=["limit"],
            query_builder=lambda v: {"limit": int(getattr(v, "limit", 20) or 20)},
        ),
        OpSpec(
            id="get_categories",
            label="Get Browse Categories",
            method="GET",
            path="/browse/categories",
            visible_fields=["limit"],
            query_builder=lambda v: {"limit": int(getattr(v, "limit", 20) or 20)},
        ),
        OpSpec(
            id="get_category",
            label="Get Category",
            method="GET",
            path="/browse/categories/{category_id}",
            visible_fields=["category_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_category_playlists",
            label="Get Category Playlists",
            method="GET",
            path="/browse/categories/{category_id}/playlists",
            visible_fields=["category_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="check_saved_tracks",
            label="Check Saved Tracks",
            method="GET",
            path="/me/tracks/contains",
            visible_fields=["ids"],
            query_builder=lambda v: {"ids": getattr(v, "ids", "") or ""},
        ),
        OpSpec(
            id="check_saved_albums",
            label="Check Saved Albums",
            method="GET",
            path="/me/albums/contains",
            visible_fields=["ids"],
            query_builder=lambda v: {"ids": getattr(v, "ids", "") or ""},
        ),
        OpSpec(
            id="save_albums",
            label="Save Albums",
            method="PUT",
            path="/me/albums",
            visible_fields=["ids"],
            body_builder=lambda v: {"ids": (getattr(v, "ids", "") or "").split(",")},
        ),
        OpSpec(
            id="get_saved_albums",
            label="Get Saved Albums",
            method="GET",
            path="/me/albums",
            visible_fields=["limit"],
            query_builder=lambda v: {"limit": int(getattr(v, "limit", 20) or 20)},
        ),
        OpSpec(
            id="update_playlist",
            label="Update Playlist Details",
            method="PUT",
            path="/playlists/{playlist_id}",
            visible_fields=["playlist_id", "playlist_name", "playlist_description"],
            body_builder=lambda v: {
                k: val
                for k, val in {
                    "name": getattr(v, "playlist_name", None) or None,
                    "description": getattr(v, "playlist_description", None) or None,
                }.items()
                if val is not None
            },
        ),
        OpSpec(
            id="upload_playlist_cover",
            label="Upload Playlist Cover (base64 JPEG)",
            method="PUT",
            path="/playlists/{playlist_id}/images",
            visible_fields=["playlist_id", "image_base64"],
            body_builder=lambda v: getattr(v, "image_base64", "") or "",
        ),
        OpSpec(
            id="get_featured_playlists",
            label="Get Featured Playlists",
            method="GET",
            path="/browse/featured-playlists",
            visible_fields=["limit"],
            query_builder=lambda v: {"limit": int(getattr(v, "limit", 20) or 20)},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "id", "type": "string"},
    ],
    allow_error=True,
)
