"""Spotify action node — Spotify — playback, playlists, tracks, artist metadata.

REST at https://api.spotify.com/v1. See sim-parity roadmap Phase 4.29.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.spotify",
    name="Spotify",
    category="integration",
    description="Spotify — playback, playlists, tracks, artist metadata.",
    icon_slug="spotify",
    color="#1DB954",
    base_url="https://api.spotify.com/v1",
    credential_type="spotify_api_key",
    token_field=["api_key"],
    auth="bearer",
    fields=[
        FieldSpec(name="query", label="Query", type="string"),
        FieldSpec(
            name="max_results", label="Max Results", type="number", default=10, mode="advanced"
        ),
        FieldSpec(name="type", label="Type", type="string"),
        FieldSpec(name="video_id", label="Video ID", type="string"),
        FieldSpec(name="channel_id", label="Channel ID", type="string"),
        FieldSpec(name="playlist_id", label="Playlist ID", type="string"),
        FieldSpec(name="post_id", label="Post ID", type="string"),
        FieldSpec(name="title", label="Title", type="string"),
        FieldSpec(name="content", label="Content (HTML)", type="string"),
        FieldSpec(name="status", label="Status", type="string", default="draft"),
        FieldSpec(name="per_page", label="Per Page", type="number", default=10, mode="advanced"),
        FieldSpec(name="text", label="Text", type="string"),
        FieldSpec(name="tweet_id", label="Tweet ID", type="string"),
        FieldSpec(name="username", label="Username", type="string"),
        FieldSpec(name="subreddit", label="Subreddit", type="string"),
        FieldSpec(name="sort", label="Sort", type="string", default="hot"),
        FieldSpec(name="limit", label="Limit", type="number", default=10, mode="advanced"),
        FieldSpec(name="url", label="URL", type="string"),
        FieldSpec(name="kind", label="Kind (self|link)", type="string", default="self"),
        FieldSpec(name="article", label="Article ID", type="string"),
        FieldSpec(name="track_id", label="Track ID", type="string"),
        FieldSpec(name="artist_id", label="Artist ID", type="string"),
        FieldSpec(name="user_id", label="User ID", type="string"),
        FieldSpec(name="playlist_name", label="Playlist Name", type="string"),
        FieldSpec(name="playlist_description", label="Playlist Description", type="string"),
        FieldSpec(name="public", label="Public Playlist", type="boolean", default=False),
        FieldSpec(name="track_uris", label="Track URIs (JSON)", type="json", default=[]),
        FieldSpec(name="prompt_image", label="Prompt Image URL", type="string"),
        FieldSpec(name="prompt_text", label="Prompt Text", type="string"),
        FieldSpec(name="duration", label="Duration (sec)", type="number", default=5),
        FieldSpec(name="ratio", label="Aspect Ratio", type="string", default="1280:768"),
        FieldSpec(name="task_id", label="Task ID", type="string"),
        FieldSpec(name="input_text", label="Input Text", type="string"),
        FieldSpec(name="format", label="Format", type="string", default="presentation"),
        FieldSpec(name="num_cards", label="Number of Cards", type="number", default=10),
        FieldSpec(name="text_amount", label="Text Amount", type="string", default="detailed"),
        FieldSpec(name="generation_id", label="Generation ID", type="string"),
    ],
    operations=[
        OpSpec(
            id="search",
            label="Search",
            method="GET",
            path="/search",
            visible_fields=["query", "type", "limit"],
            query_builder=lambda v: {
                "q": getattr(v, "query", "") or "",
                "type": getattr(v, "type", "track") or "track",
                "limit": int(getattr(v, "limit", 10) or 10),
            },
        ),
        OpSpec(
            id="get_track",
            label="Get Track",
            method="GET",
            path="/tracks/{track_id}",
            visible_fields=["track_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_artist",
            label="Get Artist",
            method="GET",
            path="/artists/{artist_id}",
            visible_fields=["artist_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_user_playlists",
            label="List My Playlists",
            method="GET",
            path="/me/playlists",
            visible_fields=["limit"],
            query_builder=lambda v: {"limit": int(getattr(v, "limit", 10) or 10)},
        ),
        OpSpec(
            id="create_playlist",
            label="Create Playlist",
            method="POST",
            path="/users/{user_id}/playlists",
            visible_fields=["user_id", "playlist_name", "playlist_description"],
            body_builder=lambda v: {
                "name": getattr(v, "playlist_name", "") or "",
                "description": getattr(v, "playlist_description", None) or None,
                "public": bool(getattr(v, "public", False)),
            },
        ),
        OpSpec(
            id="add_tracks_to_playlist",
            label="Add Tracks to Playlist",
            method="POST",
            path="/playlists/{playlist_id}/tracks",
            visible_fields=["playlist_id", "track_uris"],
            body_builder=lambda v: {"uris": getattr(v, "track_uris", []) or []},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "id", "type": "string"},
    ],
    allow_error=True,
)
