"""Rippling action node — Rippling — HR platform (employees, orgs, payroll).

REST at https://api.rippling.com. See sim-parity roadmap Phase 4.24.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.rippling",
    name="Rippling",
    category="integration",
    description="Rippling — HR platform (employees, orgs, payroll).",
    icon_slug="rippling",
    color="#1c1c1c",
    base_url="https://api.rippling.com",
    credential_type="rippling_api_key",
    token_field=["api_key"],
    auth="bearer",
    fields=[
        FieldSpec(name="employee_id", label="Employee ID", type="string"),
        FieldSpec(name="worker_id", label="Worker ID", type="string"),
        FieldSpec(name="user_id", label="User ID", type="string"),
        FieldSpec(name="contact_id", label="Contact ID", type="string"),
        FieldSpec(name="tenant", label="Tenant", type="string"),
        FieldSpec(name="raas_url", label="RaaS Report URL", type="string"),
        FieldSpec(name="report_id", label="Report ID", type="string"),
        FieldSpec(name="expense_id", label="Expense ID", type="string"),
        FieldSpec(name="first_name", label="First Name", type="string"),
        FieldSpec(name="last_name", label="Last Name", type="string"),
        FieldSpec(name="email", label="Email", type="string"),
        FieldSpec(name="content", label="Content", type="string"),
        FieldSpec(name="limit", label="Limit", type="number", default=25, mode="advanced"),
        FieldSpec(name="offset", label="Offset", type="number", default=0, mode="advanced"),
        FieldSpec(name="compensation_id", label="Compensation ID", type="string"),
        FieldSpec(name="request_id", label="Request ID", type="string"),
        FieldSpec(name="pay_run_id", label="Pay Run ID", type="string"),
        FieldSpec(name="pay_stub_id", label="Pay Stub ID", type="string"),
        FieldSpec(name="title_id", label="Title ID", type="string"),
        FieldSpec(name="title_body", label="Title Body (JSON)", type="json", default={}),
        FieldSpec(name="job_function_id", label="Job Function ID", type="string"),
        FieldSpec(name="work_location_id", label="Work Location ID", type="string"),
        FieldSpec(
            name="work_location_body", label="Work Location Body (JSON)", type="json", default={}
        ),
        FieldSpec(name="business_partner_id", label="Business Partner ID", type="string"),
        FieldSpec(name="supergroup_id", label="Supergroup ID", type="string"),
        FieldSpec(name="department_id", label="Department ID", type="string"),
        FieldSpec(name="department_body", label="Department Body (JSON)", type="json", default={}),
        FieldSpec(name="employment_type_id", label="Employment Type ID", type="string"),
        FieldSpec(name="team_id", label="Team ID", type="string"),
    ],
    operations=[
        OpSpec(
            id="list_employees",
            label="List Employees",
            method="GET",
            path="/platform/api/employees",
            visible_fields=["limit"],
            query_builder=lambda v: {"limit": int(getattr(v, "limit", 25) or 25)},
        ),
        OpSpec(
            id="get_employee",
            label="Get Employee",
            method="GET",
            path="/platform/api/employees/{employee_id}",
            visible_fields=["employee_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_departments",
            label="List Departments",
            method="GET",
            path="/platform/api/departments",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_teams",
            label="List Teams",
            method="GET",
            path="/platform/api/teams",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_work_locations",
            label="List Work Locations",
            method="GET",
            path="/platform/api/work_locations",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_compensations",
            label="List Compensations",
            method="GET",
            path="/platform/api/compensations",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_compensation",
            label="Get Compensation",
            method="GET",
            path="/platform/api/compensations/{compensation_id}",
            visible_fields=["compensation_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_time_off_balances",
            label="List Time Off Balances",
            method="GET",
            path="/platform/api/time_off_balances",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_time_off_requests",
            label="List Time Off Requests",
            method="GET",
            path="/platform/api/time_off_requests",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_time_off_request",
            label="Get Time Off Request",
            method="GET",
            path="/platform/api/time_off_requests/{request_id}",
            visible_fields=["request_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_employment_types",
            label="List Employment Types",
            method="GET",
            path="/platform/api/employment_types",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_pay_frequencies",
            label="List Pay Frequencies",
            method="GET",
            path="/platform/api/pay_frequencies",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_pay_groups",
            label="List Pay Groups",
            method="GET",
            path="/platform/api/pay_groups",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_pay_runs",
            label="List Pay Runs",
            method="GET",
            path="/platform/api/pay_runs",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_pay_run",
            label="Get Pay Run",
            method="GET",
            path="/platform/api/pay_runs/{pay_run_id}",
            visible_fields=["pay_run_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_workers",
            label="List Workers (contractors + employees)",
            method="GET",
            path="/platform/api/workers",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_worker",
            label="Get Worker",
            method="GET",
            path="/platform/api/workers/{worker_id}",
            visible_fields=["worker_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_pay_stubs",
            label="List Pay Stubs",
            method="GET",
            path="/platform/api/pay_stubs",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_pay_stub",
            label="Get Pay Stub",
            method="GET",
            path="/platform/api/pay_stubs/{pay_stub_id}",
            visible_fields=["pay_stub_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_company",
            label="Get Company Info",
            method="GET",
            path="/platform/api/company",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_leaves",
            label="List Leaves",
            method="GET",
            path="/platform/api/leaves",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_titles",
            label="List Titles",
            method="GET",
            path="/platform/api/titles",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_title",
            label="Get Title",
            method="GET",
            path="/platform/api/titles/{title_id}",
            visible_fields=["title_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_title",
            label="Create Title",
            method="POST",
            path="/platform/api/titles",
            visible_fields=["title_body"],
            body_builder=lambda v: getattr(v, "title_body", None) or {},
        ),
        OpSpec(
            id="update_title",
            label="Update Title",
            method="PUT",
            path="/platform/api/titles/{title_id}",
            visible_fields=["title_id", "title_body"],
            body_builder=lambda v: getattr(v, "title_body", None) or {},
        ),
        OpSpec(
            id="delete_title",
            label="Delete Title",
            method="DELETE",
            path="/platform/api/titles/{title_id}",
            visible_fields=["title_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_custom_fields",
            label="List Custom Fields",
            method="GET",
            path="/platform/api/custom_fields",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_job_functions",
            label="List Job Functions",
            method="GET",
            path="/platform/api/job_functions",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_job_function",
            label="Get Job Function",
            method="GET",
            path="/platform/api/job_functions/{job_function_id}",
            visible_fields=["job_function_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_work_location",
            label="Create Work Location",
            method="POST",
            path="/platform/api/work_locations",
            visible_fields=["work_location_body"],
            body_builder=lambda v: getattr(v, "work_location_body", None) or {},
        ),
        OpSpec(
            id="update_work_location",
            label="Update Work Location",
            method="PUT",
            path="/platform/api/work_locations/{work_location_id}",
            visible_fields=["work_location_id", "work_location_body"],
            body_builder=lambda v: getattr(v, "work_location_body", None) or {},
        ),
        OpSpec(
            id="delete_work_location",
            label="Delete Work Location",
            method="DELETE",
            path="/platform/api/work_locations/{work_location_id}",
            visible_fields=["work_location_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_business_partners",
            label="List Business Partners",
            method="GET",
            path="/platform/api/business_partners",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_business_partner",
            label="Get Business Partner",
            method="GET",
            path="/platform/api/business_partners/{business_partner_id}",
            visible_fields=["business_partner_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_supergroups",
            label="List Supergroups",
            method="GET",
            path="/platform/api/supergroups",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_supergroup",
            label="Get Supergroup",
            method="GET",
            path="/platform/api/supergroups/{supergroup_id}",
            visible_fields=["supergroup_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_employee_reports",
            label="List Employee Reports (org chart)",
            method="GET",
            path="/platform/api/reports",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_department",
            label="Get Department",
            method="GET",
            path="/platform/api/departments/{department_id}",
            visible_fields=["department_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_department",
            label="Create Department",
            method="POST",
            path="/platform/api/departments",
            visible_fields=["department_body"],
            body_builder=lambda v: getattr(v, "department_body", None) or {},
        ),
        OpSpec(
            id="update_department",
            label="Update Department",
            method="PUT",
            path="/platform/api/departments/{department_id}",
            visible_fields=["department_id", "department_body"],
            body_builder=lambda v: getattr(v, "department_body", None) or {},
        ),
        OpSpec(
            id="get_employment_type",
            label="Get Employment Type",
            method="GET",
            path="/platform/api/employment_types/{employment_type_id}",
            visible_fields=["employment_type_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_team",
            label="Get Team",
            method="GET",
            path="/platform/api/teams/{team_id}",
            visible_fields=["team_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_users",
            label="List Users (platform users)",
            method="GET",
            path="/platform/api/users",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_user",
            label="Get User",
            method="GET",
            path="/platform/api/users/{user_id}",
            visible_fields=["user_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_current_user",
            label="Get Current User",
            method="GET",
            path="/platform/api/me",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_entitlements",
            label="List Entitlements",
            method="GET",
            path="/platform/api/entitlements",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_expense_reports",
            label="List Expense Reports",
            method="GET",
            path="/expense/api/reports",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_bank_accounts",
            label="List Bank Accounts",
            method="GET",
            path="/platform/api/bank_accounts",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_ssn_hashes",
            label="List SSN Hashes",
            method="GET",
            path="/platform/api/employees/ssn_hashes",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "results", "type": "array"},
    ],
    allow_error=True,
)
