"""AWS Identity Center action node — AWS Identity Center (SSO) — users, groups, permissions.

REST at https://identitystore.{region}.amazonaws.com. See sim-parity roadmap Phase 4.25.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.identity_center",
    name="AWS Identity Center",
    category="integration",
    description="AWS Identity Center (SSO) — users, groups, permissions.",
    icon_slug="identity_center",
    color="#ffffff",
    base_url="https://identitystore.{region}.amazonaws.com",
    credential_type="aws_credentials",
    token_field=["api_key"],
    auth="aws_sigv4",
    aws_service="identitystore",
    extra_headers={"X-Amz-Target": "AWSIdentityStore.ListUsers"},
    fields=[
        FieldSpec(name="user_id", label="User ID", type="string"),
        FieldSpec(name="group_id", label="Group ID", type="string"),
        FieldSpec(name="email", label="Email", type="string"),
        FieldSpec(name="password", label="Password", type="string", secret=True),
        FieldSpec(name="first_name", label="First Name", type="string"),
        FieldSpec(name="last_name", label="Last Name", type="string"),
        FieldSpec(name="vault_id", label="Vault ID", type="string"),
        FieldSpec(name="item_id", label="Item ID", type="string"),
        FieldSpec(name="title", label="Title", type="string"),
        FieldSpec(name="identity_store_id", label="Identity Store ID", type="string"),
        FieldSpec(name="workspace_id", label="Workspace ID", type="string"),
        FieldSpec(name="environment", label="Environment slug", type="string"),
        FieldSpec(name="secret_path", label="Secret Path", type="string", default="/"),
        FieldSpec(name="secret_name", label="Secret Name", type="string"),
        FieldSpec(name="secret_value", label="Secret Value", type="string"),
        FieldSpec(name="query", label="Query", type="string"),
        FieldSpec(name="limit", label="Limit", type="number", default=25, mode="advanced"),
        FieldSpec(name="instance_arn", label="Instance ARN", type="string"),
        FieldSpec(name="account_id", label="AWS Account ID", type="string"),
        FieldSpec(name="permission_set_arn", label="Permission Set ARN", type="string"),
        FieldSpec(name="principal_id", label="Principal ID", type="string"),
        FieldSpec(
            name="principal_type",
            label="Principal Type (USER|GROUP)",
            type="string",
            default="USER",
        ),
        FieldSpec(name="request_id", label="Request ID (assignment)", type="string"),
    ],
    operations=[
        OpSpec(
            id="list_users",
            label="List Users",
            method="POST",
            path="/",
            visible_fields=["identity_store_id"],
            body_builder=lambda v: {"IdentityStoreId": getattr(v, "identity_store_id", "") or ""},
        ),
        OpSpec(
            id="list_groups",
            label="List Groups",
            method="POST",
            path="/",
            visible_fields=["identity_store_id"],
            body_builder=lambda v: {"IdentityStoreId": getattr(v, "identity_store_id", "") or ""},
        ),
        OpSpec(
            id="list_instances",
            label="List Instances",
            method="POST",
            path="/",
            visible_fields=[],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="list_accounts",
            label="List Accounts",
            method="POST",
            path="/",
            visible_fields=[],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="describe_account",
            label="Describe Account",
            method="POST",
            path="/",
            visible_fields=["account_id"],
            body_builder=lambda v: {"AccountId": getattr(v, "account_id", "") or ""},
        ),
        OpSpec(
            id="list_permission_sets",
            label="List Permission Sets",
            method="POST",
            path="/",
            visible_fields=["instance_arn"],
            body_builder=lambda v: {"InstanceArn": getattr(v, "instance_arn", "") or ""},
        ),
        OpSpec(
            id="get_user",
            label="Get User",
            method="POST",
            path="/",
            visible_fields=["identity_store_id", "user_id"],
            body_builder=lambda v: {
                "IdentityStoreId": getattr(v, "identity_store_id", "") or "",
                "UserId": getattr(v, "user_id", "") or "",
            },
        ),
        OpSpec(
            id="get_group",
            label="Get Group",
            method="POST",
            path="/",
            visible_fields=["identity_store_id", "group_id"],
            body_builder=lambda v: {
                "IdentityStoreId": getattr(v, "identity_store_id", "") or "",
                "GroupId": getattr(v, "group_id", "") or "",
            },
        ),
        OpSpec(
            id="create_account_assignment",
            label="Create Account Assignment",
            method="POST",
            path="/",
            visible_fields=[
                "instance_arn",
                "account_id",
                "permission_set_arn",
                "principal_id",
                "principal_type",
            ],
            body_builder=lambda v: {
                "InstanceArn": getattr(v, "instance_arn", "") or "",
                "TargetId": getattr(v, "account_id", "") or "",
                "TargetType": "AWS_ACCOUNT",
                "PermissionSetArn": getattr(v, "permission_set_arn", "") or "",
                "PrincipalId": getattr(v, "principal_id", "") or "",
                "PrincipalType": getattr(v, "principal_type", None) or "USER",
            },
        ),
        OpSpec(
            id="delete_account_assignment",
            label="Delete Account Assignment",
            method="POST",
            path="/",
            visible_fields=[
                "instance_arn",
                "account_id",
                "permission_set_arn",
                "principal_id",
                "principal_type",
            ],
            body_builder=lambda v: {
                "InstanceArn": getattr(v, "instance_arn", "") or "",
                "TargetId": getattr(v, "account_id", "") or "",
                "TargetType": "AWS_ACCOUNT",
                "PermissionSetArn": getattr(v, "permission_set_arn", "") or "",
                "PrincipalId": getattr(v, "principal_id", "") or "",
                "PrincipalType": getattr(v, "principal_type", None) or "USER",
            },
        ),
        OpSpec(
            id="check_assignment_status",
            label="Describe Assignment Creation Status",
            method="POST",
            path="/",
            visible_fields=["instance_arn", "request_id"],
            body_builder=lambda v: {
                "InstanceArn": getattr(v, "instance_arn", "") or "",
                "AccountAssignmentCreationRequestId": getattr(v, "request_id", "") or "",
            },
        ),
        OpSpec(
            id="check_assignment_deletion_status",
            label="Describe Assignment Deletion Status",
            method="POST",
            path="/",
            visible_fields=["instance_arn", "request_id"],
            body_builder=lambda v: {
                "InstanceArn": getattr(v, "instance_arn", "") or "",
                "AccountAssignmentDeletionRequestId": getattr(v, "request_id", "") or "",
            },
        ),
        OpSpec(
            id="list_account_assignments",
            label="List Account Assignments",
            method="POST",
            path="/",
            visible_fields=["instance_arn", "account_id", "permission_set_arn"],
            body_builder=lambda v: {
                "InstanceArn": getattr(v, "instance_arn", "") or "",
                "AccountId": getattr(v, "account_id", "") or "",
                "PermissionSetArn": getattr(v, "permission_set_arn", "") or "",
            },
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "id", "type": "string"},
    ],
    allow_error=True,
)
