"""Obsidian Local REST action node — Obsidian Local REST plugin — vault notes CRUD.

REST at https://{host}. See sim-parity roadmap Phase 4.32.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.obsidian",
    name="Obsidian Local REST",
    category="integration",
    description="Obsidian Local REST plugin — vault notes CRUD.",
    icon_slug="obsidian",
    color="#ffffff",
    base_url="https://{host}",
    credential_type="obsidian_api_key",
    token_field=["api_key"],
    auth="bearer",
    fields=[
        FieldSpec(name="table", label="Table", type="string"),
        FieldSpec(name="record_id", label="Record ID", type="string"),
        FieldSpec(name="filter", label="Filter", type="string"),
        FieldSpec(name="data", label="Data (JSON)", type="json", default={}),
        FieldSpec(name="config_id", label="Sync Config ID", type="string"),
        FieldSpec(name="query_text", label="Query Text", type="string"),
        FieldSpec(name="destination_id", label="Destination ID", type="string"),
        FieldSpec(name="property_id", label="Property ID", type="string"),
        FieldSpec(name="email", label="Email", type="string"),
        FieldSpec(name="right", label="Right (delete|access|...)", type="string", default="delete"),
        FieldSpec(name="source", label="LaTeX Source", type="string"),
        FieldSpec(name="query", label="Query", type="string"),
        FieldSpec(name="depth", label="Depth (standard|deep)", type="string", default="standard"),
        FieldSpec(name="output_type", label="Output Type", type="string", default="searchResults"),
        FieldSpec(name="supplier_id", label="Supplier ID", type="string"),
        FieldSpec(name="path", label="Path", type="string"),
        FieldSpec(name="content", label="Content", type="string"),
        FieldSpec(name="message", label="Message", type="string"),
        FieldSpec(name="project_id", label="Project ID", type="string"),
        FieldSpec(name="file_url", label="File URL", type="string"),
        FieldSpec(name="json_schema", label="Schema (JSON)", type="json", default={}),
        FieldSpec(name="job_id", label="Job ID", type="string"),
        FieldSpec(name="company_id", label="Company ID", type="string"),
        FieldSpec(name="event_id", label="Event ID", type="string"),
        FieldSpec(name="remote", label="Remote (github|gitlab)", type="string", default="github"),
        FieldSpec(name="repository", label="Repository (owner/repo)", type="string"),
        FieldSpec(name="branch", label="Branch", type="string", default="main"),
        FieldSpec(name="repositories", label="Repositories (JSON)", type="json", default=[]),
        FieldSpec(name="guard_name", label="Guard Name", type="string"),
        FieldSpec(name="llm_output", label="LLM Output", type="string"),
        FieldSpec(name="host_ids", label="Host IDs (JSON)", type="json", default=[]),
        FieldSpec(name="limit", label="Limit", type="number", default=50, mode="advanced"),
        FieldSpec(
            name="period",
            label="Period (daily|weekly|monthly|quarterly|yearly)",
            type="string",
            default="daily",
        ),
        FieldSpec(name="obsidian_query", label="Search Query", type="string"),
        FieldSpec(
            name="patch_operation",
            label="Patch Op (append|prepend|replace)",
            type="string",
            default="append",
        ),
        FieldSpec(
            name="patch_target",
            label="Patch Target (heading|block|frontmatter)",
            type="string",
            default="heading",
        ),
        FieldSpec(name="patch_target_value", label="Patch Target Value", type="string"),
        FieldSpec(name="obsidian_command_id", label="Command ID", type="string"),
    ],
    operations=[
        OpSpec(
            id="get_note",
            label="Get Note",
            method="GET",
            path="/vault/{path}",
            visible_fields=["path"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="delete_note",
            label="Delete Note",
            method="DELETE",
            path="/vault/{path}",
            visible_fields=["path"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_files",
            label="List Files in Vault",
            method="GET",
            path="/vault",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_note",
            label="Create / Update Note",
            method="PUT",
            path="/vault/{path}",
            visible_fields=["path", "content"],
            body_builder=lambda v: getattr(v, "content", "") or "",
        ),
        OpSpec(
            id="append_note",
            label="Append to Note",
            method="POST",
            path="/vault/{path}",
            visible_fields=["path", "content"],
            body_builder=lambda v: getattr(v, "content", "") or "",
        ),
        OpSpec(
            id="patch_note",
            label="Patch Note",
            method="PATCH",
            path="/vault/{path}",
            visible_fields=[
                "path",
                "patch_operation",
                "patch_target",
                "patch_target_value",
                "content",
            ],
            body_builder=lambda v: getattr(v, "content", "") or "",
        ),
        OpSpec(
            id="search",
            label="Search Vault (simple)",
            method="POST",
            path="/search/simple/",
            visible_fields=["obsidian_query"],
            body_builder=lambda v: {"query": getattr(v, "obsidian_query", "") or ""},
        ),
        OpSpec(
            id="get_active",
            label="Get Active File",
            method="GET",
            path="/active/",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="append_active",
            label="Append to Active File",
            method="POST",
            path="/active/",
            visible_fields=["content"],
            body_builder=lambda v: getattr(v, "content", "") or "",
        ),
        OpSpec(
            id="patch_active",
            label="Patch Active File",
            method="PATCH",
            path="/active/",
            visible_fields=["content"],
            body_builder=lambda v: getattr(v, "content", "") or "",
        ),
        OpSpec(
            id="open_file",
            label="Open File",
            method="POST",
            path="/open/{path}",
            visible_fields=["path"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="list_commands",
            label="List Commands",
            method="GET",
            path="/commands/",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="execute_command",
            label="Execute Command",
            method="POST",
            path="/commands/{obsidian_command_id}/",
            visible_fields=["obsidian_command_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="get_periodic_note",
            label="Get Periodic Note",
            method="GET",
            path="/periodic/{period}/",
            visible_fields=["period"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="append_periodic_note",
            label="Append to Periodic Note",
            method="POST",
            path="/periodic/{period}/",
            visible_fields=["period", "content"],
            body_builder=lambda v: getattr(v, "content", "") or "",
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "id", "type": "string"},
    ],
    allow_error=True,
)
