"""Jira Service Management action node — Jira Service Management — requests, service desks, queues.

REST at https://{domain}/rest/servicedeskapi. See sim-parity roadmap Phase 4.28.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.jira_service_management",
    name="Jira Service Management",
    category="integration",
    description="Jira Service Management — requests, service desks, queues.",
    icon_slug="jira_service_management",
    color="#1c1c1c",
    base_url="https://{domain}/rest/servicedeskapi",
    credential_type="jira_service_management_api_key",
    token_field=["api_key"],
    auth="basic",
    auth_basic_username="{email}",
    fields=[
        FieldSpec(name="user_id", label="User ID", type="string"),
        FieldSpec(name="group_id", label="Group ID", type="string"),
        FieldSpec(name="user_principal_name", label="User Principal Name", type="string"),
        FieldSpec(name="display_name", label="Display Name", type="string"),
        FieldSpec(name="mail_nickname", label="Mail Nickname", type="string"),
        FieldSpec(name="password", label="Password", type="string", secret=True),
        FieldSpec(name="top", label="Top", type="number", default=25, mode="advanced"),
        FieldSpec(name="filter", label="Filter", type="string", mode="advanced"),
        FieldSpec(name="entity", label="Entity (plural)", type="string", placeholder="accounts"),
        FieldSpec(name="record_id", label="Record GUID", type="string"),
        FieldSpec(name="select", label="Select", type="string", mode="advanced"),
        FieldSpec(name="data", label="Data (JSON)", type="json", default={}),
        FieldSpec(name="service_desk_id", label="Service Desk ID", type="string"),
        FieldSpec(name="request_type_id", label="Request Type ID", type="string"),
        FieldSpec(name="summary", label="Summary", type="string"),
        FieldSpec(name="description", label="Description", type="string"),
        FieldSpec(name="issue_key", label="Issue Key", type="string"),
        FieldSpec(
            name="request_status", label="Request Status", type="string", default="OPEN_REQUESTS"
        ),
        FieldSpec(name="comment_body", label="Comment Body", type="string"),
        FieldSpec(name="public", label="Public", type="boolean", default=True),
        FieldSpec(name="origin_zip", label="Origin ZIP", type="string"),
        FieldSpec(name="destination_zip", label="Destination ZIP", type="string"),
        FieldSpec(name="weight_lb", label="Weight (lb)", type="number"),
        FieldSpec(name="commodity", label="Commodity", type="string"),
        FieldSpec(name="quote_id", label="Quote ID", type="string"),
        FieldSpec(name="shipment_id", label="Shipment ID", type="string"),
        FieldSpec(name="comment_id", label="Comment ID", type="string"),
        FieldSpec(name="customer_username", label="Customer Username", type="string"),
        FieldSpec(name="organization_id", label="Organization ID", type="string"),
        FieldSpec(name="organization_name", label="Organization Name", type="string"),
        FieldSpec(name="queue_id", label="Queue ID", type="string"),
        FieldSpec(name="transition_id", label="Transition ID", type="string"),
        FieldSpec(name="sla_metric_id", label="SLA Metric ID", type="string"),
        FieldSpec(
            name="participants",
            label="Participants (JSON array of account IDs)",
            type="json",
            default=[],
        ),
        FieldSpec(name="approval_id", label="Approval ID", type="string"),
        FieldSpec(
            name="approval_decision",
            label="Decision (approve|decline)",
            type="string",
            default="approve",
        ),
        FieldSpec(name="query", label="Query", type="string"),
        FieldSpec(
            name="temporary_attachment_ids",
            label="Temporary Attachment IDs (JSON)",
            type="json",
            default=[],
        ),
        FieldSpec(name="rating", label="Rating (1-5)", type="number", default=5),
    ],
    operations=[
        OpSpec(
            id="list_service_desks",
            label="List Service Desks",
            method="GET",
            path="/servicedesk",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_request_types",
            label="List Request Types",
            method="GET",
            path="/servicedesk/{service_desk_id}/requesttype",
            visible_fields=["service_desk_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_request",
            label="Create Request",
            method="POST",
            path="/request",
            visible_fields=["service_desk_id", "request_type_id", "summary", "description"],
            body_builder=lambda v: {
                "serviceDeskId": getattr(v, "service_desk_id", "") or "",
                "requestTypeId": getattr(v, "request_type_id", "") or "",
                "requestFieldValues": {
                    "summary": getattr(v, "summary", "") or "",
                    "description": getattr(v, "description", None) or "",
                },
            },
        ),
        OpSpec(
            id="get_request",
            label="Get Request",
            method="GET",
            path="/request/{issue_key}",
            visible_fields=["issue_key"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_requests",
            label="List My Requests",
            method="GET",
            path="/request",
            visible_fields=["service_desk_id", "request_status"],
            query_builder=lambda v: {
                k: val
                for k, val in {
                    "serviceDeskId": getattr(v, "service_desk_id", None) or None,
                    "requestStatus": getattr(v, "request_status", None) or None,
                }.items()
                if val
            },
        ),
        OpSpec(
            id="add_comment",
            label="Add Comment to Request",
            method="POST",
            path="/request/{issue_key}/comment",
            visible_fields=["issue_key", "comment_body", "public"],
            body_builder=lambda v: {
                "body": getattr(v, "comment_body", "") or "",
                "public": bool(getattr(v, "public", True)),
            },
        ),
        OpSpec(
            id="get_request_status",
            label="Get Request Status",
            method="GET",
            path="/request/{issue_key}/status",
            visible_fields=["issue_key"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_comments",
            label="List Request Comments",
            method="GET",
            path="/request/{issue_key}/comment",
            visible_fields=["issue_key"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_comment",
            label="Get Request Comment",
            method="GET",
            path="/request/{issue_key}/comment/{comment_id}",
            visible_fields=["issue_key", "comment_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_attachments",
            label="List Request Attachments",
            method="GET",
            path="/request/{issue_key}/attachment",
            visible_fields=["issue_key"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_customers",
            label="List Customers",
            method="GET",
            path="/servicedesk/{service_desk_id}/customer",
            visible_fields=["service_desk_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="add_customer",
            label="Add Customer to Service Desk",
            method="POST",
            path="/servicedesk/{service_desk_id}/customer",
            visible_fields=["service_desk_id", "customer_username"],
            body_builder=lambda v: {"usernames": [getattr(v, "customer_username", "") or ""]},
        ),
        OpSpec(
            id="list_orgs",
            label="List Organizations",
            method="GET",
            path="/organization",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_org",
            label="Get Organization",
            method="GET",
            path="/organization/{organization_id}",
            visible_fields=["organization_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_org",
            label="Create Organization",
            method="POST",
            path="/organization",
            visible_fields=["organization_name"],
            body_builder=lambda v: {"name": getattr(v, "organization_name", "") or ""},
        ),
        OpSpec(
            id="list_org_users",
            label="List Users in Organization",
            method="GET",
            path="/organization/{organization_id}/user",
            visible_fields=["organization_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_queues",
            label="List Service Desk Queues",
            method="GET",
            path="/servicedesk/{service_desk_id}/queue",
            visible_fields=["service_desk_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_queue_issues",
            label="Get Queue Issues",
            method="GET",
            path="/servicedesk/{service_desk_id}/queue/{queue_id}/issue",
            visible_fields=["service_desk_id", "queue_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="transition_request",
            label="Transition Request",
            method="POST",
            path="/request/{issue_key}/transition",
            visible_fields=["issue_key", "transition_id", "comment_body"],
            body_builder=lambda v: {
                "id": getattr(v, "transition_id", "") or "",
                "additionalComment": {"body": getattr(v, "comment_body", None) or ""}
                if getattr(v, "comment_body", None)
                else None,
            },
        ),
        OpSpec(
            id="get_transitions",
            label="Get Available Transitions",
            method="GET",
            path="/request/{issue_key}/transition",
            visible_fields=["issue_key"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_sla",
            label="Get Request SLA",
            method="GET",
            path="/request/{issue_key}/sla",
            visible_fields=["issue_key"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_slas",
            label="List SLAs on Request",
            method="GET",
            path="/request/{issue_key}/sla",
            visible_fields=["issue_key"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_sla_metric",
            label="Get SLA Metric",
            method="GET",
            path="/request/{issue_key}/sla/{sla_metric_id}",
            visible_fields=["issue_key", "sla_metric_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_participants",
            label="List Request Participants",
            method="GET",
            path="/request/{issue_key}/participant",
            visible_fields=["issue_key"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="add_participants",
            label="Add Request Participants",
            method="POST",
            path="/request/{issue_key}/participant",
            visible_fields=["issue_key", "participants"],
            body_builder=lambda v: {"accountIds": getattr(v, "participants", []) or []},
        ),
        OpSpec(
            id="remove_participants",
            label="Remove Request Participants",
            method="DELETE",
            path="/request/{issue_key}/participant",
            visible_fields=["issue_key", "participants"],
            body_builder=lambda v: {"accountIds": getattr(v, "participants", []) or []},
        ),
        OpSpec(
            id="get_approvals",
            label="List Approvals on Request",
            method="GET",
            path="/request/{issue_key}/approval",
            visible_fields=["issue_key"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="answer_approval",
            label="Answer Approval",
            method="POST",
            path="/request/{issue_key}/approval/{approval_id}",
            visible_fields=["issue_key", "approval_id", "approval_decision"],
            body_builder=lambda v: {
                "decision": (getattr(v, "approval_decision", None) or "approve").lower()
            },
        ),
        OpSpec(
            id="list_notifications",
            label="List Notification Preferences",
            method="GET",
            path="/request/{issue_key}/notification",
            visible_fields=["issue_key"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="subscribe_notification",
            label="Subscribe to Notifications",
            method="PUT",
            path="/request/{issue_key}/notification",
            visible_fields=["issue_key"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="unsubscribe_notification",
            label="Unsubscribe from Notifications",
            method="DELETE",
            path="/request/{issue_key}/notification",
            visible_fields=["issue_key"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_articles",
            label="List Knowledge Base Articles",
            method="GET",
            path="/knowledgebase/article",
            visible_fields=["query"],
            query_builder=lambda v: {
                k: val for k, val in {"query": getattr(v, "query", None) or None}.items() if val
            },
        ),
        OpSpec(
            id="list_asset_workspaces",
            label="List Assets Workspaces",
            method="GET",
            path="/assets/workspace",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_asset_object_schemas",
            label="List Asset Object Schemas",
            method="GET",
            path="/assets/objectschema/list",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_service_desk",
            label="Get Service Desk",
            method="GET",
            path="/servicedesk/{service_desk_id}",
            visible_fields=["service_desk_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_workflow_status",
            label="List Workflow Statuses (for SD)",
            method="GET",
            path="/servicedesk/{service_desk_id}/workflow",
            visible_fields=["service_desk_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="attach_temporary_files",
            label="Attach Temporary Files",
            method="POST",
            path="/servicedesk/{service_desk_id}/attachTemporaryFile",
            visible_fields=["service_desk_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="create_attachment",
            label="Create Attachment on Request",
            method="POST",
            path="/request/{issue_key}/attachment",
            visible_fields=["issue_key", "temporary_attachment_ids"],
            body_builder=lambda v: {
                "temporaryAttachmentIds": getattr(v, "temporary_attachment_ids", []) or []
            },
        ),
        OpSpec(
            id="list_feedback",
            label="List Feedback for Request",
            method="GET",
            path="/request/{issue_key}/feedback",
            visible_fields=["issue_key"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="post_feedback",
            label="Post Feedback for Request",
            method="POST",
            path="/request/{issue_key}/feedback",
            visible_fields=["issue_key", "rating", "comment_body"],
            body_builder=lambda v: {
                "rating": int(getattr(v, "rating", 5) or 5),
                "comment": {"body": getattr(v, "comment_body", None) or ""},
            },
        ),
        OpSpec(
            id="delete_feedback",
            label="Delete Feedback",
            method="DELETE",
            path="/request/{issue_key}/feedback",
            visible_fields=["issue_key"],
            query_builder=lambda v: {},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "id", "type": "string"},
    ],
    allow_error=True,
)
