"""Reddit action node — Reddit — subreddit browsing, submissions, comments.

REST at https://oauth.reddit.com. See sim-parity roadmap Phase 4.29.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import (
    FieldSpec,
    OpSpec,
    ProviderManifest,
    RemoteLookup,
)

MANIFEST = ProviderManifest(
    type="action.reddit",
    name="Reddit",
    category="integration",
    description="Reddit — subreddit browsing, submissions, comments.",
    icon_slug="reddit",
    color="#ffffff",
    base_url="https://oauth.reddit.com",
    credential_type="reddit_api_key",
    token_field=["api_key"],
    auth="bearer",
    fields=[
        FieldSpec(name="query", label="Query", type="string"),
        FieldSpec(
            name="max_results", label="Max Results", type="number", default=10, mode="advanced"
        ),
        FieldSpec(name="type", label="Type", type="string"),
        FieldSpec(name="video_id", label="Video ID", type="string"),
        FieldSpec(name="channel_id", label="Channel ID", type="string"),
        FieldSpec(name="playlist_id", label="Playlist ID", type="string"),
        FieldSpec(name="post_id", label="Post ID", type="string"),
        FieldSpec(name="title", label="Title", type="string"),
        FieldSpec(name="content", label="Content (HTML)", type="string"),
        FieldSpec(name="status", label="Status", type="string", default="draft"),
        FieldSpec(name="per_page", label="Per Page", type="number", default=10, mode="advanced"),
        FieldSpec(name="text", label="Text", type="string"),
        FieldSpec(name="tweet_id", label="Tweet ID", type="string"),
        FieldSpec(name="username", label="Username", type="string"),
        FieldSpec(
            name="subreddit",
            label="Subreddit",
            type="string",
            remote=RemoteLookup(provider="reddit", resource="subreddits"),
        ),
        FieldSpec(name="sort", label="Sort", type="string", default="hot"),
        FieldSpec(name="limit", label="Limit", type="number", default=10, mode="advanced"),
        FieldSpec(name="url", label="URL", type="string"),
        FieldSpec(name="kind", label="Kind (self|link)", type="string", default="self"),
        FieldSpec(name="article", label="Article ID", type="string"),
        FieldSpec(name="track_id", label="Track ID", type="string"),
        FieldSpec(name="artist_id", label="Artist ID", type="string"),
        FieldSpec(name="user_id", label="User ID", type="string"),
        FieldSpec(name="playlist_name", label="Playlist Name", type="string"),
        FieldSpec(name="playlist_description", label="Playlist Description", type="string"),
        FieldSpec(name="public", label="Public Playlist", type="boolean", default=False),
        FieldSpec(name="track_uris", label="Track URIs (JSON)", type="json", default=[]),
        FieldSpec(name="prompt_image", label="Prompt Image URL", type="string"),
        FieldSpec(name="prompt_text", label="Prompt Text", type="string"),
        FieldSpec(name="duration", label="Duration (sec)", type="number", default=5),
        FieldSpec(name="ratio", label="Aspect Ratio", type="string", default="1280:768"),
        FieldSpec(name="task_id", label="Task ID", type="string"),
        FieldSpec(name="input_text", label="Input Text", type="string"),
        FieldSpec(name="format", label="Format", type="string", default="presentation"),
        FieldSpec(name="num_cards", label="Number of Cards", type="number", default=10),
        FieldSpec(name="text_amount", label="Text Amount", type="string", default="detailed"),
        FieldSpec(name="generation_id", label="Generation ID", type="string"),
        FieldSpec(name="fullname", label="Fullname (t3_xxx or t1_xxx)", type="string"),
        FieldSpec(name="direction", label="Direction (1|0|-1)", type="number", default=0),
        FieldSpec(name="action_kind", label="Action (sub|unsub)", type="string", default="sub"),
        FieldSpec(
            name="time_filter",
            label="Time Filter (hour|day|week|month|year|all)",
            type="string",
            default="day",
        ),
        FieldSpec(name="subject", label="Subject", type="string"),
        FieldSpec(name="message", label="Message", type="string"),
        FieldSpec(name="query_text", label="Query Text", type="string"),
        FieldSpec(name="wiki_page", label="Wiki Page Name", type="string"),
    ],
    operations=[
        OpSpec(
            id="list_subreddit",
            label="List Subreddit Posts",
            method="GET",
            path="/r/{subreddit}/{sort}",
            visible_fields=["subreddit", "sort", "limit"],
            query_builder=lambda v: {"limit": int(getattr(v, "limit", 10) or 10)},
        ),
        OpSpec(
            id="submit",
            label="Submit Post",
            method="POST",
            path="/api/submit",
            visible_fields=["subreddit", "title", "url", "text", "kind"],
            body_builder=lambda v: {
                k: val
                for k, val in {
                    "sr": getattr(v, "subreddit", "") or "",
                    "title": getattr(v, "title", "") or "",
                    "url": getattr(v, "url", None) or None,
                    "text": getattr(v, "text", None) or None,
                    "kind": getattr(v, "kind", None) or "self",
                }.items()
                if val is not None
            },
        ),
        OpSpec(
            id="get_comments",
            label="Get Post Comments",
            method="GET",
            path="/comments/{article}",
            visible_fields=["article"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="search",
            label="Search Reddit",
            method="GET",
            path="/search",
            visible_fields=["query", "limit"],
            query_builder=lambda v: {
                "q": getattr(v, "query", "") or "",
                "limit": int(getattr(v, "limit", 10) or 10),
            },
        ),
        OpSpec(
            id="save",
            label="Save (Post/Comment)",
            method="POST",
            path="/api/save",
            visible_fields=["fullname"],
            body_builder=lambda v: {"id": getattr(v, "fullname", "") or ""},
        ),
        OpSpec(
            id="unsave",
            label="Unsave",
            method="POST",
            path="/api/unsave",
            visible_fields=["fullname"],
            body_builder=lambda v: {"id": getattr(v, "fullname", "") or ""},
        ),
        OpSpec(
            id="vote",
            label="Vote (Post/Comment)",
            method="POST",
            path="/api/vote",
            visible_fields=["fullname", "direction"],
            body_builder=lambda v: {
                "id": getattr(v, "fullname", "") or "",
                "dir": int(getattr(v, "direction", 0) or 0),
            },
        ),
        OpSpec(
            id="me",
            label="Get Current User",
            method="GET",
            path="/api/v1/me",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_user",
            label="Get User Info",
            method="GET",
            path="/user/{username}/about",
            visible_fields=["username"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_user_posts",
            label="List User Posts",
            method="GET",
            path="/user/{username}/submitted",
            visible_fields=["username", "limit"],
            query_builder=lambda v: {"limit": int(getattr(v, "limit", 10) or 10)},
        ),
        OpSpec(
            id="list_saved",
            label="List Saved (me)",
            method="GET",
            path="/user/{username}/saved",
            visible_fields=["username", "limit"],
            query_builder=lambda v: {"limit": int(getattr(v, "limit", 10) or 10)},
        ),
        OpSpec(
            id="subscribe",
            label="Subscribe / Unsubscribe",
            method="POST",
            path="/api/subscribe",
            visible_fields=["subreddit", "action_kind"],
            body_builder=lambda v: {
                "sr_name": getattr(v, "subreddit", "") or "",
                "action": getattr(v, "action_kind", None) or "sub",
            },
        ),
        OpSpec(
            id="get_subreddit_info",
            label="Get Subreddit Info",
            method="GET",
            path="/r/{subreddit}/about",
            visible_fields=["subreddit"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_hot",
            label="Get Hot Posts",
            method="GET",
            path="/r/{subreddit}/hot",
            visible_fields=["subreddit", "limit"],
            query_builder=lambda v: {"limit": int(getattr(v, "limit", 10) or 10)},
        ),
        OpSpec(
            id="get_new",
            label="Get New Posts",
            method="GET",
            path="/r/{subreddit}/new",
            visible_fields=["subreddit", "limit"],
            query_builder=lambda v: {"limit": int(getattr(v, "limit", 10) or 10)},
        ),
        OpSpec(
            id="get_top",
            label="Get Top Posts",
            method="GET",
            path="/r/{subreddit}/top",
            visible_fields=["subreddit", "limit", "time_filter"],
            query_builder=lambda v: {
                "limit": int(getattr(v, "limit", 10) or 10),
                "t": getattr(v, "time_filter", None) or "day",
            },
        ),
        OpSpec(
            id="comment",
            label="Post Comment",
            method="POST",
            path="/api/comment",
            visible_fields=["fullname", "text"],
            body_builder=lambda v: {
                "api_type": "json",
                "thing_id": getattr(v, "fullname", "") or "",
                "text": getattr(v, "text", "") or "",
            },
        ),
        OpSpec(
            id="delete_post",
            label="Delete Post/Comment",
            method="POST",
            path="/api/del",
            visible_fields=["fullname"],
            body_builder=lambda v: {"id": getattr(v, "fullname", "") or ""},
        ),
        OpSpec(
            id="edit_post",
            label="Edit Post/Comment",
            method="POST",
            path="/api/editusertext",
            visible_fields=["fullname", "text"],
            body_builder=lambda v: {
                "api_type": "json",
                "thing_id": getattr(v, "fullname", "") or "",
                "text": getattr(v, "text", "") or "",
            },
        ),
        OpSpec(
            id="get_inbox",
            label="Get Inbox",
            method="GET",
            path="/message/inbox",
            visible_fields=["limit"],
            query_builder=lambda v: {"limit": int(getattr(v, "limit", 10) or 10)},
        ),
        OpSpec(
            id="send_message",
            label="Send Private Message",
            method="POST",
            path="/api/compose",
            visible_fields=["username", "subject", "message"],
            body_builder=lambda v: {
                "api_type": "json",
                "to": getattr(v, "username", "") or "",
                "subject": getattr(v, "subject", "") or "",
                "text": getattr(v, "message", "") or "",
            },
        ),
        OpSpec(
            id="search_subreddits",
            label="Search Subreddits by Query",
            method="GET",
            path="/subreddits/search",
            visible_fields=["query_text", "limit"],
            query_builder=lambda v: {
                "q": getattr(v, "query_text", "") or "",
                "limit": int(getattr(v, "limit", 10) or 10),
            },
        ),
        OpSpec(
            id="get_trending_subreddits",
            label="Trending Subreddits",
            method="GET",
            path="/api/trending_subreddits",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_moderators",
            label="Get Subreddit Moderators",
            method="GET",
            path="/r/{subreddit}/about/moderators",
            visible_fields=["subreddit"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_wiki_page",
            label="Get Wiki Page",
            method="GET",
            path="/r/{subreddit}/wiki/{wiki_page}",
            visible_fields=["subreddit", "wiki_page"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_multi",
            label="List My Multireddits",
            method="GET",
            path="/api/multi/mine",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "id", "type": "string"},
    ],
    allow_error=True,
)
