"""LaunchDarkly action node — LaunchDarkly — feature flags + segments.

REST at https://app.launchdarkly.com/api/v2. See sim-parity roadmap Phase 4.22.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import (
    FieldSpec,
    OpSpec,
    ProviderManifest,
    RemoteLookup,
)

MANIFEST = ProviderManifest(
    type="action.launchdarkly",
    name="LaunchDarkly",
    category="integration",
    description="LaunchDarkly — feature flags + segments.",
    icon_slug="launchdarkly",
    color="#ffffff",
    base_url="https://app.launchdarkly.com/api/v2",
    credential_type="launchdarkly_api_key",
    token_field=["api_key"],
    auth="header_token",
    auth_header_name="Authorization",
    fields=[
        FieldSpec(name="query", label="GraphQL Query / Search Query", type="string"),
        FieldSpec(name="variables", label="Variables (JSON)", type="json"),
        FieldSpec(name="run_config", label="Run Config (JSON)", type="json"),
        FieldSpec(name="workspace_id", label="Workspace ID", type="string"),
        FieldSpec(name="name", label="Name", type="string"),
        FieldSpec(name="repository", label="Repository URL", type="string"),
        FieldSpec(
            name="project_key",
            label="Project",
            type="string",
            remote=RemoteLookup(provider="launchdarkly", resource="projects"),
        ),
        FieldSpec(
            name="flag_key",
            label="Feature Flag Key",
            type="string",
            remote=RemoteLookup(
                provider="launchdarkly",
                resource="flags",
                params={"project_key": "${project_key}"},
                depends_on=["project_key"],
            ),
        ),
        FieldSpec(
            name="environment_key",
            label="Environment Key",
            type="string",
            remote=RemoteLookup(
                provider="launchdarkly",
                resource="environments",
                params={"project_key": "${project_key}"},
                depends_on=["project_key"],
            ),
        ),
        FieldSpec(name="enabled", label="Enabled (true/false)", type="string"),
        FieldSpec(name="severity_id", label="Severity ID", type="string"),
        FieldSpec(name="severity", label="Severity (slug)", type="string"),
        FieldSpec(name="summary", label="Summary", type="string"),
        FieldSpec(name="visibility", label="Visibility", type="string", default="public"),
        FieldSpec(name="incident_id", label="Incident ID", type="string"),
        FieldSpec(name="title", label="Title", type="string"),
        FieldSpec(name="status", label="Status", type="string"),
        FieldSpec(name="page_size", label="Page Size", type="number", default=25, mode="advanced"),
        FieldSpec(name="ld_project_key", label="Project Key", type="string"),
        FieldSpec(name="ld_environment_key", label="Environment Key", type="string"),
        FieldSpec(name="ld_flag_key", label="Flag Key", type="string"),
        FieldSpec(name="ld_flag_body", label="Flag Body (JSON)", type="json", default={}),
        FieldSpec(name="ld_flag_state", label="Flag State (on|off)", type="string", default="on"),
        FieldSpec(name="segment_key", label="Segment Key", type="string"),
    ],
    operations=[
        OpSpec(
            id="list_flags",
            label="List Feature Flags",
            method="GET",
            path="/flags/{project_key}",
            visible_fields=["project_key"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_flag",
            label="Get Feature Flag",
            method="GET",
            path="/flags/{project_key}/{flag_key}",
            visible_fields=["project_key", "flag_key"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="toggle_flag",
            label="Toggle Flag (patch)",
            method="PATCH",
            path="/flags/{project_key}/{flag_key}",
            visible_fields=["project_key", "flag_key", "environment_key", "enabled"],
            body_builder=lambda v: [
                {
                    "op": "replace",
                    "path": f"/environments/{getattr(v, 'environment_key', '')}/on",
                    "value": (getattr(v, "enabled", None) or "false").lower() == "true",
                }
            ],
        ),
        OpSpec(
            id="list_projects",
            label="List Projects",
            method="GET",
            path="/projects",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_flag",
            label="Create Feature Flag",
            method="POST",
            path="/api/v2/flags/{ld_project_key}",
            visible_fields=["ld_project_key", "ld_flag_body"],
            body_builder=lambda v: getattr(v, "ld_flag_body", None) or {},
        ),
        OpSpec(
            id="update_flag",
            label="Update Feature Flag (patch)",
            method="PATCH",
            path="/api/v2/flags/{ld_project_key}/{ld_flag_key}",
            visible_fields=["ld_project_key", "ld_flag_key", "ld_flag_body"],
            body_builder=lambda v: getattr(v, "ld_flag_body", None) or {},
        ),
        OpSpec(
            id="delete_flag",
            label="Delete Flag",
            method="DELETE",
            path="/api/v2/flags/{ld_project_key}/{ld_flag_key}",
            visible_fields=["ld_project_key", "ld_flag_key"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_flag_status",
            label="Get Flag Status",
            method="GET",
            path="/api/v2/flag-statuses/{ld_project_key}/{ld_environment_key}/{ld_flag_key}",
            visible_fields=["ld_project_key", "ld_environment_key", "ld_flag_key"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_environments",
            label="List Environments",
            method="GET",
            path="/api/v2/projects/{ld_project_key}/environments",
            visible_fields=["ld_project_key"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_segments",
            label="List Segments",
            method="GET",
            path="/api/v2/segments/{ld_project_key}/{ld_environment_key}",
            visible_fields=["ld_project_key", "ld_environment_key"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_members",
            label="List Members",
            method="GET",
            path="/api/v2/members",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_audit_log",
            label="Get Audit Log",
            method="GET",
            path="/api/v2/auditlog",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "id", "type": "string"},
        {"label": "status", "type": "string"},
    ],
    allow_error=True,
)
