"""LinQ action node — LinQ — enterprise procurement + supplier data.

REST at https://api.linq.build/v1. See sim-parity roadmap Phase 4.32.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.linq",
    name="LinQ",
    category="integration",
    description="LinQ — enterprise procurement + supplier data.",
    icon_slug="linq",
    color="#1c1c1c",
    base_url="https://api.linq.build/v1",
    credential_type="linq_api_key",
    token_field=["api_key"],
    auth="bearer",
    fields=[
        FieldSpec(name="table", label="Table", type="string"),
        FieldSpec(name="record_id", label="Record ID", type="string"),
        FieldSpec(name="filter", label="Filter", type="string"),
        FieldSpec(name="data", label="Data (JSON)", type="json", default={}),
        FieldSpec(name="config_id", label="Sync Config ID", type="string"),
        FieldSpec(name="query_text", label="Query Text", type="string"),
        FieldSpec(name="destination_id", label="Destination ID", type="string"),
        FieldSpec(name="property_id", label="Property ID", type="string"),
        FieldSpec(name="email", label="Email", type="string"),
        FieldSpec(name="right", label="Right (delete|access|...)", type="string", default="delete"),
        FieldSpec(name="source", label="LaTeX Source", type="string"),
        FieldSpec(name="query", label="Query", type="string"),
        FieldSpec(name="depth", label="Depth (standard|deep)", type="string", default="standard"),
        FieldSpec(name="output_type", label="Output Type", type="string", default="searchResults"),
        FieldSpec(name="supplier_id", label="Supplier ID", type="string"),
        FieldSpec(name="path", label="Path", type="string"),
        FieldSpec(name="content", label="Content", type="string"),
        FieldSpec(name="message", label="Message", type="string"),
        FieldSpec(name="project_id", label="Project ID", type="string"),
        FieldSpec(name="file_url", label="File URL", type="string"),
        FieldSpec(name="json_schema", label="Schema (JSON)", type="json", default={}),
        FieldSpec(name="job_id", label="Job ID", type="string"),
        FieldSpec(name="company_id", label="Company ID", type="string"),
        FieldSpec(name="event_id", label="Event ID", type="string"),
        FieldSpec(name="remote", label="Remote (github|gitlab)", type="string", default="github"),
        FieldSpec(name="repository", label="Repository (owner/repo)", type="string"),
        FieldSpec(name="branch", label="Branch", type="string", default="main"),
        FieldSpec(name="repositories", label="Repositories (JSON)", type="json", default=[]),
        FieldSpec(name="guard_name", label="Guard Name", type="string"),
        FieldSpec(name="llm_output", label="LLM Output", type="string"),
        FieldSpec(name="host_ids", label="Host IDs (JSON)", type="json", default=[]),
        FieldSpec(name="limit", label="Limit", type="number", default=50, mode="advanced"),
        FieldSpec(name="chat_id", label="Chat ID", type="string"),
        FieldSpec(name="chat_name", label="Chat Name", type="string"),
        FieldSpec(name="message_id", label="Message ID", type="string"),
        FieldSpec(name="message_text", label="Message Text", type="string"),
        FieldSpec(name="participants", label="Participants (JSON array)", type="json", default=[]),
        FieldSpec(name="participant", label="Participant ID", type="string"),
        FieldSpec(name="media_url", label="Media URL", type="string"),
        FieldSpec(name="contact_card_id", label="Contact Card ID", type="string"),
        FieldSpec(name="emoji", label="Emoji", type="string"),
        FieldSpec(name="attachment_id", label="Attachment ID", type="string"),
        FieldSpec(name="phone_number", label="Phone Number", type="string"),
        FieldSpec(
            name="contact_card_body", label="Contact Card Body (JSON)", type="json", default={}
        ),
    ],
    operations=[
        OpSpec(
            id="search_suppliers",
            label="Search Suppliers",
            method="GET",
            path="/suppliers",
            visible_fields=["query"],
            query_builder=lambda v: {"q": getattr(v, "query", "") or ""},
        ),
        OpSpec(
            id="get_supplier",
            label="Get Supplier",
            method="GET",
            path="/suppliers/{supplier_id}",
            visible_fields=["supplier_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="send_message",
            label="Send Message",
            method="POST",
            path="/messages",
            visible_fields=["chat_id", "message_text"],
            body_builder=lambda v: {
                "chat_id": getattr(v, "chat_id", "") or "",
                "text": getattr(v, "message_text", "") or "",
            },
        ),
        OpSpec(
            id="create_chat",
            label="Create Chat",
            method="POST",
            path="/chats",
            visible_fields=["participants"],
            body_builder=lambda v: {"participants": getattr(v, "participants", []) or []},
        ),
        OpSpec(
            id="list_chats",
            label="List Chats",
            method="GET",
            path="/chats",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_chat",
            label="Get Chat",
            method="GET",
            path="/chats/{chat_id}",
            visible_fields=["chat_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="update_chat",
            label="Update Chat",
            method="PATCH",
            path="/chats/{chat_id}",
            visible_fields=["chat_id", "chat_name"],
            body_builder=lambda v: {"name": getattr(v, "chat_name", "") or ""},
        ),
        OpSpec(
            id="mark_chat_read",
            label="Mark Chat Read",
            method="POST",
            path="/chats/{chat_id}/read",
            visible_fields=["chat_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="leave_chat",
            label="Leave Chat",
            method="POST",
            path="/chats/{chat_id}/leave",
            visible_fields=["chat_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="add_participant",
            label="Add Participant",
            method="POST",
            path="/chats/{chat_id}/participants",
            visible_fields=["chat_id", "participant"],
            body_builder=lambda v: {"participant": getattr(v, "participant", "") or ""},
        ),
        OpSpec(
            id="remove_participant",
            label="Remove Participant",
            method="DELETE",
            path="/chats/{chat_id}/participants/{participant}",
            visible_fields=["chat_id", "participant"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="start_typing",
            label="Start Typing Indicator",
            method="POST",
            path="/chats/{chat_id}/typing/start",
            visible_fields=["chat_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="stop_typing",
            label="Stop Typing Indicator",
            method="POST",
            path="/chats/{chat_id}/typing/stop",
            visible_fields=["chat_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="send_voice_memo",
            label="Send Voice Memo",
            method="POST",
            path="/messages/voice",
            visible_fields=["chat_id", "media_url"],
            body_builder=lambda v: {
                "chat_id": getattr(v, "chat_id", "") or "",
                "audio_url": getattr(v, "media_url", "") or "",
            },
        ),
        OpSpec(
            id="share_contact_card",
            label="Share Contact Card",
            method="POST",
            path="/messages/contact",
            visible_fields=["chat_id", "contact_card_id"],
            body_builder=lambda v: {
                "chat_id": getattr(v, "chat_id", "") or "",
                "contact_card_id": getattr(v, "contact_card_id", "") or "",
            },
        ),
        OpSpec(
            id="list_messages",
            label="List Messages in Chat",
            method="GET",
            path="/chats/{chat_id}/messages",
            visible_fields=["chat_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_message",
            label="Get Message",
            method="GET",
            path="/messages/{message_id}",
            visible_fields=["message_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="edit_message",
            label="Edit Message",
            method="PATCH",
            path="/messages/{message_id}",
            visible_fields=["message_id", "message_text"],
            body_builder=lambda v: {"text": getattr(v, "message_text", "") or ""},
        ),
        OpSpec(
            id="delete_message",
            label="Delete Message",
            method="DELETE",
            path="/messages/{message_id}",
            visible_fields=["message_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="react_to_message",
            label="React to Message",
            method="POST",
            path="/messages/{message_id}/reactions",
            visible_fields=["message_id", "emoji"],
            body_builder=lambda v: {"emoji": getattr(v, "emoji", "") or ""},
        ),
        OpSpec(
            id="create_attachment",
            label="Create Attachment",
            method="POST",
            path="/attachments",
            visible_fields=["media_url"],
            body_builder=lambda v: {"url": getattr(v, "media_url", "") or ""},
        ),
        OpSpec(
            id="get_attachment",
            label="Get Attachment",
            method="GET",
            path="/attachments/{attachment_id}",
            visible_fields=["attachment_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="delete_attachment",
            label="Delete Attachment",
            method="DELETE",
            path="/attachments/{attachment_id}",
            visible_fields=["attachment_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_phone_numbers",
            label="List Phone Numbers",
            method="GET",
            path="/phone-numbers",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="check_imessage",
            label="Check iMessage Support",
            method="GET",
            path="/imessage/check",
            visible_fields=["phone_number"],
            query_builder=lambda v: {"phone_number": getattr(v, "phone_number", "") or ""},
        ),
        OpSpec(
            id="check_rcs",
            label="Check RCS Support",
            method="GET",
            path="/rcs/check",
            visible_fields=["phone_number"],
            query_builder=lambda v: {"phone_number": getattr(v, "phone_number", "") or ""},
        ),
        OpSpec(
            id="get_contact_card",
            label="Get Contact Card",
            method="GET",
            path="/contact-cards/{contact_card_id}",
            visible_fields=["contact_card_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_contact_card",
            label="Create Contact Card",
            method="POST",
            path="/contact-cards",
            visible_fields=["contact_card_body"],
            body_builder=lambda v: getattr(v, "contact_card_body", None) or {},
        ),
        OpSpec(
            id="update_contact_card",
            label="Update Contact Card",
            method="PATCH",
            path="/contact-cards/{contact_card_id}",
            visible_fields=["contact_card_id", "contact_card_body"],
            body_builder=lambda v: getattr(v, "contact_card_body", None) or {},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "id", "type": "string"},
    ],
    allow_error=True,
)
