"""PostHog action node — manifest form.

PostHog has two API surfaces:

  - **Capture API** at `https://us.i.posthog.com` for event ingestion.
    Uses `api_key` *in the body* (project key, not personal). The
    user-facing prop is `api_key` but it lives at the project level,
    not the credential token. We pass the credential's personal token
    via Bearer for queries; capture ops use the project key from the
    request body.
  - **Personal/Project API** at `https://us.posthog.com/api/projects/{project_id}/`
    for everything else — feature flags, queries, persons, cohorts.
    Bearer auth with a personal API key.

This manifest covers the API surface (queries, flags, persons). Event
capture lives in a separate `posthog-capture` integration if we need it
later — different auth model, different base URL.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import (
    FieldSpec,
    OpSpec,
    ProviderManifest,
)

MANIFEST = ProviderManifest(
    type="action.posthog",
    name="PostHog",
    category="integration",
    description="Query PostHog events, manage feature flags + persons.",
    icon_slug="posthog",
    color="#ffffff",
    base_url="https://us.posthog.com/api",
    credential_type="posthog_api_key",
    token_field=["api_key"],
    auth="bearer",
    fields=[
        FieldSpec(
            name="project_id", label="Project ID", type="string", required=True, placeholder="12345"
        ),
        FieldSpec(name="flag_id", label="Feature Flag ID", type="string"),
        FieldSpec(name="flag_key", label="Feature Flag Key", type="string"),
        FieldSpec(name="active", label="Active", type="boolean", mode="advanced"),
        FieldSpec(name="filters", label="Filters (JSON)", type="json", mode="advanced"),
        FieldSpec(name="person_id", label="Person ID", type="string"),
        FieldSpec(name="distinct_id", label="Distinct ID", type="string"),
        FieldSpec(
            name="query",
            label="HogQL Query",
            type="string",
            placeholder="SELECT count() FROM events",
        ),
        FieldSpec(name="limit", label="Limit", type="number", default=100, mode="advanced"),
        FieldSpec(name="batch", label="Batch (JSON array)", type="json", default=[]),
        FieldSpec(name="posthog_query", label="HogQL Query (JSON)", type="json", default={}),
        FieldSpec(name="insight_id", label="Insight ID", type="string"),
        FieldSpec(name="insight_body", label="Insight Body (JSON)", type="json", default={}),
        FieldSpec(name="dashboard_id", label="Dashboard ID", type="string"),
        FieldSpec(name="cohort_id", label="Cohort ID", type="string"),
        FieldSpec(name="content", label="Content", type="string"),
        FieldSpec(name="date_marker", label="Date Marker (ISO)", type="string"),
        FieldSpec(name="flag_name", label="Feature Flag Name", type="string"),
        FieldSpec(name="action_id", label="Action ID", type="string"),
        FieldSpec(name="action_body", label="Action Body (JSON)", type="json", default={}),
        FieldSpec(name="cohort_body", label="Cohort Body (JSON)", type="json", default={}),
        FieldSpec(name="dashboard_body", label="Dashboard Body (JSON)", type="json", default={}),
        FieldSpec(name="annotation_id", label="Annotation ID", type="string"),
        FieldSpec(name="survey_id", label="Survey ID", type="string"),
        FieldSpec(name="survey_body", label="Survey Body (JSON)", type="json", default={}),
        FieldSpec(name="recording_id", label="Session Recording ID", type="string"),
        FieldSpec(name="event_def_id", label="Event Definition ID", type="string"),
        FieldSpec(name="property_def_id", label="Property Definition ID", type="string"),
    ],
    operations=[
        OpSpec(
            id="run_query",
            label="Run HogQL Query",
            method="POST",
            path="/projects/{project_id}/query/",
            visible_fields=["project_id", "query"],
            body_template={"query": {"kind": "HogQLQuery", "query": "{query}"}},
        ),
        OpSpec(
            id="list_feature_flags",
            label="List Feature Flags",
            method="GET",
            path="/projects/{project_id}/feature_flags/",
            visible_fields=["project_id", "limit"],
            query_fields=["limit"],
        ),
        OpSpec(
            id="get_feature_flag",
            label="Get Feature Flag",
            method="GET",
            path="/projects/{project_id}/feature_flags/{flag_id}/",
            visible_fields=["project_id", "flag_id"],
        ),
        OpSpec(
            id="create_feature_flag",
            label="Create Feature Flag",
            method="POST",
            path="/projects/{project_id}/feature_flags/",
            visible_fields=["project_id", "flag_key", "active", "filters"],
            body_builder=lambda props: {
                k: v
                for k, v in {
                    "key": getattr(props, "flag_key", None),
                    "name": getattr(props, "flag_key", None),
                    "active": getattr(props, "active", None),
                    "filters": getattr(props, "filters", None),
                }.items()
                if v is not None
            },
        ),
        OpSpec(
            id="update_feature_flag",
            label="Update Feature Flag",
            method="PATCH",
            path="/projects/{project_id}/feature_flags/{flag_id}/",
            visible_fields=["project_id", "flag_id", "active", "filters"],
            body_builder=lambda props: {
                k: v
                for k, v in {
                    "active": getattr(props, "active", None),
                    "filters": getattr(props, "filters", None),
                }.items()
                if v is not None
            },
        ),
        OpSpec(
            id="list_persons",
            label="List Persons",
            method="GET",
            path="/projects/{project_id}/persons/",
            visible_fields=["project_id", "distinct_id", "limit"],
            query_fields=["distinct_id", "limit"],
        ),
        OpSpec(
            id="get_person",
            label="Get Person",
            method="GET",
            path="/projects/{project_id}/persons/{person_id}/",
            visible_fields=["project_id", "person_id"],
        ),
        OpSpec(
            id="batch_events",
            label="Batch Capture Events",
            method="POST",
            path="/i/v0/batch",
            visible_fields=["batch"],
            body_builder=lambda v: {"batch": getattr(v, "batch", []) or []},
        ),
        OpSpec(
            id="delete_person",
            label="Delete Person",
            method="DELETE",
            path="/api/projects/{project_id}/persons/{person_id}",
            visible_fields=["project_id", "person_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_insights",
            label="List Insights",
            method="GET",
            path="/api/projects/{project_id}/insights",
            visible_fields=["project_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_insight",
            label="Get Insight",
            method="GET",
            path="/api/projects/{project_id}/insights/{insight_id}",
            visible_fields=["project_id", "insight_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_insight",
            label="Create Insight",
            method="POST",
            path="/api/projects/{project_id}/insights",
            visible_fields=["project_id", "insight_body"],
            body_builder=lambda v: getattr(v, "insight_body", None) or {},
        ),
        OpSpec(
            id="list_dashboards",
            label="List Dashboards",
            method="GET",
            path="/api/projects/{project_id}/dashboards",
            visible_fields=["project_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_dashboard",
            label="Get Dashboard",
            method="GET",
            path="/api/projects/{project_id}/dashboards/{dashboard_id}",
            visible_fields=["project_id", "dashboard_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_actions",
            label="List Actions",
            method="GET",
            path="/api/projects/{project_id}/actions",
            visible_fields=["project_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_cohorts",
            label="List Cohorts",
            method="GET",
            path="/api/projects/{project_id}/cohorts",
            visible_fields=["project_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_cohort",
            label="Get Cohort",
            method="GET",
            path="/api/projects/{project_id}/cohorts/{cohort_id}",
            visible_fields=["project_id", "cohort_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_annotations",
            label="List Annotations",
            method="GET",
            path="/api/projects/{project_id}/annotations",
            visible_fields=["project_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_annotation",
            label="Create Annotation",
            method="POST",
            path="/api/projects/{project_id}/annotations",
            visible_fields=["project_id", "content", "date_marker"],
            body_builder=lambda v: {
                "content": getattr(v, "content", "") or "",
                "date_marker": getattr(v, "date_marker", "") or "",
            },
        ),
        OpSpec(
            id="delete_feature_flag",
            label="Delete Feature Flag",
            method="DELETE",
            path="/api/projects/{project_id}/feature_flags/{flag_id}",
            visible_fields=["project_id", "flag_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_experiments",
            label="List Experiments",
            method="GET",
            path="/api/projects/{project_id}/experiments",
            visible_fields=["project_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_surveys",
            label="List Surveys",
            method="GET",
            path="/api/projects/{project_id}/surveys",
            visible_fields=["project_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_session_recordings",
            label="List Session Recordings",
            method="GET",
            path="/api/projects/{project_id}/session_recordings",
            visible_fields=["project_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_event_definitions",
            label="List Event Definitions",
            method="GET",
            path="/api/projects/{project_id}/event_definitions",
            visible_fields=["project_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_property_definitions",
            label="List Property Definitions",
            method="GET",
            path="/api/projects/{project_id}/property_definitions",
            visible_fields=["project_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="update_insight",
            label="Update Insight",
            method="PATCH",
            path="/api/projects/{project_id}/insights/{insight_id}",
            visible_fields=["project_id", "insight_id", "insight_body"],
            body_builder=lambda v: getattr(v, "insight_body", None) or {},
        ),
        OpSpec(
            id="delete_insight",
            label="Delete Insight",
            method="DELETE",
            path="/api/projects/{project_id}/insights/{insight_id}",
            visible_fields=["project_id", "insight_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="update_dashboard",
            label="Update Dashboard",
            method="PATCH",
            path="/api/projects/{project_id}/dashboards/{dashboard_id}",
            visible_fields=["project_id", "dashboard_id", "dashboard_body"],
            body_builder=lambda v: getattr(v, "dashboard_body", None) or {},
        ),
        OpSpec(
            id="create_dashboard",
            label="Create Dashboard",
            method="POST",
            path="/api/projects/{project_id}/dashboards",
            visible_fields=["project_id", "dashboard_body"],
            body_builder=lambda v: getattr(v, "dashboard_body", None) or {},
        ),
        OpSpec(
            id="delete_dashboard",
            label="Delete Dashboard",
            method="DELETE",
            path="/api/projects/{project_id}/dashboards/{dashboard_id}",
            visible_fields=["project_id", "dashboard_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_action",
            label="Get Action",
            method="GET",
            path="/api/projects/{project_id}/actions/{action_id}",
            visible_fields=["project_id", "action_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_action",
            label="Create Action",
            method="POST",
            path="/api/projects/{project_id}/actions",
            visible_fields=["project_id", "action_body"],
            body_builder=lambda v: getattr(v, "action_body", None) or {},
        ),
        OpSpec(
            id="update_cohort",
            label="Update Cohort",
            method="PATCH",
            path="/api/projects/{project_id}/cohorts/{cohort_id}",
            visible_fields=["project_id", "cohort_id", "cohort_body"],
            body_builder=lambda v: getattr(v, "cohort_body", None) or {},
        ),
        OpSpec(
            id="delete_cohort",
            label="Delete Cohort",
            method="DELETE",
            path="/api/projects/{project_id}/cohorts/{cohort_id}",
            visible_fields=["project_id", "cohort_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_annotation",
            label="Get Annotation",
            method="GET",
            path="/api/projects/{project_id}/annotations/{annotation_id}",
            visible_fields=["project_id", "annotation_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="delete_annotation",
            label="Delete Annotation",
            method="DELETE",
            path="/api/projects/{project_id}/annotations/{annotation_id}",
            visible_fields=["project_id", "annotation_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_survey",
            label="Get Survey",
            method="GET",
            path="/api/projects/{project_id}/surveys/{survey_id}",
            visible_fields=["project_id", "survey_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_survey",
            label="Create Survey",
            method="POST",
            path="/api/projects/{project_id}/surveys",
            visible_fields=["project_id", "survey_body"],
            body_builder=lambda v: getattr(v, "survey_body", None) or {},
        ),
        OpSpec(
            id="update_survey",
            label="Update Survey",
            method="PATCH",
            path="/api/projects/{project_id}/surveys/{survey_id}",
            visible_fields=["project_id", "survey_id", "survey_body"],
            body_builder=lambda v: getattr(v, "survey_body", None) or {},
        ),
        OpSpec(
            id="get_session_recording",
            label="Get Session Recording",
            method="GET",
            path="/api/projects/{project_id}/session_recordings/{recording_id}",
            visible_fields=["project_id", "recording_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_recording_playlists",
            label="List Session Recording Playlists",
            method="GET",
            path="/api/projects/{project_id}/session_recording_playlists",
            visible_fields=["project_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_event_definition",
            label="Get Event Definition",
            method="GET",
            path="/api/projects/{project_id}/event_definitions/{event_def_id}",
            visible_fields=["project_id", "event_def_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_property_definition",
            label="Get Property Definition",
            method="GET",
            path="/api/projects/{project_id}/property_definitions/{property_def_id}",
            visible_fields=["project_id", "property_def_id"],
            query_builder=lambda v: {},
        ),
    ],
    outputs_schema=[
        {"label": "id", "type": "string"},
        {"label": "key", "type": "string"},
        {"label": "active", "type": "boolean"},
        {"label": "results", "type": "array"},
        {"label": "count", "type": "number"},
        {"label": "next", "type": "string"},
    ],
    allow_error=True,
)
