"""SportMonks action node — SportMonks — football (soccer) live scores, fixtures, leagues.

REST at https://api.sportmonks.com/v3/football. See sim-parity roadmap Phase 4.30.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.sportmonks",
    name="SportMonks",
    category="integration",
    description="SportMonks — football (soccer) live scores, fixtures, leagues.",
    icon_slug="sportmonks",
    color="#ffffff",
    base_url="https://api.sportmonks.com/v3/football",
    credential_type="sportmonks_api_key",
    token_field=["api_key"],
    auth="query_token",
    auth_query_param="api_token",
    fields=[
        FieldSpec(name="coach_id", label="Coach Id", type="string"),
        FieldSpec(name="country_id", label="Country Id", type="string"),
        FieldSpec(name="date", label="Date", type="string"),
        FieldSpec(name="date_from", label="Date From", type="string"),
        FieldSpec(name="date_to", label="Date To", type="string"),
        FieldSpec(name="fixture_id", label="Fixture Id", type="string"),
        FieldSpec(name="fixtures_ids", label="Fixtures Ids", type="string"),
        FieldSpec(name="league_id", label="League Id", type="string"),
        FieldSpec(name="market_id", label="Market Id", type="string"),
        FieldSpec(name="player_id", label="Player Id", type="string"),
        FieldSpec(
            name="prematch_news_upcoming_id", label="Prematch News Upcoming Id", type="string"
        ),
        FieldSpec(name="referee_id", label="Referee Id", type="string"),
        FieldSpec(name="round_id", label="Round Id", type="string"),
        FieldSpec(name="search_query", label="Search Query", type="string"),
        FieldSpec(name="season_and_team_id", label="Season And Team Id", type="string"),
        FieldSpec(name="season_id", label="Season Id", type="string"),
        FieldSpec(name="stage_id", label="Stage Id", type="string"),
        FieldSpec(name="state_id", label="State Id", type="string"),
        FieldSpec(name="team1_id", label="Team1 Id", type="string"),
        FieldSpec(name="team2_id", label="Team2 Id", type="string"),
        FieldSpec(name="team_id", label="Team Id", type="string"),
        FieldSpec(name="team_squad_id", label="Team Squad Id", type="string"),
        FieldSpec(name="totw_id", label="Totw Id", type="string"),
        FieldSpec(name="transfer_id", label="Transfer Id", type="string"),
        FieldSpec(name="transfer_rumour_id", label="Transfer Rumour Id", type="string"),
        FieldSpec(name="tv_station_id", label="Tv Station Id", type="string"),
        FieldSpec(name="venue_id", label="Venue Id", type="string"),
        FieldSpec(name="page", label="Page", type="number", default=1, mode="advanced"),
        FieldSpec(name="per_page", label="Per Page", type="number", default=25, mode="advanced"),
        FieldSpec(
            name="include",
            label="Include (comma-separated relations)",
            type="string",
            mode="advanced",
        ),
    ],
    operations=[
        OpSpec(
            id="expected_by_player",
            label="Football Expected By Player",
            method="GET",
            path="/expected/lineups/players/{player_id}",
            visible_fields=["player_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="expected_by_team",
            label="Football Expected By Team",
            method="GET",
            path="/expected/lineups/teams/{team_id}",
            visible_fields=["team_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_all_commentaries",
            label="Football Get All Commentaries",
            method="GET",
            path="/commentaries",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_all_fixtures",
            label="Football Get All Fixtures",
            method="GET",
            path="/fixtures",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_all_players",
            label="Football Get All Players",
            method="GET",
            path="/players",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_all_rivals",
            label="Football Get All Rivals",
            method="GET",
            path="/rivals",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_all_teams",
            label="Football Get All Teams",
            method="GET",
            path="/teams",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_all_transfer_rumours",
            label="Football Get All Transfer Rumours",
            method="GET",
            path="/transfer_rumours",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_all_transfers",
            label="Football Get All Transfers",
            method="GET",
            path="/transfers",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_brackets_by_season",
            label="Football Get Brackets By Season",
            method="GET",
            path="/brackets/season/{season_id}",
            visible_fields=["season_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_coach",
            label="Football Get Coach",
            method="GET",
            path="/coach/{coach_id}",
            visible_fields=["coach_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_coaches",
            label="Football Get Coaches",
            method="GET",
            path="/coaches",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_coaches_by_country",
            label="Football Get Coaches By Country",
            method="GET",
            path="/coaches/country/{country_id}",
            visible_fields=["country_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_commentaries_by_fixture",
            label="Football Get Commentaries By Fixture",
            method="GET",
            path="/commentaries/fixture/{fixture_id}",
            visible_fields=["fixture_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_current_leagues_by_team",
            label="Football Get Current Leagues By Team",
            method="GET",
            path="/leagues/current/teams/{team_id}",
            visible_fields=["team_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_expected_lineups_by_player",
            label="Football Get Expected Lineups By Player",
            method="GET",
            path="/expected/lineups/players/{player_id}",
            visible_fields=["player_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_expected_lineups_by_team",
            label="Football Get Expected Lineups By Team",
            method="GET",
            path="/expected/lineups/teams/{team_id}",
            visible_fields=["team_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_extended_team_squad",
            label="Football Get Extended Team Squad",
            method="GET",
            path="/squads/teams/{team_id}/extended",
            visible_fields=["team_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_fixture",
            label="Football Get Fixture",
            method="GET",
            path="/fixture/{fixture_id}",
            visible_fields=["fixture_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_fixtures_by_date",
            label="Football Get Fixtures By Date",
            method="GET",
            path="/fixtures/date/{date}",
            visible_fields=["date"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_fixtures_by_date_range",
            label="Football Get Fixtures By Date Range",
            method="GET",
            path="/fixtures/between/{date_from}/{date_to}",
            visible_fields=["date_from", "date_to"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_fixtures_by_date_range_for_team",
            label="Football Get Fixtures By Date Range For Team",
            method="GET",
            path="/fixtures/between/{date_from}/{date_to}",
            visible_fields=["date_from", "date_to"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_fixtures_by_ids",
            label="Football Get Fixtures By Ids",
            method="GET",
            path="/fixtures/multi/{fixtures_ids}",
            visible_fields=["fixtures_ids"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_grouped_standings_by_round",
            label="Football Get Grouped Standings By Round",
            method="GET",
            path="/grouped_standings/round/{round_id}",
            visible_fields=["round_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_head_to_head",
            label="Football Get Head To Head",
            method="GET",
            path="/fixtures/head-to-head/{team1_id}/{team2_id}",
            visible_fields=["team1_id", "team2_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_inplay_livescores",
            label="Football Get Inplay Livescores",
            method="GET",
            path="/livescores/inplay",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_latest_coaches",
            label="Football Get Latest Coaches",
            method="GET",
            path="/coaches/latest",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_latest_fixtures",
            label="Football Get Latest Fixtures",
            method="GET",
            path="/fixtures/latest",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_latest_livescores",
            label="Football Get Latest Livescores",
            method="GET",
            path="/livescores/latest",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_latest_players",
            label="Football Get Latest Players",
            method="GET",
            path="/players/latest",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_latest_totw",
            label="Football Get Latest Totw",
            method="GET",
            path="/totw/latest",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_latest_transfers",
            label="Football Get Latest Transfers",
            method="GET",
            path="/transfers/latest",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_league",
            label="Football Get League",
            method="GET",
            path="/league/{league_id}",
            visible_fields=["league_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_leagues",
            label="Football Get Leagues",
            method="GET",
            path="/leagues",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_leagues_by_country",
            label="Football Get Leagues By Country",
            method="GET",
            path="/leagues/country/{country_id}",
            visible_fields=["country_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_leagues_by_date",
            label="Football Get Leagues By Date",
            method="GET",
            path="/leagues/date/{date}",
            visible_fields=["date"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_leagues_by_team",
            label="Football Get Leagues By Team",
            method="GET",
            path="/leagues/team/{team_id}",
            visible_fields=["team_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_live_leagues",
            label="Football Get Live Leagues",
            method="GET",
            path="/leagues/live",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_live_probabilities",
            label="Football Get Live Probabilities",
            method="GET",
            path="/predictions/probabilities/live",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_live_probabilities_by_fixture",
            label="Football Get Live Probabilities By Fixture",
            method="GET",
            path="/live_probabilities/fixture/{fixture_id}",
            visible_fields=["fixture_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_live_standings_by_league",
            label="Football Get Live Standings By League",
            method="GET",
            path="/live_standings/league/{league_id}",
            visible_fields=["league_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_livescores",
            label="Football Get Livescores",
            method="GET",
            path="/livescores",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_match_facts",
            label="Football Get Match Facts",
            method="GET",
            path="/match_facts",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_match_facts_by_date_range",
            label="Football Get Match Facts By Date Range",
            method="GET",
            path="/match_facts/between/{date_from}/{date_to}",
            visible_fields=["date_from", "date_to"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_match_facts_by_fixture",
            label="Football Get Match Facts By Fixture",
            method="GET",
            path="/match_facts/fixture/{fixture_id}",
            visible_fields=["fixture_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_match_facts_by_league",
            label="Football Get Match Facts By League",
            method="GET",
            path="/match_facts/league/{league_id}",
            visible_fields=["league_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_past_fixtures_by_tv_station",
            label="Football Get Past Fixtures By Tv Station",
            method="GET",
            path="/past_fixtures/tv_station/{tv_station_id}",
            visible_fields=["tv_station_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_player",
            label="Football Get Player",
            method="GET",
            path="/player/{player_id}",
            visible_fields=["player_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_players_by_country",
            label="Football Get Players By Country",
            method="GET",
            path="/players/country/{country_id}",
            visible_fields=["country_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_postmatch_news",
            label="Football Get Postmatch News",
            method="GET",
            path="/postmatch_news",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_postmatch_news_by_season",
            label="Football Get Postmatch News By Season",
            method="GET",
            path="/postmatch_news/season/{season_id}",
            visible_fields=["season_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_predictability_by_league",
            label="Football Get Predictability By League",
            method="GET",
            path="/predictability/league/{league_id}",
            visible_fields=["league_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_prematch_news",
            label="Football Get Prematch News",
            method="GET",
            path="/prematch_news",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_prematch_news_by_season",
            label="Football Get Prematch News By Season",
            method="GET",
            path="/prematch_news/season/{season_id}",
            visible_fields=["season_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_prematch_news_upcoming",
            label="Football Get Prematch News Upcoming",
            method="GET",
            path="/prematch_news_upcoming/{prematch_news_upcoming_id}",
            visible_fields=["prematch_news_upcoming_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_probabilities",
            label="Football Get Probabilities",
            method="GET",
            path="/probabilities",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_probabilities_by_fixture",
            label="Football Get Probabilities By Fixture",
            method="GET",
            path="/probabilities/fixture/{fixture_id}",
            visible_fields=["fixture_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_referee",
            label="Football Get Referee",
            method="GET",
            path="/referee/{referee_id}",
            visible_fields=["referee_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_referees",
            label="Football Get Referees",
            method="GET",
            path="/referees",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_referees_by_country",
            label="Football Get Referees By Country",
            method="GET",
            path="/referees/country/{country_id}",
            visible_fields=["country_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_referees_by_season",
            label="Football Get Referees By Season",
            method="GET",
            path="/referees/season/{season_id}",
            visible_fields=["season_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_rivals_by_team",
            label="Football Get Rivals By Team",
            method="GET",
            path="/rivals/team/{team_id}",
            visible_fields=["team_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_round",
            label="Football Get Round",
            method="GET",
            path="/round/{round_id}",
            visible_fields=["round_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_round_statistics",
            label="Football Get Round Statistics",
            method="GET",
            path="/round_statistics",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_rounds",
            label="Football Get Rounds",
            method="GET",
            path="/rounds",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_rounds_by_season",
            label="Football Get Rounds By Season",
            method="GET",
            path="/rounds/season/{season_id}",
            visible_fields=["season_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_schedules_by_season",
            label="Football Get Schedules By Season",
            method="GET",
            path="/schedules/season/{season_id}",
            visible_fields=["season_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_schedules_by_season_and_team",
            label="Football Get Schedules By Season And Team",
            method="GET",
            path="/schedules/season_and_team/{season_and_team_id}",
            visible_fields=["season_and_team_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_schedules_by_team",
            label="Football Get Schedules By Team",
            method="GET",
            path="/schedules/team/{team_id}",
            visible_fields=["team_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_season",
            label="Football Get Season",
            method="GET",
            path="/season/{season_id}",
            visible_fields=["season_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_seasons",
            label="Football Get Seasons",
            method="GET",
            path="/seasons",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_seasons_by_team",
            label="Football Get Seasons By Team",
            method="GET",
            path="/seasons/team/{team_id}",
            visible_fields=["team_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_stage",
            label="Football Get Stage",
            method="GET",
            path="/stage/{stage_id}",
            visible_fields=["stage_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_stage_statistics",
            label="Football Get Stage Statistics",
            method="GET",
            path="/stage_statistics",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_stages",
            label="Football Get Stages",
            method="GET",
            path="/stages",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_stages_by_season",
            label="Football Get Stages By Season",
            method="GET",
            path="/stages/season/{season_id}",
            visible_fields=["season_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_standing_corrections_by_season",
            label="Football Get Standing Corrections By Season",
            method="GET",
            path="/standing_corrections/season/{season_id}",
            visible_fields=["season_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_standings",
            label="Football Get Standings",
            method="GET",
            path="/standings",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_standings_by_round",
            label="Football Get Standings By Round",
            method="GET",
            path="/standings/round/{round_id}",
            visible_fields=["round_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_standings_by_season",
            label="Football Get Standings By Season",
            method="GET",
            path="/standings/season/{season_id}",
            visible_fields=["season_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_state",
            label="Football Get State",
            method="GET",
            path="/state/{state_id}",
            visible_fields=["state_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_states",
            label="Football Get States",
            method="GET",
            path="/states",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_team",
            label="Football Get Team",
            method="GET",
            path="/team/{team_id}",
            visible_fields=["team_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_team_rankings",
            label="Football Get Team Rankings",
            method="GET",
            path="/team_rankings",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_team_rankings_by_date",
            label="Football Get Team Rankings By Date",
            method="GET",
            path="/team_rankings/date/{date}",
            visible_fields=["date"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_team_rankings_by_team",
            label="Football Get Team Rankings By Team",
            method="GET",
            path="/team_rankings/team/{team_id}",
            visible_fields=["team_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_team_squad",
            label="Football Get Team Squad",
            method="GET",
            path="/team_squad/{team_squad_id}",
            visible_fields=["team_squad_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_team_squad_by_season",
            label="Football Get Team Squad By Season",
            method="GET",
            path="/team_squad/season/{season_id}",
            visible_fields=["season_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_teams_by_country",
            label="Football Get Teams By Country",
            method="GET",
            path="/teams/country/{country_id}",
            visible_fields=["country_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_teams_by_season",
            label="Football Get Teams By Season",
            method="GET",
            path="/teams/season/{season_id}",
            visible_fields=["season_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_topscorers_by_season",
            label="Football Get Topscorers By Season",
            method="GET",
            path="/topscorers/season/{season_id}",
            visible_fields=["season_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_topscorers_by_stage",
            label="Football Get Topscorers By Stage",
            method="GET",
            path="/topscorers/stage/{stage_id}",
            visible_fields=["stage_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_totw",
            label="Football Get Totw",
            method="GET",
            path="/totw/{totw_id}",
            visible_fields=["totw_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_totw_by_round",
            label="Football Get Totw By Round",
            method="GET",
            path="/totw/round/{round_id}",
            visible_fields=["round_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_transfer",
            label="Football Get Transfer",
            method="GET",
            path="/transfer/{transfer_id}",
            visible_fields=["transfer_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_transfer_rumour",
            label="Football Get Transfer Rumour",
            method="GET",
            path="/transfer_rumour/{transfer_rumour_id}",
            visible_fields=["transfer_rumour_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_transfer_rumours_between_dates",
            label="Football Get Transfer Rumours Between Dates",
            method="GET",
            path="/transfer_rumours_between_dates",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_transfer_rumours_by_player",
            label="Football Get Transfer Rumours By Player",
            method="GET",
            path="/transfer_rumours/player/{player_id}",
            visible_fields=["player_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_transfer_rumours_by_team",
            label="Football Get Transfer Rumours By Team",
            method="GET",
            path="/transfer_rumours/team/{team_id}",
            visible_fields=["team_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_transfers_between_dates",
            label="Football Get Transfers Between Dates",
            method="GET",
            path="/transfers_between_dates",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_transfers_by_player",
            label="Football Get Transfers By Player",
            method="GET",
            path="/transfers/player/{player_id}",
            visible_fields=["player_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_transfers_by_team",
            label="Football Get Transfers By Team",
            method="GET",
            path="/transfers/team/{team_id}",
            visible_fields=["team_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_tv_station",
            label="Football Get Tv Station",
            method="GET",
            path="/tv_station/{tv_station_id}",
            visible_fields=["tv_station_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_tv_stations",
            label="Football Get Tv Stations",
            method="GET",
            path="/tv_stations",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_tv_stations_by_fixture",
            label="Football Get Tv Stations By Fixture",
            method="GET",
            path="/tv_stations/fixture/{fixture_id}",
            visible_fields=["fixture_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_upcoming_fixtures_by_market",
            label="Football Get Upcoming Fixtures By Market",
            method="GET",
            path="/upcoming_fixtures/market/{market_id}",
            visible_fields=["market_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_upcoming_fixtures_by_tv_station",
            label="Football Get Upcoming Fixtures By Tv Station",
            method="GET",
            path="/upcoming_fixtures/tv_station/{tv_station_id}",
            visible_fields=["tv_station_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_value_bets",
            label="Football Get Value Bets",
            method="GET",
            path="/value_bets",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_value_bets_by_fixture",
            label="Football Get Value Bets By Fixture",
            method="GET",
            path="/value_bets/fixture/{fixture_id}",
            visible_fields=["fixture_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_venue",
            label="Football Get Venue",
            method="GET",
            path="/venue/{venue_id}",
            visible_fields=["venue_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_venues",
            label="Football Get Venues",
            method="GET",
            path="/venues",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_venues_by_season",
            label="Football Get Venues By Season",
            method="GET",
            path="/venues/season/{season_id}",
            visible_fields=["season_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="search_coaches",
            label="Football Search Coaches",
            method="GET",
            path="/coaches/search/{search_query}",
            visible_fields=["search_query"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="search_fixtures",
            label="Football Search Fixtures",
            method="GET",
            path="/fixtures/search/{search_query}",
            visible_fields=["search_query"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="search_leagues",
            label="Football Search Leagues",
            method="GET",
            path="/leagues/search/{search_query}",
            visible_fields=["search_query"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="search_players",
            label="Football Search Players",
            method="GET",
            path="/players/search/{search_query}",
            visible_fields=["search_query"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="search_referees",
            label="Football Search Referees",
            method="GET",
            path="/referees/search/{search_query}",
            visible_fields=["search_query"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="search_rounds",
            label="Football Search Rounds",
            method="GET",
            path="/rounds/search/{search_query}",
            visible_fields=["search_query"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="search_seasons",
            label="Football Search Seasons",
            method="GET",
            path="/seasons/search/{search_query}",
            visible_fields=["search_query"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="search_stages",
            label="Football Search Stages",
            method="GET",
            path="/stages/search/{search_query}",
            visible_fields=["search_query"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="search_teams",
            label="Football Search Teams",
            method="GET",
            path="/teams/search/{search_query}",
            visible_fields=["search_query"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="search_venues",
            label="Football Search Venues",
            method="GET",
            path="/venues/search/{search_query}",
            visible_fields=["search_query"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_all_fixtures",
            label="Motorsport Get All Fixtures",
            method="GET",
            path="/motorsport_get_all_fixtures",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_current_leagues_by_team",
            label="Motorsport Get Current Leagues By Team",
            method="GET",
            path="/motorsport_get_current_leagues_by_team",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_driver",
            label="Motorsport Get Driver",
            method="GET",
            path="/motorsport_get_driver",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_driver_standings",
            label="Motorsport Get Driver Standings",
            method="GET",
            path="/motorsport_get_driver_standings",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_driver_standings_by_season",
            label="Motorsport Get Driver Standings By Season",
            method="GET",
            path="/motorsport_get_driver_standings_by_season",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_drivers",
            label="Motorsport Get Drivers",
            method="GET",
            path="/motorsport_get_drivers",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_drivers_by_country",
            label="Motorsport Get Drivers By Country",
            method="GET",
            path="/motorsport_get_drivers_by_country",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_drivers_by_season",
            label="Motorsport Get Drivers By Season",
            method="GET",
            path="/motorsport_get_drivers_by_season",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_fixture",
            label="Motorsport Get Fixture",
            method="GET",
            path="/motorsport_get_fixture",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_fixtures_by_date",
            label="Motorsport Get Fixtures By Date",
            method="GET",
            path="/motorsport_get_fixtures_by_date",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_fixtures_by_date_range",
            label="Motorsport Get Fixtures By Date Range",
            method="GET",
            path="/motorsport_get_fixtures_by_date_range",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_fixtures_by_ids",
            label="Motorsport Get Fixtures By Ids",
            method="GET",
            path="/motorsport_get_fixtures_by_ids",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_laps_by_fixture",
            label="Motorsport Get Laps By Fixture",
            method="GET",
            path="/motorsport_get_laps_by_fixture",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_laps_by_fixture_and_driver",
            label="Motorsport Get Laps By Fixture And Driver",
            method="GET",
            path="/motorsport_get_laps_by_fixture_and_driver",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_laps_by_fixture_and_lap",
            label="Motorsport Get Laps By Fixture And Lap",
            method="GET",
            path="/motorsport_get_laps_by_fixture_and_lap",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_latest_laps_by_fixture",
            label="Motorsport Get Latest Laps By Fixture",
            method="GET",
            path="/motorsport_get_latest_laps_by_fixture",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_latest_pitstops_by_fixture",
            label="Motorsport Get Latest Pitstops By Fixture",
            method="GET",
            path="/motorsport_get_latest_pitstops_by_fixture",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_latest_stints_by_fixture",
            label="Motorsport Get Latest Stints By Fixture",
            method="GET",
            path="/motorsport_get_latest_stints_by_fixture",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_latest_updated_drivers",
            label="Motorsport Get Latest Updated Drivers",
            method="GET",
            path="/motorsport_get_latest_updated_drivers",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_latest_updated_fixtures",
            label="Motorsport Get Latest Updated Fixtures",
            method="GET",
            path="/motorsport_get_latest_updated_fixtures",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_league",
            label="Motorsport Get League",
            method="GET",
            path="/motorsport_get_league",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_leagues",
            label="Motorsport Get Leagues",
            method="GET",
            path="/motorsport_get_leagues",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_leagues_by_country",
            label="Motorsport Get Leagues By Country",
            method="GET",
            path="/motorsport_get_leagues_by_country",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_leagues_by_date",
            label="Motorsport Get Leagues By Date",
            method="GET",
            path="/motorsport_get_leagues_by_date",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_leagues_by_live",
            label="Motorsport Get Leagues By Live",
            method="GET",
            path="/motorsport_get_leagues_by_live",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_leagues_by_team",
            label="Motorsport Get Leagues By Team",
            method="GET",
            path="/motorsport_get_leagues_by_team",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_livescores",
            label="Motorsport Get Livescores",
            method="GET",
            path="/motorsport_get_livescores",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_pitstops_by_fixture",
            label="Motorsport Get Pitstops By Fixture",
            method="GET",
            path="/motorsport_get_pitstops_by_fixture",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_pitstops_by_fixture_and_driver",
            label="Motorsport Get Pitstops By Fixture And Driver",
            method="GET",
            path="/motorsport_get_pitstops_by_fixture_and_driver",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_pitstops_by_fixture_and_lap",
            label="Motorsport Get Pitstops By Fixture And Lap",
            method="GET",
            path="/motorsport_get_pitstops_by_fixture_and_lap",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_race_results_by_season_and_driver",
            label="Motorsport Get Race Results By Season And Driver",
            method="GET",
            path="/motorsport_get_race_results_by_season_and_driver",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_race_results_by_season_and_team",
            label="Motorsport Get Race Results By Season And Team",
            method="GET",
            path="/motorsport_get_race_results_by_season_and_team",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_schedules_by_season",
            label="Motorsport Get Schedules By Season",
            method="GET",
            path="/motorsport_get_schedules_by_season",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_season",
            label="Motorsport Get Season",
            method="GET",
            path="/motorsport_get_season",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_seasons",
            label="Motorsport Get Seasons",
            method="GET",
            path="/motorsport_get_seasons",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_stage",
            label="Motorsport Get Stage",
            method="GET",
            path="/motorsport_get_stage",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_stages",
            label="Motorsport Get Stages",
            method="GET",
            path="/motorsport_get_stages",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_stages_by_season",
            label="Motorsport Get Stages By Season",
            method="GET",
            path="/motorsport_get_stages_by_season",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_state",
            label="Motorsport Get State",
            method="GET",
            path="/motorsport_get_state",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_states",
            label="Motorsport Get States",
            method="GET",
            path="/motorsport_get_states",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_stints_by_fixture",
            label="Motorsport Get Stints By Fixture",
            method="GET",
            path="/motorsport_get_stints_by_fixture",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_stints_by_fixture_and_driver",
            label="Motorsport Get Stints By Fixture And Driver",
            method="GET",
            path="/motorsport_get_stints_by_fixture_and_driver",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_stints_by_fixture_and_stint",
            label="Motorsport Get Stints By Fixture And Stint",
            method="GET",
            path="/motorsport_get_stints_by_fixture_and_stint",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_team",
            label="Motorsport Get Team",
            method="GET",
            path="/motorsport_get_team",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_team_standings",
            label="Motorsport Get Team Standings",
            method="GET",
            path="/motorsport_get_team_standings",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_team_standings_by_season",
            label="Motorsport Get Team Standings By Season",
            method="GET",
            path="/motorsport_get_team_standings_by_season",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_teams",
            label="Motorsport Get Teams",
            method="GET",
            path="/motorsport_get_teams",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_teams_by_country",
            label="Motorsport Get Teams By Country",
            method="GET",
            path="/motorsport_get_teams_by_country",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_teams_by_season",
            label="Motorsport Get Teams By Season",
            method="GET",
            path="/motorsport_get_teams_by_season",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_venue",
            label="Motorsport Get Venue",
            method="GET",
            path="/motorsport_get_venue",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_venues",
            label="Motorsport Get Venues",
            method="GET",
            path="/motorsport_get_venues",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_get_venues_by_season",
            label="Motorsport Get Venues By Season",
            method="GET",
            path="/motorsport_get_venues_by_season",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_search_drivers",
            label="Motorsport Search Drivers",
            method="GET",
            path="/motorsport_search_drivers",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_search_leagues",
            label="Motorsport Search Leagues",
            method="GET",
            path="/motorsport_search_leagues",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_search_stages",
            label="Motorsport Search Stages",
            method="GET",
            path="/motorsport_search_stages",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_search_teams",
            label="Motorsport Search Teams",
            method="GET",
            path="/motorsport_search_teams",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="motorsport_search_venues",
            label="Motorsport Search Venues",
            method="GET",
            path="/motorsport_search_venues",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_get_all_historical_odds",
            label="Odds Get All Historical Odds",
            method="GET",
            path="/odds_get_all_historical_odds",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_get_all_inplay_odds",
            label="Odds Get All Inplay Odds",
            method="GET",
            path="/odds_get_all_inplay_odds",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_get_all_pre_match_odds",
            label="Odds Get All Pre Match Odds",
            method="GET",
            path="/odds_get_all_pre_match_odds",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_get_all_premium_odds",
            label="Odds Get All Premium Odds",
            method="GET",
            path="/odds_get_all_premium_odds",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_get_bookmaker",
            label="Odds Get Bookmaker",
            method="GET",
            path="/odds_get_bookmaker",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_get_bookmaker_event_ids_by_fixture",
            label="Odds Get Bookmaker Event Ids By Fixture",
            method="GET",
            path="/odds_get_bookmaker_event_ids_by_fixture",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_get_bookmakers",
            label="Odds Get Bookmakers",
            method="GET",
            path="/odds_get_bookmakers",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_get_bookmakers_by_fixture",
            label="Odds Get Bookmakers By Fixture",
            method="GET",
            path="/odds_get_bookmakers_by_fixture",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_get_inplay_odds_by_fixture",
            label="Odds Get Inplay Odds By Fixture",
            method="GET",
            path="/odds_get_inplay_odds_by_fixture",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_get_inplay_odds_by_fixture_and_bookmaker",
            label="Odds Get Inplay Odds By Fixture And Bookmaker",
            method="GET",
            path="/odds_get_inplay_odds_by_fixture_and_bookmaker",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_get_inplay_odds_by_fixture_and_market",
            label="Odds Get Inplay Odds By Fixture And Market",
            method="GET",
            path="/odds_get_inplay_odds_by_fixture_and_market",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_get_last_updated_inplay_odds",
            label="Odds Get Last Updated Inplay Odds",
            method="GET",
            path="/odds_get_last_updated_inplay_odds",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_get_last_updated_pre_match_odds",
            label="Odds Get Last Updated Pre Match Odds",
            method="GET",
            path="/odds_get_last_updated_pre_match_odds",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_get_market",
            label="Odds Get Market",
            method="GET",
            path="/odds_get_market",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_get_markets",
            label="Odds Get Markets",
            method="GET",
            path="/odds_get_markets",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_get_pre_match_odds_by_fixture",
            label="Odds Get Pre Match Odds By Fixture",
            method="GET",
            path="/odds_get_pre_match_odds_by_fixture",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_get_pre_match_odds_by_fixture_and_bookmaker",
            label="Odds Get Pre Match Odds By Fixture And Bookmaker",
            method="GET",
            path="/odds_get_pre_match_odds_by_fixture_and_bookmaker",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_get_pre_match_odds_by_fixture_and_market",
            label="Odds Get Pre Match Odds By Fixture And Market",
            method="GET",
            path="/odds_get_pre_match_odds_by_fixture_and_market",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_get_premium_odds_by_fixture",
            label="Odds Get Premium Odds By Fixture",
            method="GET",
            path="/odds_get_premium_odds_by_fixture",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_get_premium_odds_by_fixture_and_bookmaker",
            label="Odds Get Premium Odds By Fixture And Bookmaker",
            method="GET",
            path="/odds_get_premium_odds_by_fixture_and_bookmaker",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_get_premium_odds_by_fixture_and_market",
            label="Odds Get Premium Odds By Fixture And Market",
            method="GET",
            path="/odds_get_premium_odds_by_fixture_and_market",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_get_updated_historical_odds_between",
            label="Odds Get Updated Historical Odds Between",
            method="GET",
            path="/odds_get_updated_historical_odds_between",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_get_updated_premium_odds_between",
            label="Odds Get Updated Premium Odds Between",
            method="GET",
            path="/odds_get_updated_premium_odds_between",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_search_bookmakers",
            label="Odds Search Bookmakers",
            method="GET",
            path="/odds_search_bookmakers",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="odds_search_markets",
            label="Odds Search Markets",
            method="GET",
            path="/odds_search_markets",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="core_get_cities",
            label="Core Get Cities",
            method="GET",
            path="/core_get_cities",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="core_get_city",
            label="Core Get City",
            method="GET",
            path="/core_get_city",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="core_get_continent",
            label="Core Get Continent",
            method="GET",
            path="/core_get_continent",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="core_get_continents",
            label="Core Get Continents",
            method="GET",
            path="/core_get_continents",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="core_get_countries",
            label="Core Get Countries",
            method="GET",
            path="/core_get_countries",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="core_get_country",
            label="Core Get Country",
            method="GET",
            path="/core_get_country",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="core_get_entity_filters",
            label="Core Get Entity Filters",
            method="GET",
            path="/core_get_entity_filters",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="core_get_my_usage",
            label="Core Get My Usage",
            method="GET",
            path="/core_get_my_usage",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="core_get_region",
            label="Core Get Region",
            method="GET",
            path="/core_get_region",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="core_get_regions",
            label="Core Get Regions",
            method="GET",
            path="/core_get_regions",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="core_get_timezones",
            label="Core Get Timezones",
            method="GET",
            path="/core_get_timezones",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="core_get_type",
            label="Core Get Type",
            method="GET",
            path="/core_get_type",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="core_get_type_by_entity",
            label="Core Get Type By Entity",
            method="GET",
            path="/core_get_type_by_entity",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="core_get_types",
            label="Core Get Types",
            method="GET",
            path="/core_get_types",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="core_search_cities",
            label="Core Search Cities",
            method="GET",
            path="/core_search_cities",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="core_search_countries",
            label="Core Search Countries",
            method="GET",
            path="/core_search_countries",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="core_search_regions",
            label="Core Search Regions",
            method="GET",
            path="/core_search_regions",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "id", "type": "string"},
    ],
    allow_error=True,
)
