"""Persona action node — Persona — identity verification + KYC.

REST at https://api.withpersona.com/api/v1. See sim-parity roadmap Phase 4.16/4.17.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.persona",
    name="Persona",
    category="integration",
    description="Persona — identity verification + KYC.",
    icon_slug="persona",
    color="#1c1c1c",
    base_url="https://api.withpersona.com/api/v1",
    credential_type="persona_api_key",
    token_field=["api_key"],
    auth="bearer",
    fields=[
        FieldSpec(name="email", label="Email", type="string"),
        FieldSpec(name="first_name", label="First Name", type="string"),
        FieldSpec(name="last_name", label="Last Name", type="string"),
        FieldSpec(name="linkedin_url", label="LinkedIn URL", type="string"),
        FieldSpec(name="domain", label="Domain / Website", type="string"),
        FieldSpec(name="company", label="Company Name", type="string"),
        FieldSpec(name="query", label="Search Query (JSON)", type="json", mode="advanced"),
        FieldSpec(name="size", label="Size", type="number", default=25, mode="advanced"),
        FieldSpec(name="page", label="Page", type="number", default=1, mode="advanced"),
        FieldSpec(name="per_page", label="Per Page", type="number", default=25, mode="advanced"),
        FieldSpec(name="limit", label="Limit", type="number", default=100, mode="advanced"),
        FieldSpec(name="inquiry_id", label="Inquiry ID", type="string"),
        FieldSpec(name="verification_id", label="Verification ID", type="string"),
        FieldSpec(name="account_id", label="Account ID", type="string"),
        FieldSpec(name="list_id", label="List ID", type="string"),
        FieldSpec(name="start_date", label="Start Date (YYYY-MM)", type="string"),
        FieldSpec(name="end_date", label="End Date (YYYY-MM)", type="string"),
        FieldSpec(name="inquiry_body", label="Inquiry Attributes (JSON)", type="json", default={}),
        FieldSpec(name="account_body", label="Account Attributes (JSON)", type="json", default={}),
        FieldSpec(name="import_body", label="Import Body (JSON)", type="json", default={}),
        FieldSpec(name="case_id", label="Case ID", type="string"),
        FieldSpec(name="report_id", label="Report ID", type="string"),
        FieldSpec(name="report_body", label="Report Attributes (JSON)", type="json", default={}),
        FieldSpec(name="document_id", label="Document ID", type="string"),
    ],
    operations=[
        OpSpec(
            id="get_inquiry",
            label="Get Inquiry",
            method="GET",
            path="/inquiries/{inquiry_id}",
            visible_fields=["inquiry_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_inquiries",
            label="List Inquiries",
            method="GET",
            path="/inquiries",
            visible_fields=["page", "per_page"],
            query_builder=lambda v: {
                k: val
                for k, val in {
                    "page[size]": int(getattr(v, "per_page", 25) or 25),
                    "page[number]": int(getattr(v, "page", 1) or 1),
                }.items()
                if val is not None
            },
        ),
        OpSpec(
            id="get_verification",
            label="Get Verification",
            method="GET",
            path="/verifications/{verification_id}",
            visible_fields=["verification_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_account",
            label="Get Account",
            method="GET",
            path="/accounts/{account_id}",
            visible_fields=["account_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_inquiry",
            label="Create Inquiry",
            method="POST",
            path="/api/v1/inquiries",
            visible_fields=["inquiry_body"],
            body_builder=lambda v: {"data": {"attributes": getattr(v, "inquiry_body", None) or {}}},
        ),
        OpSpec(
            id="update_inquiry",
            label="Update Inquiry",
            method="PATCH",
            path="/api/v1/inquiries/{inquiry_id}",
            visible_fields=["inquiry_id", "inquiry_body"],
            body_builder=lambda v: {"data": {"attributes": getattr(v, "inquiry_body", None) or {}}},
        ),
        OpSpec(
            id="approve_inquiry",
            label="Approve Inquiry",
            method="POST",
            path="/api/v1/inquiries/{inquiry_id}/approve",
            visible_fields=["inquiry_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="decline_inquiry",
            label="Decline Inquiry",
            method="POST",
            path="/api/v1/inquiries/{inquiry_id}/decline",
            visible_fields=["inquiry_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="mark_inquiry_for_review",
            label="Mark Inquiry for Review",
            method="POST",
            path="/api/v1/inquiries/{inquiry_id}/mark-for-review",
            visible_fields=["inquiry_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="resume_inquiry",
            label="Resume Inquiry",
            method="POST",
            path="/api/v1/inquiries/{inquiry_id}/resume",
            visible_fields=["inquiry_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="expire_inquiry",
            label="Expire Inquiry",
            method="POST",
            path="/api/v1/inquiries/{inquiry_id}/expire",
            visible_fields=["inquiry_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="generate_inquiry_link",
            label="Generate Inquiry Link",
            method="POST",
            path="/api/v1/inquiries/{inquiry_id}/generate-one-time-link",
            visible_fields=["inquiry_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="print_inquiry_pdf",
            label="Print Inquiry PDF",
            method="GET",
            path="/api/v1/inquiries/{inquiry_id}/print",
            visible_fields=["inquiry_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="redact_inquiry",
            label="Redact Inquiry",
            method="POST",
            path="/api/v1/inquiries/{inquiry_id}/redact",
            visible_fields=["inquiry_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="create_account",
            label="Create Account",
            method="POST",
            path="/api/v1/accounts",
            visible_fields=["account_body"],
            body_builder=lambda v: {"data": {"attributes": getattr(v, "account_body", None) or {}}},
        ),
        OpSpec(
            id="list_accounts",
            label="List Accounts",
            method="GET",
            path="/api/v1/accounts",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="update_account",
            label="Update Account",
            method="PATCH",
            path="/api/v1/accounts/{account_id}",
            visible_fields=["account_id", "account_body"],
            body_builder=lambda v: {"data": {"attributes": getattr(v, "account_body", None) or {}}},
        ),
        OpSpec(
            id="import_accounts",
            label="Import Accounts",
            method="POST",
            path="/api/v1/import/accounts",
            visible_fields=["import_body"],
            body_builder=lambda v: getattr(v, "import_body", None) or {},
        ),
        OpSpec(
            id="redact_account",
            label="Redact Account",
            method="POST",
            path="/api/v1/accounts/{account_id}/redact",
            visible_fields=["account_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="list_cases",
            label="List Cases",
            method="GET",
            path="/api/v1/cases",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_case",
            label="Get Case",
            method="GET",
            path="/api/v1/cases/{case_id}",
            visible_fields=["case_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_report",
            label="Create Report",
            method="POST",
            path="/api/v1/reports",
            visible_fields=["report_body"],
            body_builder=lambda v: {"data": {"attributes": getattr(v, "report_body", None) or {}}},
        ),
        OpSpec(
            id="get_report",
            label="Get Report",
            method="GET",
            path="/api/v1/reports/{report_id}",
            visible_fields=["report_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_reports",
            label="List Reports",
            method="GET",
            path="/api/v1/reports",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_document",
            label="Get Document",
            method="GET",
            path="/api/v1/documents/{document_id}",
            visible_fields=["document_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_inquiry_templates",
            label="List Inquiry Templates",
            method="GET",
            path="/api/v1/inquiry-templates",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "result", "type": "string"},
        {"label": "email", "type": "string"},
        {"label": "status", "type": "string"},
    ],
    allow_error=True,
)
