"""Elasticsearch action node — Elasticsearch — index, search, aggregate documents.

REST at {host}. See sim-parity roadmap Phase 4.21.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import (
    FieldSpec,
    OpSpec,
    ProviderManifest,
    RemoteLookup,
)

MANIFEST = ProviderManifest(
    type="action.elasticsearch",
    name="Elasticsearch",
    category="integration",
    description="Elasticsearch — index, search, aggregate documents.",
    icon_slug="elasticsearch",
    color="#ffffff",
    base_url="{host}",
    credential_type="elasticsearch_api_key",
    token_field=["api_key"],
    auth="basic",
    auth_basic_username="{username}",
    fields=[
        FieldSpec(name="warehouse_id", label="SQL Warehouse ID", type="string"),
        FieldSpec(name="statement", label="SQL Statement", type="string"),
        FieldSpec(name="statement_id", label="Statement ID", type="string"),
        FieldSpec(name="catalog", label="Catalog", type="string"),
        FieldSpec(name="schema_name", label="Schema", type="string"),
        FieldSpec(name="job_id", label="Job ID", type="string"),
        FieldSpec(name="run_id", label="Run ID", type="string"),
        FieldSpec(name="parameters", label="Parameters (JSON)", type="json"),
        FieldSpec(name="sql", label="SQL", type="string"),
        FieldSpec(name="database", label="Database", type="string"),
        FieldSpec(name="table", label="Table", type="string"),
        FieldSpec(name="rows", label="Rows (JSONEachRow)", type="string"),
        FieldSpec(
            name="index",
            label="Index",
            type="string",
            remote=RemoteLookup(provider="elasticsearch", resource="indices"),
        ),
        FieldSpec(name="doc_id", label="Doc ID", type="string"),
        FieldSpec(name="document", label="Document (JSON)", type="json"),
        FieldSpec(name="query", label="Query (JSON / DSL / KQL)", type="json"),
        FieldSpec(name="function_name", label="Function Path", type="string"),
        FieldSpec(name="args", label="Function Args (JSON)", type="json"),
        FieldSpec(name="namespace", label="Namespace", type="string"),
        FieldSpec(name="workflow_id", label="Workflow ID", type="string"),
        FieldSpec(name="workflow_type", label="Workflow Type", type="string"),
        FieldSpec(name="task_queue", label="Task Queue", type="string"),
        FieldSpec(name="input", label="Input (JSON)", type="json"),
        FieldSpec(name="signal_name", label="Signal Name", type="string"),
        FieldSpec(name="reason", label="Reason", type="string"),
        FieldSpec(name="es_index", label="Index", type="string"),
        FieldSpec(name="es_doc_id", label="Document ID", type="string"),
        FieldSpec(name="es_query_body", label="Query Body (JSON)", type="json", default={}),
        FieldSpec(name="es_doc_body", label="Document Body (JSON)", type="json", default={}),
        FieldSpec(name="es_update_body", label="Update Body (JSON)", type="json", default={}),
        FieldSpec(name="es_bulk_ops", label="Bulk Ops (newline-delim JSON)", type="string"),
        FieldSpec(
            name="es_index_body", label="Index Settings Body (JSON)", type="json", default={}
        ),
    ],
    operations=[
        OpSpec(
            id="search",
            label="Search",
            method="POST",
            path="/{es_index}/_search",
            visible_fields=["es_index", "es_query_body"],
            body_builder=lambda v: getattr(v, "es_query_body", None) or {},
        ),
        OpSpec(
            id="index_document",
            label="Index Document",
            method="POST",
            path="/{es_index}/_doc",
            visible_fields=["es_index", "es_doc_body"],
            body_builder=lambda v: getattr(v, "es_doc_body", None) or {},
        ),
        OpSpec(
            id="get_document",
            label="Get Document",
            method="GET",
            path="/{es_index}/_doc/{es_doc_id}",
            visible_fields=["es_index", "es_doc_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="update_document",
            label="Update Document",
            method="POST",
            path="/{es_index}/_update/{es_doc_id}",
            visible_fields=["es_index", "es_doc_id", "es_update_body"],
            body_builder=lambda v: getattr(v, "es_update_body", None) or {},
        ),
        OpSpec(
            id="delete_document",
            label="Delete Document",
            method="DELETE",
            path="/{es_index}/_doc/{es_doc_id}",
            visible_fields=["es_index", "es_doc_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="bulk",
            label="Bulk API",
            method="POST",
            path="/_bulk",
            visible_fields=["es_bulk_ops"],
            body_builder=lambda v: getattr(v, "es_bulk_ops", "") or "",
        ),
        OpSpec(
            id="count",
            label="Count",
            method="POST",
            path="/{es_index}/_count",
            visible_fields=["es_index", "es_query_body"],
            body_builder=lambda v: getattr(v, "es_query_body", None) or {},
        ),
        OpSpec(
            id="create_index",
            label="Create Index",
            method="PUT",
            path="/{es_index}",
            visible_fields=["es_index", "es_index_body"],
            body_builder=lambda v: getattr(v, "es_index_body", None) or {},
        ),
        OpSpec(
            id="delete_index",
            label="Delete Index",
            method="DELETE",
            path="/{es_index}",
            visible_fields=["es_index"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_index",
            label="Get Index",
            method="GET",
            path="/{es_index}",
            visible_fields=["es_index"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_indices",
            label="List Indices",
            method="GET",
            path="/_cat/indices",
            visible_fields=[],
            query_builder=lambda v: {"format": "json"},
        ),
        OpSpec(
            id="cluster_health",
            label="Cluster Health",
            method="GET",
            path="/_cluster/health",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="cluster_stats",
            label="Cluster Stats",
            method="GET",
            path="/_cluster/stats",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "result", "type": "object"},
        {"label": "status", "type": "string"},
    ],
    allow_error=True,
)
