"""SAP Concur action node — SAP Concur — travel + expense management.

REST at https://us.api.concursolutions.com. See sim-parity roadmap Phase 4.24.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.sap_concur",
    name="SAP Concur",
    category="integration",
    description="SAP Concur — travel + expense management.",
    icon_slug="sap_concur",
    color="#1c1c1c",
    base_url="https://us.api.concursolutions.com",
    credential_type="sap_concur_api_key",
    token_field=["api_key"],
    auth="bearer",
    fields=[
        FieldSpec(name="employee_id", label="Employee ID", type="string"),
        FieldSpec(name="worker_id", label="Worker ID", type="string"),
        FieldSpec(name="user_id", label="User ID", type="string"),
        FieldSpec(name="contact_id", label="Contact ID", type="string"),
        FieldSpec(name="tenant", label="Tenant", type="string"),
        FieldSpec(name="raas_url", label="RaaS Report URL", type="string"),
        FieldSpec(name="report_id", label="Report ID", type="string"),
        FieldSpec(name="expense_id", label="Expense ID", type="string"),
        FieldSpec(name="first_name", label="First Name", type="string"),
        FieldSpec(name="last_name", label="Last Name", type="string"),
        FieldSpec(name="email", label="Email", type="string"),
        FieldSpec(name="content", label="Content", type="string"),
        FieldSpec(name="limit", label="Limit", type="number", default=25, mode="advanced"),
        FieldSpec(name="offset", label="Offset", type="number", default=0, mode="advanced"),
        FieldSpec(name="context", label="Context (TRAVELER|APPROVER|PROCESSOR)", type="string"),
        FieldSpec(name="entry_id", label="Entry ID", type="string"),
        FieldSpec(name="booking_id", label="Booking ID", type="string"),
        FieldSpec(name="comment_body", label="Comment", type="string"),
        FieldSpec(name="cash_advance_id", label="Cash Advance ID", type="string"),
        FieldSpec(name="receipt_id", label="Receipt ID", type="string"),
        FieldSpec(name="request_id", label="Travel Request ID", type="string"),
        FieldSpec(name="report_body", label="Report Body (JSON)", type="json", default={}),
        FieldSpec(name="invoice_id", label="Invoice ID", type="string"),
        FieldSpec(name="form_id", label="Form ID", type="string"),
        FieldSpec(name="policy_id", label="Policy ID", type="string"),
        FieldSpec(name="extract_id", label="Extract Definition ID", type="string"),
    ],
    operations=[
        OpSpec(
            id="list_reports",
            label="List Expense Reports",
            method="GET",
            path="/api/v3.0/expense/reports",
            visible_fields=["user_id"],
            query_builder=lambda v: {
                k: val for k, val in {"user": getattr(v, "user_id", None) or None}.items() if val
            },
        ),
        OpSpec(
            id="get_report",
            label="Get Expense Report",
            method="GET",
            path="/api/v3.0/expense/reports/{report_id}",
            visible_fields=["report_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_entries",
            label="List Entries in Report",
            method="GET",
            path="/api/v3.0/expense/entries",
            visible_fields=["report_id"],
            query_builder=lambda v: {"reportID": getattr(v, "report_id", "") or ""},
        ),
        OpSpec(
            id="get_report_details",
            label="Get Report Details",
            method="GET",
            path="/expensereports/v4/users/{user_id}/context/{context}/reports/{report_id}",
            visible_fields=["user_id", "context", "report_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_expenses",
            label="List Expense Entries",
            method="GET",
            path="/api/v3.0/expense/entries",
            visible_fields=["report_id"],
            query_builder=lambda v: {
                k: val
                for k, val in {"reportID": getattr(v, "report_id", None) or None}.items()
                if val
            },
        ),
        OpSpec(
            id="get_expense",
            label="Get Expense Entry",
            method="GET",
            path="/api/v3.0/expense/entries/{entry_id}",
            visible_fields=["entry_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_receipts",
            label="List Receipt Images",
            method="GET",
            path="/api/v3.0/expense/receiptimages",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_users",
            label="List Users",
            method="GET",
            path="/api/v3.0/common/users",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_user",
            label="Get User",
            method="GET",
            path="/api/v3.0/common/users/{user_id}",
            visible_fields=["user_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_travel_bookings",
            label="List Travel Bookings",
            method="GET",
            path="/api/travel/v1.1/bookings",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_travel_booking",
            label="Get Travel Booking",
            method="GET",
            path="/api/travel/v1.1/bookings/{booking_id}",
            visible_fields=["booking_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_itemization_types",
            label="List Itemization Types",
            method="GET",
            path="/api/v3.0/expense/itemizationtypes",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_expense_types",
            label="List Expense Types",
            method="GET",
            path="/api/v3.0/expense/expensetypes",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_currency_codes",
            label="List Currency Codes",
            method="GET",
            path="/api/v3.0/common/enums/currencies",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="submit_report",
            label="Submit Expense Report",
            method="POST",
            path="/expensereports/v4/users/{user_id}/context/{context}/reports/{report_id}/submit",
            visible_fields=["user_id", "context", "report_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="approve_report",
            label="Approve Expense Report",
            method="POST",
            path="/expensereports/v4/users/{user_id}/context/{context}/reports/{report_id}/approve",
            visible_fields=["user_id", "context", "report_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="reject_report",
            label="Reject Expense Report",
            method="POST",
            path="/expensereports/v4/users/{user_id}/context/{context}/reports/{report_id}/reject",
            visible_fields=["user_id", "context", "report_id", "comment_body"],
            body_builder=lambda v: {"comment": getattr(v, "comment_body", None) or None},
        ),
        OpSpec(
            id="recall_report",
            label="Recall Expense Report",
            method="POST",
            path="/expensereports/v4/users/{user_id}/context/{context}/reports/{report_id}/recall",
            visible_fields=["user_id", "context", "report_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="list_pending_approvals",
            label="List Pending Approvals",
            method="GET",
            path="/expensereports/v4/users/{user_id}/context/{context}/reports?state=Pending",
            visible_fields=["user_id", "context"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_cash_advances",
            label="List Cash Advances",
            method="GET",
            path="/api/v3.0/expense/cashadvances",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_cash_advance",
            label="Get Cash Advance",
            method="GET",
            path="/api/v3.0/expense/cashadvances/{cash_advance_id}",
            visible_fields=["cash_advance_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_locations",
            label="List Locations",
            method="GET",
            path="/api/v3.0/common/locations",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_departments",
            label="List Departments",
            method="GET",
            path="/api/v3.0/common/departments",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_cost_objects",
            label="List Cost Objects",
            method="GET",
            path="/api/v3.0/common/costobjects",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_attendee_types",
            label="List Attendee Types",
            method="GET",
            path="/api/v3.0/expense/attendeetypes",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_attendees",
            label="List Attendees for Entry",
            method="GET",
            path="/api/v3.0/expense/attendees",
            visible_fields=["entry_id"],
            query_builder=lambda v: {
                k: val
                for k, val in {"entryID": getattr(v, "entry_id", None) or None}.items()
                if val
            },
        ),
        OpSpec(
            id="create_report_from_template",
            label="Create Report from Template",
            method="POST",
            path="/api/v3.0/expense/reports",
            visible_fields=["report_body"],
            body_builder=lambda v: getattr(v, "report_body", None) or {},
        ),
        OpSpec(
            id="get_report_ancillary_data",
            label="Get Report Ancillary Data",
            method="GET",
            path="/api/v3.0/expense/reports/{report_id}/ancillarydata",
            visible_fields=["report_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_report_states",
            label="List Report States",
            method="GET",
            path="/api/v3.0/expense/reportstates",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_receipt_types",
            label="List Receipt Types",
            method="GET",
            path="/api/v3.0/expense/receipttypes",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_receipt",
            label="Get Receipt Image",
            method="GET",
            path="/api/v3.0/expense/receiptimages/{receipt_id}",
            visible_fields=["receipt_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="delete_receipt",
            label="Delete Receipt Image",
            method="DELETE",
            path="/api/v3.0/expense/receiptimages/{receipt_id}",
            visible_fields=["receipt_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_travel_requests",
            label="List Travel Requests",
            method="GET",
            path="/travelrequest/v4/requests",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_travel_request",
            label="Get Travel Request",
            method="GET",
            path="/travelrequest/v4/requests/{request_id}",
            visible_fields=["request_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_travel_profiles",
            label="List Travel Profiles",
            method="GET",
            path="/api/travelprofile/v2.0/profile",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_travel_profile",
            label="Get Travel Profile",
            method="GET",
            path="/api/travelprofile/v2.0/profile/{user_id}",
            visible_fields=["user_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_invoices",
            label="List Invoices",
            method="GET",
            path="/api/v3.0/invoice/invoices",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_invoice",
            label="Get Invoice",
            method="GET",
            path="/api/v3.0/invoice/invoices/{invoice_id}",
            visible_fields=["invoice_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_purchase_requests",
            label="List Purchase Requests",
            method="GET",
            path="/api/v3.0/invoice/purchaserequests",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_vendors",
            label="List Vendors",
            method="GET",
            path="/api/v3.0/invoice/vendors",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_car_bookings",
            label="List Car Bookings",
            method="GET",
            path="/api/travel/v1.1/carbookings",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_hotel_bookings",
            label="List Hotel Bookings",
            method="GET",
            path="/api/travel/v1.1/hotelbookings",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_air_bookings",
            label="List Air Bookings",
            method="GET",
            path="/api/travel/v1.1/airbookings",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_rail_bookings",
            label="List Rail Bookings",
            method="GET",
            path="/api/travel/v1.1/railbookings",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_travel_itineraries",
            label="List Travel Itineraries",
            method="GET",
            path="/api/travel/v1.1/itineraries",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_expense_form",
            label="Get Expense Form",
            method="GET",
            path="/api/v3.0/expense/forms/{form_id}",
            visible_fields=["form_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_expense_forms",
            label="List Expense Forms",
            method="GET",
            path="/api/v3.0/expense/forms",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_group_configurations",
            label="List Group Configurations",
            method="GET",
            path="/api/v3.0/expense/groupconfigurations",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_delegators",
            label="List Delegators",
            method="GET",
            path="/api/v3.0/common/delegates/delegators",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_delegates",
            label="List Delegates",
            method="GET",
            path="/api/v3.0/common/delegates",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_credit_card_transactions",
            label="List Credit Card Transactions",
            method="GET",
            path="/api/v3.0/expense/creditcardtransactions",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_mileage_rates",
            label="List Mileage Rates",
            method="GET",
            path="/api/v3.0/expense/mileagerates",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_reimbursement_currencies",
            label="List Reimbursement Currencies",
            method="GET",
            path="/api/v3.0/common/reimbursementcurrencies",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_travel_policies",
            label="List Travel Policies",
            method="GET",
            path="/api/travel/v1.1/policies",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_travel_policy",
            label="Get Travel Policy",
            method="GET",
            path="/api/travel/v1.1/policies/{policy_id}",
            visible_fields=["policy_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_supplier_lists",
            label="List Supplier Lists",
            method="GET",
            path="/api/v3.0/common/lists",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_extract_definitions",
            label="List Extract Definitions",
            method="GET",
            path="/extract/v4/{context}/definitions",
            visible_fields=["context"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_extract_definition",
            label="Get Extract Definition",
            method="GET",
            path="/extract/v4/{context}/definitions/{extract_id}",
            visible_fields=["context", "extract_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_extract_runs",
            label="List Extract Runs",
            method="GET",
            path="/extract/v4/{context}/definitions/{extract_id}/runs",
            visible_fields=["context", "extract_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_purchase_orders",
            label="List Purchase Orders",
            method="GET",
            path="/api/v3.0/invoice/purchaseorders",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_payment_requests",
            label="List Payment Requests",
            method="GET",
            path="/api/v3.0/invoice/paymentrequests",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_payment_request_details",
            label="List Payment Request Details",
            method="GET",
            path="/api/v3.0/invoice/paymentrequestdetails",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_invoice_configurations",
            label="List Invoice Configurations",
            method="GET",
            path="/api/v3.0/invoice/configurations",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "results", "type": "array"},
    ],
    allow_error=True,
)
