"""Vanta action node — Vanta — compliance controls, findings, security tests.

REST at https://api.vanta.com/v1. See sim-parity roadmap Phase 4.30.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.vanta",
    name="Vanta",
    category="integration",
    description="Vanta — compliance controls, findings, security tests.",
    icon_slug="vanta",
    color="#ffffff",
    base_url="https://api.vanta.com/v1",
    credential_type="vanta_api_key",
    token_field=["api_key"],
    auth="bearer",
    fields=[
        FieldSpec(name="tailnet", label="Tailnet", type="string", default="-"),
        FieldSpec(name="device_id", label="Device ID", type="string"),
        FieldSpec(name="tags", label="Tags (JSON array)", type="json", default=[]),
        FieldSpec(name="s3_bucket", label="S3 Bucket", type="string"),
        FieldSpec(name="s3_key", label="S3 Key", type="string"),
        FieldSpec(
            name="feature_types",
            label="Feature Types (JSON)",
            type="json",
            default=["TABLES", "FORMS"],
        ),
        FieldSpec(name="pipeline_name", label="Pipeline Name", type="string"),
        FieldSpec(name="task_id", label="Task ID", type="string"),
        FieldSpec(name="run_id", label="Run ID", type="string"),
        FieldSpec(name="payload", label="Payload (JSON)", type="json", default={}),
        FieldSpec(name="test_id", label="Test ID", type="string"),
        FieldSpec(name="status", label="Status", type="string"),
        FieldSpec(name="event_ticker", label="Event Ticker", type="string"),
        FieldSpec(name="ticker", label="Ticker", type="string"),
        FieldSpec(name="side", label="Side (yes|no|buy|sell)", type="string"),
        FieldSpec(name="count", label="Count", type="number", default=1),
        FieldSpec(name="price", label="Yes Price (¢)", type="number", default=50),
        FieldSpec(name="condition_id", label="Condition ID", type="string"),
        FieldSpec(name="token_id", label="Token ID", type="string"),
        FieldSpec(name="fixture_id", label="Fixture ID", type="string"),
        FieldSpec(name="app_user_id", label="App User ID", type="string"),
        FieldSpec(name="entitlement_id", label="Entitlement ID", type="string"),
        FieldSpec(name="duration", label="Duration", type="string", default="monthly"),
        FieldSpec(name="framework_id", label="Framework ID", type="string"),
        FieldSpec(name="control_id", label="Control ID", type="string"),
        FieldSpec(name="document_id", label="Document ID", type="string"),
        FieldSpec(name="person_id", label="Person ID", type="string"),
        FieldSpec(name="policy_id", label="Policy ID", type="string"),
        FieldSpec(name="vendor_id", label="Vendor ID", type="string"),
        FieldSpec(name="vuln_id", label="Vulnerability ID", type="string"),
        FieldSpec(name="asset_id", label="Asset ID", type="string"),
    ],
    operations=[
        OpSpec(
            id="list_controls",
            label="List Controls",
            method="GET",
            path="/controls",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_findings",
            label="List Findings",
            method="GET",
            path="/findings",
            visible_fields=["status"],
            query_builder=lambda v: {
                k: val for k, val in {"status": getattr(v, "status", None) or None}.items() if val
            },
        ),
        OpSpec(
            id="list_tests",
            label="List Tests",
            method="GET",
            path="/tests",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_test",
            label="Get Test",
            method="GET",
            path="/tests/{test_id}",
            visible_fields=["test_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_frameworks",
            label="List Frameworks",
            method="GET",
            path="/frameworks",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_framework",
            label="Get Framework",
            method="GET",
            path="/frameworks/{framework_id}",
            visible_fields=["framework_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_framework_controls",
            label="List Controls for Framework",
            method="GET",
            path="/frameworks/{framework_id}/controls",
            visible_fields=["framework_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_control",
            label="Get Control",
            method="GET",
            path="/controls/{control_id}",
            visible_fields=["control_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_control_tests",
            label="List Tests for Control",
            method="GET",
            path="/controls/{control_id}/tests",
            visible_fields=["control_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_control_documents",
            label="List Documents for Control",
            method="GET",
            path="/controls/{control_id}/documents",
            visible_fields=["control_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_test_entities",
            label="List Entities for Test",
            method="GET",
            path="/tests/{test_id}/entities",
            visible_fields=["test_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_documents",
            label="List Documents",
            method="GET",
            path="/documents",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_document",
            label="Get Document",
            method="GET",
            path="/documents/{document_id}",
            visible_fields=["document_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_document_uploads",
            label="List Document Uploads",
            method="GET",
            path="/documents/{document_id}/uploads",
            visible_fields=["document_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="submit_document",
            label="Submit Document",
            method="POST",
            path="/documents/{document_id}/submit",
            visible_fields=["document_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="list_people",
            label="List People",
            method="GET",
            path="/people",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_person",
            label="Get Person",
            method="GET",
            path="/people/{person_id}",
            visible_fields=["person_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_policies",
            label="List Policies",
            method="GET",
            path="/policies",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_policy",
            label="Get Policy",
            method="GET",
            path="/policies/{policy_id}",
            visible_fields=["policy_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_vendors",
            label="List Vendors",
            method="GET",
            path="/vendors",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_vendor",
            label="Get Vendor",
            method="GET",
            path="/vendors/{vendor_id}",
            visible_fields=["vendor_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_monitored_computers",
            label="List Monitored Computers",
            method="GET",
            path="/monitored-computers",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_vulnerabilities",
            label="List Vulnerabilities",
            method="GET",
            path="/vulnerabilities",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_vulnerability_remediations",
            label="List Vulnerability Remediations",
            method="GET",
            path="/vulnerabilities/{vuln_id}/remediations",
            visible_fields=["vuln_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_vulnerable_assets",
            label="List Vulnerable Assets",
            method="GET",
            path="/vulnerable-assets",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_vulnerable_asset",
            label="Get Vulnerable Asset",
            method="GET",
            path="/vulnerable-assets/{asset_id}",
            visible_fields=["asset_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_risk_scenarios",
            label="List Risk Scenarios",
            method="GET",
            path="/risk-scenarios",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "id", "type": "string"},
    ],
    allow_error=True,
)
