"""Salesforce action node — manifest form.

Salesforce REST API v60.0. Base URL resolves per-org from the OAuth
credential's `instance_url` (`https://mycompany.my.salesforce.com`) +
`/services/data/v60.0`. The scaffold's `{instance_url}` template is
read from the credential dict via `_PropCredView`.

"""

from __future__ import annotations

from apps.api.app.node_system.nodes.salesforce import COLOR, ICON_SLUG, NAME
from apps.api.app.node_system.scaffolds import (
    FieldSpec,
    OpSpec,
    ProviderManifest,
    RemoteLookup,
)

MANIFEST = ProviderManifest(
    type="action.salesforce",
    name=NAME,
    category="integration",
    description="Salesforce — SObject records (Lead, Contact, Account, Opportunity, Case).",
    icon_slug=ICON_SLUG,
    color=COLOR,
    base_url="{instance_url}/services/data/v60.0",
    credential_type="salesforce_oauth",
    token_field=["access_token"],
    auth="bearer",
    fields=[
        FieldSpec(
            name="sobject",
            label="SObject",
            type="string",
            remote=RemoteLookup(provider="salesforce", resource="objects"),
        ),
        FieldSpec(name="record_id", label="Record ID", type="string"),
        FieldSpec(name="record_data", label="Record Data (JSON)", type="json", default={}),
        FieldSpec(
            name="soql",
            label="SOQL",
            type="string",
            placeholder="SELECT Id, Name FROM Account LIMIT 10",
        ),
        FieldSpec(name="external_id_field", label="External ID Field", type="string"),
        FieldSpec(name="external_id_value", label="External ID Value", type="string"),
        FieldSpec(name="search_sosl", label="SOSL", type="string"),
        FieldSpec(name="field_names", label="Field Names (comma-separated)", type="string"),
        FieldSpec(
            name="report_id",
            label="Report",
            type="string",
            remote=RemoteLookup(provider="salesforce", resource="reports"),
        ),
        FieldSpec(name="dashboard_id", label="Dashboard ID", type="string"),
        FieldSpec(name="user_id", label="User ID", type="string"),
        FieldSpec(name="apex_class", label="Apex Class Name (REST)", type="string"),
        FieldSpec(name="apex_body", label="Apex Body (JSON)", type="json", default={}),
        FieldSpec(name="limit", label="Limit", type="number", default=200, mode="advanced"),
        FieldSpec(name="records_body", label="Records (JSON array)", type="json", default=[]),
        FieldSpec(name="record_ids", label="Record IDs (JSON array)", type="json", default=[]),
        FieldSpec(name="job_id", label="Bulk Job ID", type="string"),
    ],
    operations=[
        OpSpec(
            id="query",
            label="SOQL Query",
            method="GET",
            path="/query",
            visible_fields=["soql"],
            query_builder=lambda v: {"q": getattr(v, "soql", "") or ""},
        ),
        OpSpec(
            id="create_record",
            label="Create Record",
            method="POST",
            path="/sobjects/{sobject}",
            visible_fields=["sobject", "record_data"],
            body_builder=lambda v: getattr(v, "record_data", None) or {},
        ),
        OpSpec(
            id="get_record",
            label="Get Record",
            method="GET",
            path="/sobjects/{sobject}/{record_id}",
            visible_fields=["sobject", "record_id", "field_names"],
            query_builder=lambda v: {"fields": getattr(v, "field_names", None) or None},
        ),
        OpSpec(
            id="update_record",
            label="Update Record",
            method="PATCH",
            path="/sobjects/{sobject}/{record_id}",
            visible_fields=["sobject", "record_id", "record_data"],
            body_builder=lambda v: getattr(v, "record_data", None) or {},
        ),
        OpSpec(
            id="delete_record",
            label="Delete Record",
            method="DELETE",
            path="/sobjects/{sobject}/{record_id}",
            visible_fields=["sobject", "record_id"],
        ),
        OpSpec(
            id="list_objects",
            label="List Available SObjects",
            method="GET",
            path="/sobjects",
        ),
        # ─── record + query depth ──────────────────────────────────
        OpSpec(
            id="upsert_by_external_id",
            label="Upsert Record by External ID",
            method="PATCH",
            path="/sobjects/{sobject}/{external_id_field}/{external_id_value}",
            visible_fields=["sobject", "external_id_field", "external_id_value", "record_data"],
            body_builder=lambda v: getattr(v, "record_data", None) or {},
        ),
        OpSpec(
            id="query_all",
            label="Query All (includes deleted)",
            method="GET",
            path="/queryAll",
            visible_fields=["soql"],
            query_builder=lambda v: {"q": getattr(v, "soql", "") or ""},
        ),
        OpSpec(
            id="query_more",
            label="Query More (cursor pagination)",
            method="GET",
            path="/query/{external_id_value}",
            visible_fields=["external_id_value"],
        ),
        OpSpec(
            id="search",
            label="SOSL Search",
            method="GET",
            path="/search",
            visible_fields=["search_sosl"],
            query_builder=lambda v: {"q": getattr(v, "search_sosl", "") or ""},
        ),
        OpSpec(
            id="describe_sobject",
            label="Describe SObject",
            method="GET",
            path="/sobjects/{sobject}/describe",
            visible_fields=["sobject"],
        ),
        OpSpec(
            id="sobject_basic",
            label="SObject Basic Info",
            method="GET",
            path="/sobjects/{sobject}",
            visible_fields=["sobject"],
        ),
        OpSpec(
            id="recent_records",
            label="Recently Viewed Records",
            method="GET",
            path="/sobjects/{sobject}/listviews",
            visible_fields=["sobject"],
        ),
        # ─── typed shortcuts (Lead / Contact / Opportunity / Case) ─
        OpSpec(
            id="create_lead",
            label="Create Lead",
            method="POST",
            path="/sobjects/Lead",
            visible_fields=["record_data"],
            body_builder=lambda v: getattr(v, "record_data", None) or {},
        ),
        OpSpec(
            id="create_contact",
            label="Create Contact",
            method="POST",
            path="/sobjects/Contact",
            visible_fields=["record_data"],
            body_builder=lambda v: getattr(v, "record_data", None) or {},
        ),
        OpSpec(
            id="create_account",
            label="Create Account",
            method="POST",
            path="/sobjects/Account",
            visible_fields=["record_data"],
            body_builder=lambda v: getattr(v, "record_data", None) or {},
        ),
        OpSpec(
            id="create_opportunity",
            label="Create Opportunity",
            method="POST",
            path="/sobjects/Opportunity",
            visible_fields=["record_data"],
            body_builder=lambda v: getattr(v, "record_data", None) or {},
        ),
        OpSpec(
            id="create_case",
            label="Create Case",
            method="POST",
            path="/sobjects/Case",
            visible_fields=["record_data"],
            body_builder=lambda v: getattr(v, "record_data", None) or {},
        ),
        # ─── reports + dashboards + users ─────────────────────────
        OpSpec(
            id="run_report",
            label="Run Report",
            method="GET",
            path="/analytics/reports/{report_id}",
            visible_fields=["report_id"],
        ),
        OpSpec(
            id="list_reports",
            label="List Reports",
            method="GET",
            path="/analytics/reports",
        ),
        OpSpec(
            id="get_dashboard",
            label="Get Dashboard",
            method="GET",
            path="/analytics/dashboards/{dashboard_id}",
            visible_fields=["dashboard_id"],
        ),
        OpSpec(
            id="list_dashboards",
            label="List Dashboards",
            method="GET",
            path="/analytics/dashboards",
        ),
        OpSpec(
            id="get_current_user",
            label="Get Current User",
            method="GET",
            path="/chatter/users/me",
        ),
        OpSpec(
            id="get_user",
            label="Get User",
            method="GET",
            path="/sobjects/User/{user_id}",
            visible_fields=["user_id"],
        ),
        # ─── apex REST ─────────────────────────────────────────────
        OpSpec(
            id="apex_get",
            label="Apex REST GET",
            method="GET",
            path="/apexrest/{apex_class}",
            visible_fields=["apex_class"],
        ),
        OpSpec(
            id="apex_post",
            label="Apex REST POST",
            method="POST",
            path="/apexrest/{apex_class}",
            visible_fields=["apex_class", "apex_body"],
            body_builder=lambda v: getattr(v, "apex_body", None) or {},
        ),
        OpSpec(
            id="upsert_composite",
            label="Composite Upsert (batch records)",
            method="POST",
            path="/composite/sobjects/{sobject}/{external_id_field}",
            visible_fields=["sobject", "external_id_field", "records_body"],
            body_builder=lambda v: {
                "allOrNone": False,
                "records": getattr(v, "records_body", []) or [],
            },
        ),
        OpSpec(
            id="composite_create",
            label="Composite Create (batch records)",
            method="POST",
            path="/composite/sobjects",
            visible_fields=["records_body"],
            body_builder=lambda v: {
                "allOrNone": False,
                "records": getattr(v, "records_body", []) or [],
            },
        ),
        OpSpec(
            id="composite_update",
            label="Composite Update (batch records)",
            method="PATCH",
            path="/composite/sobjects",
            visible_fields=["records_body"],
            body_builder=lambda v: {
                "allOrNone": False,
                "records": getattr(v, "records_body", []) or [],
            },
        ),
        OpSpec(
            id="composite_delete",
            label="Composite Delete (batch records)",
            method="DELETE",
            path="/composite/sobjects",
            visible_fields=["record_ids"],
            query_builder=lambda v: {"ids": ",".join(getattr(v, "record_ids", []) or [])},
        ),
        OpSpec(
            id="limits",
            label="Get Org Limits",
            method="GET",
            path="/limits",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_custom_metadata",
            label="List Custom Metadata",
            method="GET",
            path="/tooling/query",
            visible_fields=["soql"],
            query_builder=lambda v: {"q": "SELECT+DeveloperName+FROM+CustomMetadata"},
        ),
        OpSpec(
            id="versions",
            label="List API Versions",
            method="GET",
            path="/",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_resources",
            label="List Resources",
            method="GET",
            path="/",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="bulk_query",
            label="Bulk API Query (create job)",
            method="POST",
            path="/jobs/query",
            visible_fields=["soql"],
            body_builder=lambda v: {"operation": "query", "query": getattr(v, "soql", "") or ""},
        ),
        OpSpec(
            id="bulk_query_results",
            label="Bulk API Query Results",
            method="GET",
            path="/jobs/query/{job_id}/results",
            visible_fields=["job_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_bulk_job",
            label="Get Bulk API Job",
            method="GET",
            path="/jobs/query/{job_id}",
            visible_fields=["job_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="abort_bulk_job",
            label="Abort Bulk API Job",
            method="PATCH",
            path="/jobs/query/{job_id}",
            visible_fields=["job_id"],
            body_builder=lambda v: {"state": "Aborted"},
        ),
        OpSpec(
            id="create_note",
            label="Create Note",
            method="POST",
            path="/sobjects/Note",
            visible_fields=["record_data"],
            body_builder=lambda v: getattr(v, "record_data", None) or {},
        ),
        OpSpec(
            id="attach_file",
            label="Attach File (ContentDocumentLink)",
            method="POST",
            path="/sobjects/ContentDocumentLink",
            visible_fields=["record_data"],
            body_builder=lambda v: getattr(v, "record_data", None) or {},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "id", "type": "string"},
        {"label": "records", "type": "array"},
        {"label": "totalSize", "type": "number"},
    ],
    allow_error=True,
)
