"""Datadog action node — Datadog — metrics, logs, events, monitors.

REST at https://api.datadoghq.com/api/v2. See sim-parity roadmap Phase 4.20.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.datadog",
    name="Datadog",
    category="integration",
    description="Datadog — metrics, logs, events, monitors.",
    icon_slug="datadog",
    color="#ffffff",
    base_url="https://api.datadoghq.com/api/v2",
    credential_type="datadog_api_key",
    token_field=["api_key"],
    auth="header_token",
    auth_header_name="DD-API-KEY",
    extra_headers={"DD-APPLICATION-KEY": "{app_key}"},
    fields=[
        FieldSpec(name="series", label="Metric Series (JSON array)", type="json"),
        FieldSpec(name="logs", label="Log Entries (JSON array)", type="json"),
        FieldSpec(name="events", label="Events (JSON array)", type="json"),
        FieldSpec(name="identification", label="Identifications (JSON array)", type="json"),
        FieldSpec(name="title", label="Title", type="string"),
        FieldSpec(name="text", label="Text / Message", type="string"),
        FieldSpec(name="tags", label="Tags (comma-separated)", type="string"),
        FieldSpec(name="query", label="Query", type="string"),
        FieldSpec(name="nrql", label="NRQL Query", type="string"),
        FieldSpec(name="account_id", label="Account ID", type="string"),
        FieldSpec(name="chart_id", label="Chart ID", type="string"),
        FieldSpec(name="dashboard_id", label="Dashboard ID (numeric)", type="string"),
        FieldSpec(name="dashboard_uid", label="Dashboard UID", type="string"),
        FieldSpec(name="name", label="Name", type="string"),
        FieldSpec(name="run_type", label="Run Type (chain/llm/tool)", type="string"),
        FieldSpec(name="inputs", label="Inputs (JSON)", type="json"),
        FieldSpec(name="project_name", label="Project / Session Name", type="string"),
        FieldSpec(name="project_id", label="Project ID", type="string"),
        FieldSpec(name="run_id", label="Run ID", type="string"),
        FieldSpec(name="key", label="Feedback Key", type="string"),
        FieldSpec(name="score", label="Score (float)", type="number"),
        FieldSpec(name="value", label="Value", type="string"),
        FieldSpec(name="input_params", label="Input Params (JSON)", type="json"),
        FieldSpec(name="dry_run", label="Dry Run (true/false)", type="string", mode="advanced"),
        FieldSpec(name="limit", label="Limit", type="number", default=25, mode="advanced"),
        FieldSpec(name="dd_metrics_body", label="Metrics Body (JSON)", type="json", default={}),
        FieldSpec(name="dd_query", label="Metrics Query", type="string"),
        FieldSpec(name="dd_from", label="From (unix)", type="number", default=0),
        FieldSpec(name="dd_to", label="To (unix)", type="number", default=0),
        FieldSpec(name="dd_event_body", label="Event Body (JSON)", type="json", default={}),
        FieldSpec(name="dd_monitor_body", label="Monitor Body (JSON)", type="json", default={}),
        FieldSpec(name="dd_monitor_id", label="Monitor ID", type="string"),
        FieldSpec(name="dd_logs_body", label="Logs Body (JSON)", type="json", default={}),
        FieldSpec(name="dd_downtime_body", label="Downtime Body (JSON)", type="json", default={}),
        FieldSpec(name="dd_downtime_id", label="Downtime ID", type="string"),
    ],
    operations=[
        OpSpec(
            id="submit_logs",
            label="Submit Logs",
            method="POST",
            path="/logs",
            visible_fields=["logs"],
            body_builder=lambda v: getattr(v, "logs", None) or [],
        ),
        OpSpec(
            id="submit_event",
            label="Submit Event",
            method="POST",
            path="/events",
            visible_fields=["title", "text", "tags"],
            body_builder=lambda v: {
                "data": {
                    "type": "event",
                    "attributes": {
                        "title": getattr(v, "title", "") or "",
                        "text": getattr(v, "text", "") or "",
                        "tags": [
                            t.strip()
                            for t in (getattr(v, "tags", "") or "").split(",")
                            if t.strip()
                        ],
                    },
                }
            },
        ),
        OpSpec(
            id="submit_metrics",
            label="Submit Metrics",
            method="POST",
            path="/api/v2/series",
            visible_fields=["dd_metrics_body"],
            body_builder=lambda v: getattr(v, "dd_metrics_body", None) or {},
        ),
        OpSpec(
            id="query_timeseries",
            label="Query Timeseries",
            method="GET",
            path="/api/v1/query",
            visible_fields=["dd_query", "dd_from", "dd_to"],
            query_builder=lambda v: {
                "query": getattr(v, "dd_query", "") or "",
                "from": int(getattr(v, "dd_from", 0) or 0),
                "to": int(getattr(v, "dd_to", 0) or 0),
            },
        ),
        OpSpec(
            id="create_event",
            label="Create Event",
            method="POST",
            path="/api/v1/events",
            visible_fields=["dd_event_body"],
            body_builder=lambda v: getattr(v, "dd_event_body", None) or {},
        ),
        OpSpec(
            id="create_monitor",
            label="Create Monitor",
            method="POST",
            path="/api/v1/monitor",
            visible_fields=["dd_monitor_body"],
            body_builder=lambda v: getattr(v, "dd_monitor_body", None) or {},
        ),
        OpSpec(
            id="get_monitor",
            label="Get Monitor",
            method="GET",
            path="/api/v1/monitor/{dd_monitor_id}",
            visible_fields=["dd_monitor_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_monitors",
            label="List Monitors",
            method="GET",
            path="/api/v1/monitor",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="mute_monitor",
            label="Mute Monitor",
            method="POST",
            path="/api/v1/monitor/{dd_monitor_id}/mute",
            visible_fields=["dd_monitor_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="query_logs",
            label="Query Logs",
            method="POST",
            path="/api/v2/logs/events/search",
            visible_fields=["dd_logs_body"],
            body_builder=lambda v: getattr(v, "dd_logs_body", None) or {},
        ),
        OpSpec(
            id="send_logs",
            label="Send Logs",
            method="POST",
            path="https://http-intake.logs.datadoghq.com/api/v2/logs",
            visible_fields=["dd_logs_body"],
            body_builder=lambda v: getattr(v, "dd_logs_body", None) or {},
        ),
        OpSpec(
            id="create_downtime",
            label="Create Downtime",
            method="POST",
            path="/api/v1/downtime",
            visible_fields=["dd_downtime_body"],
            body_builder=lambda v: getattr(v, "dd_downtime_body", None) or {},
        ),
        OpSpec(
            id="list_downtimes",
            label="List Downtimes",
            method="GET",
            path="/api/v1/downtime",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="cancel_downtime",
            label="Cancel Downtime",
            method="DELETE",
            path="/api/v1/downtime/{dd_downtime_id}",
            visible_fields=["dd_downtime_id"],
            query_builder=lambda v: {},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "status", "type": "string"},
    ],
    allow_error=True,
)
