"""Intercom action node — manifest form.

Intercom v2 REST API. Bearer auth + a pinned `Intercom-Version`
header (we default to `2.13`). Eight ops cover the typical workflow
use: contacts CRUD, message send, conversation reply, segment list.
"""

from __future__ import annotations

from apps.api.app.node_system.nodes.intercom import COLOR, ICON_SLUG, NAME
from apps.api.app.node_system.scaffolds import (
    FieldSpec,
    OpSpec,
    ProviderManifest,
)

MANIFEST = ProviderManifest(
    type="action.intercom",
    name=NAME,
    category="integration",
    description="Intercom — manage contacts, conversations, and messages.",
    icon_slug=ICON_SLUG,
    color=COLOR,
    base_url="https://api.intercom.io",
    credential_type="intercom_api_key",
    token_field=["api_key"],
    auth="bearer",
    extra_headers={"Intercom-Version": "2.13"},
    fields=[
        FieldSpec(name="contact_id", label="Contact ID", type="string"),
        FieldSpec(name="external_id", label="External ID", type="string", mode="advanced"),
        FieldSpec(name="email", label="Email", type="string"),
        FieldSpec(name="name", label="Name", type="string"),
        FieldSpec(name="phone", label="Phone", type="string", mode="advanced"),
        FieldSpec(
            name="role",
            label="Role",
            type="options",
            mode="advanced",
            options=[
                {"label": "User", "value": "user"},
                {"label": "Lead", "value": "lead"},
            ],
        ),
        FieldSpec(
            name="custom_attributes", label="Custom Attributes (JSON)", type="json", mode="advanced"
        ),
        FieldSpec(name="conversation_id", label="Conversation ID", type="string"),
        FieldSpec(
            name="message_type",
            label="Message Type",
            type="options",
            default="comment",
            options=[
                {"label": "Comment", "value": "comment"},
                {"label": "Note", "value": "note"},
            ],
        ),
        FieldSpec(name="body", label="Body", type="string"),
        FieldSpec(name="admin_id", label="Admin ID (sender)", type="string"),
        FieldSpec(name="from_email", label="From email", type="string", mode="advanced"),
        FieldSpec(name="subject", label="Subject", type="string", mode="advanced"),
        FieldSpec(name="query", label="Search Query (JSON)", type="json", mode="advanced"),
        FieldSpec(name="limit", label="Per page", type="number", default=50, mode="advanced"),
        FieldSpec(name="company_id", label="Company ID", type="string"),
        FieldSpec(name="company_name", label="Company Name", type="string"),
        FieldSpec(name="plan", label="Plan", type="string"),
        FieldSpec(name="ticket_id", label="Ticket ID", type="string"),
        FieldSpec(name="ticket_type_id", label="Ticket Type ID", type="string"),
        FieldSpec(name="assignee_id", label="Assignee ID", type="string"),
        FieldSpec(name="tag_id", label="Tag ID", type="string"),
        FieldSpec(name="tag_name", label="Tag Name", type="string"),
        FieldSpec(name="event_name", label="Event Name", type="string"),
        FieldSpec(name="event_metadata", label="Event Metadata (JSON)", type="json", default={}),
        FieldSpec(name="created_at", label="Created At (unix)", type="number", default=0),
        FieldSpec(name="snoozed_until", label="Snoozed Until (unix)", type="number", default=0),
        FieldSpec(name="state", label="State", type="string"),
    ],
    operations=[
        OpSpec(
            id="create_contact",
            label="Create Contact",
            method="POST",
            path="/contacts",
            visible_fields=["role", "email", "name", "external_id", "phone", "custom_attributes"],
            body_builder=lambda v: {
                k: val
                for k, val in {
                    "role": getattr(v, "role", None) or "user",
                    "email": getattr(v, "email", None),
                    "name": getattr(v, "name", None),
                    "external_id": getattr(v, "external_id", None),
                    "phone": getattr(v, "phone", None),
                    "custom_attributes": getattr(v, "custom_attributes", None),
                }.items()
                if val is not None
            },
        ),
        OpSpec(
            id="get_contact",
            label="Get Contact",
            method="GET",
            path="/contacts/{contact_id}",
            visible_fields=["contact_id"],
        ),
        OpSpec(
            id="update_contact",
            label="Update Contact",
            method="PUT",
            path="/contacts/{contact_id}",
            visible_fields=["contact_id", "email", "name", "phone", "custom_attributes"],
            body_builder=lambda v: {
                k: val
                for k, val in {
                    "email": getattr(v, "email", None),
                    "name": getattr(v, "name", None),
                    "phone": getattr(v, "phone", None),
                    "custom_attributes": getattr(v, "custom_attributes", None),
                }.items()
                if val is not None
            },
        ),
        OpSpec(
            id="search_contacts",
            label="Search Contacts",
            method="POST",
            path="/contacts/search",
            visible_fields=["query"],
            body_builder=lambda v: {"query": getattr(v, "query", None) or {}},
        ),
        OpSpec(
            id="list_contacts",
            label="List Contacts",
            method="GET",
            path="/contacts",
            visible_fields=["limit"],
            query_builder=lambda v: {"per_page": int(getattr(v, "limit", 50) or 50)},
        ),
        OpSpec(
            id="send_message",
            label="Send Message",
            method="POST",
            path="/messages",
            visible_fields=["from_email", "subject", "body", "email", "admin_id"],
            body_builder=lambda v: {
                "message_type": "email",
                "subject": getattr(v, "subject", None) or "",
                "body": getattr(v, "body", None) or "",
                "from": {"type": "admin", "id": getattr(v, "admin_id", None)},
                "to": {"type": "user", "email": getattr(v, "email", None)},
            },
        ),
        OpSpec(
            id="reply_conversation",
            label="Reply to Conversation",
            method="POST",
            path="/conversations/{conversation_id}/reply",
            visible_fields=["conversation_id", "message_type", "body", "admin_id"],
            body_builder=lambda v: {
                "message_type": getattr(v, "message_type", None) or "comment",
                "type": "admin",
                "admin_id": getattr(v, "admin_id", None),
                "body": getattr(v, "body", None) or "",
            },
        ),
        OpSpec(
            id="list_segments",
            label="List Segments",
            method="GET",
            path="/segments",
        ),
        OpSpec(
            id="delete_contact",
            label="Delete Contact",
            method="DELETE",
            path="/contacts/{contact_id}",
            visible_fields=["contact_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_company",
            label="Create Company",
            method="POST",
            path="/companies",
            visible_fields=["company_id", "name", "plan"],
            body_builder=lambda v: {
                "company_id": getattr(v, "company_id", "") or "",
                "name": getattr(v, "company_name", None) or None,
                "plan": getattr(v, "plan", None) or None,
            },
        ),
        OpSpec(
            id="get_company",
            label="Get Company",
            method="GET",
            path="/companies/{company_id}",
            visible_fields=["company_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_companies",
            label="List Companies",
            method="GET",
            path="/companies",
            visible_fields=["limit"],
            query_builder=lambda v: {"per_page": int(getattr(v, "limit", 20) or 20)},
        ),
        OpSpec(
            id="attach_contact_to_company",
            label="Attach Contact to Company",
            method="POST",
            path="/contacts/{contact_id}/companies",
            visible_fields=["contact_id", "company_id"],
            body_builder=lambda v: {"id": getattr(v, "company_id", "") or ""},
        ),
        OpSpec(
            id="detach_contact_from_company",
            label="Detach Contact from Company",
            method="DELETE",
            path="/contacts/{contact_id}/companies/{company_id}",
            visible_fields=["contact_id", "company_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="search_conversations",
            label="Search Conversations",
            method="POST",
            path="/conversations/search",
            visible_fields=["query"],
            body_builder=lambda v: {"query": getattr(v, "query", None) or {}},
        ),
        OpSpec(
            id="get_conversation",
            label="Get Conversation",
            method="GET",
            path="/conversations/{conversation_id}",
            visible_fields=["conversation_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_conversations",
            label="List Conversations",
            method="GET",
            path="/conversations",
            visible_fields=["limit"],
            query_builder=lambda v: {"per_page": int(getattr(v, "limit", 20) or 20)},
        ),
        OpSpec(
            id="close_conversation",
            label="Close Conversation",
            method="POST",
            path="/conversations/{conversation_id}/parts",
            visible_fields=["conversation_id", "admin_id"],
            body_builder=lambda v: {
                "message_type": "close",
                "type": "admin",
                "admin_id": getattr(v, "admin_id", "") or "",
            },
        ),
        OpSpec(
            id="open_conversation",
            label="Reopen Conversation",
            method="POST",
            path="/conversations/{conversation_id}/parts",
            visible_fields=["conversation_id", "admin_id"],
            body_builder=lambda v: {
                "message_type": "open",
                "type": "admin",
                "admin_id": getattr(v, "admin_id", "") or "",
            },
        ),
        OpSpec(
            id="snooze_conversation",
            label="Snooze Conversation",
            method="POST",
            path="/conversations/{conversation_id}/parts",
            visible_fields=["conversation_id", "admin_id", "snoozed_until"],
            body_builder=lambda v: {
                "message_type": "snoozed",
                "type": "admin",
                "admin_id": getattr(v, "admin_id", "") or "",
                "snoozed_until": int(getattr(v, "snoozed_until", 0) or 0),
            },
        ),
        OpSpec(
            id="assign_conversation",
            label="Assign Conversation",
            method="POST",
            path="/conversations/{conversation_id}/parts",
            visible_fields=["conversation_id", "admin_id", "assignee_id"],
            body_builder=lambda v: {
                "message_type": "assignment",
                "type": "admin",
                "admin_id": getattr(v, "admin_id", "") or "",
                "assignee_id": getattr(v, "assignee_id", "") or "",
            },
        ),
        OpSpec(
            id="create_ticket",
            label="Create Ticket",
            method="POST",
            path="/tickets",
            visible_fields=["ticket_type_id", "contact_id"],
            body_builder=lambda v: {
                "ticket_type_id": getattr(v, "ticket_type_id", "") or "",
                "contacts": [{"id": getattr(v, "contact_id", "") or ""}],
            },
        ),
        OpSpec(
            id="get_ticket",
            label="Get Ticket",
            method="GET",
            path="/tickets/{ticket_id}",
            visible_fields=["ticket_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="update_ticket",
            label="Update Ticket",
            method="PUT",
            path="/tickets/{ticket_id}",
            visible_fields=["ticket_id", "state"],
            body_builder=lambda v: {"state": getattr(v, "state", "") or ""},
        ),
        OpSpec(
            id="list_admins",
            label="List Admins",
            method="GET",
            path="/admins",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_tags",
            label="List Tags",
            method="GET",
            path="/tags",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_tag",
            label="Create Tag",
            method="POST",
            path="/tags",
            visible_fields=["tag_name"],
            body_builder=lambda v: {"name": getattr(v, "tag_name", "") or ""},
        ),
        OpSpec(
            id="tag_contact",
            label="Tag Contact",
            method="POST",
            path="/contacts/{contact_id}/tags",
            visible_fields=["contact_id", "tag_id"],
            body_builder=lambda v: {"id": getattr(v, "tag_id", "") or ""},
        ),
        OpSpec(
            id="untag_contact",
            label="Untag Contact",
            method="DELETE",
            path="/contacts/{contact_id}/tags/{tag_id}",
            visible_fields=["contact_id", "tag_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="tag_conversation",
            label="Tag Conversation",
            method="POST",
            path="/conversations/{conversation_id}/tags",
            visible_fields=["conversation_id", "tag_id", "admin_id"],
            body_builder=lambda v: {
                "id": getattr(v, "tag_id", "") or "",
                "admin_id": getattr(v, "admin_id", "") or "",
            },
        ),
        OpSpec(
            id="create_event",
            label="Create Event",
            method="POST",
            path="/events",
            visible_fields=["contact_id", "event_name", "event_metadata", "created_at"],
            body_builder=lambda v: {
                "event_name": getattr(v, "event_name", "") or "",
                "created_at": int(getattr(v, "created_at", 0) or 0),
                "user_id": getattr(v, "contact_id", "") or "",
                "metadata": getattr(v, "event_metadata", None) or None,
            },
        ),
    ],
    outputs_schema=[
        {"label": "id", "type": "string"},
        {"label": "type", "type": "string"},
        {"label": "email", "type": "string"},
        {"label": "name", "type": "string"},
        {"label": "data", "type": "array"},
        {"label": "segments", "type": "array"},
        {"label": "total_count", "type": "number"},
    ],
    allow_error=True,
)
