"""Grafana Cloud action node — Grafana Cloud — dashboards, alerts, annotations, folders.

REST at https://{stack}.grafana.net/api. See sim-parity roadmap Phase 4.20.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.grafana",
    name="Grafana Cloud",
    category="integration",
    description="Grafana Cloud — dashboards, alerts, annotations, folders.",
    icon_slug="grafana",
    color="#ffffff",
    base_url="https://{stack}.grafana.net/api",
    credential_type="grafana_api_key",
    token_field=["api_key"],
    auth="bearer",
    fields=[
        FieldSpec(name="series", label="Metric Series (JSON array)", type="json"),
        FieldSpec(name="logs", label="Log Entries (JSON array)", type="json"),
        FieldSpec(name="events", label="Events (JSON array)", type="json"),
        FieldSpec(name="identification", label="Identifications (JSON array)", type="json"),
        FieldSpec(name="title", label="Title", type="string"),
        FieldSpec(name="text", label="Text / Message", type="string"),
        FieldSpec(name="tags", label="Tags (comma-separated)", type="string"),
        FieldSpec(name="query", label="Query", type="string"),
        FieldSpec(name="nrql", label="NRQL Query", type="string"),
        FieldSpec(name="account_id", label="Account ID", type="string"),
        FieldSpec(name="chart_id", label="Chart ID", type="string"),
        FieldSpec(name="dashboard_id", label="Dashboard ID (numeric)", type="string"),
        FieldSpec(name="dashboard_uid", label="Dashboard UID", type="string"),
        FieldSpec(name="name", label="Name", type="string"),
        FieldSpec(name="run_type", label="Run Type (chain/llm/tool)", type="string"),
        FieldSpec(name="inputs", label="Inputs (JSON)", type="json"),
        FieldSpec(name="project_name", label="Project / Session Name", type="string"),
        FieldSpec(name="project_id", label="Project ID", type="string"),
        FieldSpec(name="run_id", label="Run ID", type="string"),
        FieldSpec(name="key", label="Feedback Key", type="string"),
        FieldSpec(name="score", label="Score (float)", type="number"),
        FieldSpec(name="value", label="Value", type="string"),
        FieldSpec(name="input_params", label="Input Params (JSON)", type="json"),
        FieldSpec(name="dry_run", label="Dry Run (true/false)", type="string", mode="advanced"),
        FieldSpec(name="limit", label="Limit", type="number", default=25, mode="advanced"),
        FieldSpec(name="dashboard_query", label="Search Query", type="string"),
        FieldSpec(name="dashboard_body", label="Dashboard Body (JSON)", type="json", default={}),
        FieldSpec(name="alert_rule_uid", label="Alert Rule UID", type="string"),
        FieldSpec(name="alert_rule_body", label="Alert Rule Body (JSON)", type="json", default={}),
        FieldSpec(
            name="contact_point_body", label="Contact Point Body (JSON)", type="json", default={}
        ),
        FieldSpec(name="annotation_id", label="Annotation ID", type="string"),
        FieldSpec(name="annotation_body", label="Annotation Body (JSON)", type="json", default={}),
        FieldSpec(name="datasource_id", label="Datasource ID", type="string"),
        FieldSpec(name="datasource_uid", label="Datasource UID", type="string"),
        FieldSpec(name="folder_uid", label="Folder UID", type="string"),
        FieldSpec(name="folder_body", label="Folder Body (JSON)", type="json", default={}),
    ],
    operations=[
        OpSpec(
            id="list_dashboards",
            label="List Dashboards",
            method="GET",
            path="/search",
            visible_fields=["query"],
            query_builder=lambda v: {
                k: val
                for k, val in {
                    "query": getattr(v, "query", None) or None,
                    "type": "dash-db",
                }.items()
                if val is not None
            },
        ),
        OpSpec(
            id="get_dashboard",
            label="Get Dashboard",
            method="GET",
            path="/dashboards/uid/{dashboard_uid}",
            visible_fields=["dashboard_uid"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_annotation",
            label="Create Annotation",
            method="POST",
            path="/annotations",
            visible_fields=["dashboard_id", "text", "tags"],
            body_builder=lambda v: {
                k: val
                for k, val in {
                    "dashboardId": int(getattr(v, "dashboard_id", 0) or 0) or None,
                    "text": getattr(v, "text", None) or None,
                    "tags": [
                        t.strip() for t in (getattr(v, "tags", "") or "").split(",") if t.strip()
                    ]
                    or None,
                }.items()
                if val is not None
            },
        ),
        OpSpec(
            id="list_alerts",
            label="List Alert Rules",
            method="GET",
            path="/v1/provisioning/alert-rules",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_dashboard",
            label="Create/Update Dashboard",
            method="POST",
            path="/api/dashboards/db",
            visible_fields=["dashboard_body"],
            body_builder=lambda v: getattr(v, "dashboard_body", None) or {},
        ),
        OpSpec(
            id="update_dashboard",
            label="Update Dashboard",
            method="POST",
            path="/api/dashboards/db",
            visible_fields=["dashboard_body"],
            body_builder=lambda v: getattr(v, "dashboard_body", None) or {},
        ),
        OpSpec(
            id="delete_dashboard",
            label="Delete Dashboard",
            method="DELETE",
            path="/api/dashboards/uid/{dashboard_uid}",
            visible_fields=["dashboard_uid"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_alert_rules",
            label="List Alert Rules",
            method="GET",
            path="/api/v1/provisioning/alert-rules",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_alert_rule",
            label="Get Alert Rule",
            method="GET",
            path="/api/v1/provisioning/alert-rules/{alert_rule_uid}",
            visible_fields=["alert_rule_uid"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_alert_rule",
            label="Create Alert Rule",
            method="POST",
            path="/api/v1/provisioning/alert-rules",
            visible_fields=["alert_rule_body"],
            body_builder=lambda v: getattr(v, "alert_rule_body", None) or {},
        ),
        OpSpec(
            id="update_alert_rule",
            label="Update Alert Rule",
            method="PUT",
            path="/api/v1/provisioning/alert-rules/{alert_rule_uid}",
            visible_fields=["alert_rule_uid", "alert_rule_body"],
            body_builder=lambda v: getattr(v, "alert_rule_body", None) or {},
        ),
        OpSpec(
            id="delete_alert_rule",
            label="Delete Alert Rule",
            method="DELETE",
            path="/api/v1/provisioning/alert-rules/{alert_rule_uid}",
            visible_fields=["alert_rule_uid"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_contact_points",
            label="List Contact Points",
            method="GET",
            path="/api/v1/provisioning/contact-points",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_contact_point",
            label="Create Contact Point",
            method="POST",
            path="/api/v1/provisioning/contact-points",
            visible_fields=["contact_point_body"],
            body_builder=lambda v: getattr(v, "contact_point_body", None) or {},
        ),
        OpSpec(
            id="list_annotations",
            label="List Annotations",
            method="GET",
            path="/api/annotations",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="update_annotation",
            label="Update Annotation",
            method="PUT",
            path="/api/annotations/{annotation_id}",
            visible_fields=["annotation_id", "annotation_body"],
            body_builder=lambda v: getattr(v, "annotation_body", None) or {},
        ),
        OpSpec(
            id="delete_annotation",
            label="Delete Annotation",
            method="DELETE",
            path="/api/annotations/{annotation_id}",
            visible_fields=["annotation_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_data_sources",
            label="List Data Sources",
            method="GET",
            path="/api/datasources",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_data_source",
            label="Get Data Source",
            method="GET",
            path="/api/datasources/{datasource_id}",
            visible_fields=["datasource_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="check_data_source_health",
            label="Check Data Source Health",
            method="GET",
            path="/api/datasources/uid/{datasource_uid}/health",
            visible_fields=["datasource_uid"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_folders",
            label="List Folders",
            method="GET",
            path="/api/folders",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_folder",
            label="Create Folder",
            method="POST",
            path="/api/folders",
            visible_fields=["folder_body"],
            body_builder=lambda v: getattr(v, "folder_body", None) or {},
        ),
        OpSpec(
            id="get_folder",
            label="Get Folder",
            method="GET",
            path="/api/folders/{folder_uid}",
            visible_fields=["folder_uid"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="update_folder",
            label="Update Folder",
            method="PUT",
            path="/api/folders/{folder_uid}",
            visible_fields=["folder_uid", "folder_body"],
            body_builder=lambda v: getattr(v, "folder_body", None) or {},
        ),
        OpSpec(
            id="delete_folder",
            label="Delete Folder",
            method="DELETE",
            path="/api/folders/{folder_uid}",
            visible_fields=["folder_uid"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_health",
            label="Get Grafana Health",
            method="GET",
            path="/api/health",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "status", "type": "string"},
    ],
    allow_error=True,
)
