"""Context action node — Context — LLM answer analytics + user feedback.

REST at https://api.getcontext.dev/v1. See sim-parity roadmap Phase 4.18/4.19.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.context_dev",
    name="Context",
    category="integration",
    description="Context — LLM answer analytics + user feedback.",
    icon_slug="context_dev",
    color="#ffffff",
    base_url="https://api.getcontext.dev/v1",
    credential_type="context_dev_api_key",
    token_field=["api_key"],
    auth="bearer",
    fields=[
        FieldSpec(name="inbox_id", label="Inbox ID", type="string"),
        FieldSpec(name="message_id", label="Message ID", type="string"),
        FieldSpec(
            name="to", label="To (comma-separated for email; phone number for call)", type="string"
        ),
        FieldSpec(name="from_", label="From", type="string"),
        FieldSpec(name="subject", label="Subject", type="string"),
        FieldSpec(name="text", label="Text / Message Body", type="string"),
        FieldSpec(name="username", label="Username", type="string"),
        FieldSpec(name="domain", label="Domain", type="string"),
        FieldSpec(name="assistant_id", label="Assistant ID", type="string"),
        FieldSpec(name="prompt", label="Prompt", type="string"),
        FieldSpec(name="call_id", label="Call ID", type="string"),
        FieldSpec(name="agent_id", label="Agent ID", type="string"),
        FieldSpec(name="session_id", label="Session ID", type="string"),
        FieldSpec(name="repo", label="Repo (owner/name)", type="string"),
        FieldSpec(name="model", label="Model", type="string"),
        FieldSpec(name="playbook_id", label="Playbook ID", type="string"),
        FieldSpec(name="conversation_id", label="Conversation ID", type="string"),
        FieldSpec(name="messages", label="Messages (JSON array)", type="json"),
        FieldSpec(name="metadata", label="Metadata (JSON)", type="json"),
        FieldSpec(name="start_date", label="Start Date", type="string"),
        FieldSpec(name="end_date", label="End Date", type="string"),
        FieldSpec(name="url", label="URL", type="string"),
        FieldSpec(name="file_id", label="File ID", type="string"),
        FieldSpec(name="query", label="Query", type="string"),
        FieldSpec(name="input", label="Input(s) (pipe-separated)", type="string"),
        FieldSpec(name="documents", label="Documents (JSON array)", type="json"),
        FieldSpec(name="config", label="Config (JSON)", type="json"),
        FieldSpec(name="job_id", label="Job ID", type="string"),
        FieldSpec(name="project_id", label="Project ID", type="string"),
        FieldSpec(name="dataset_id", label="Dataset ID", type="string"),
        FieldSpec(name="snapshot_id", label="Snapshot ID", type="string"),
        FieldSpec(name="program_id", label="Program ID", type="string"),
        FieldSpec(name="inputs", label="Inputs (JSON)", type="json"),
        FieldSpec(name="limit", label="Limit", type="number", default=25, mode="advanced"),
        FieldSpec(name="crawl_options", label="Crawl Options (JSON)", type="json", default={}),
        FieldSpec(name="extract_schema", label="Extract Schema (JSON)", type="json", default={}),
        FieldSpec(name="urls", label="URLs (JSON array)", type="json", default=[]),
        FieldSpec(name="name", label="Name", type="string"),
        FieldSpec(name="email", label="Email", type="string"),
        FieldSpec(name="ticker", label="Ticker", type="string"),
        FieldSpec(
            name="transaction_body", label="Transaction Body (JSON)", type="json", default={}
        ),
    ],
    operations=[
        OpSpec(
            id="log_conversation",
            label="Log Conversation",
            method="POST",
            path="/pipelines/log",
            visible_fields=["conversation_id", "messages", "metadata"],
            body_builder=lambda v: {
                k: val
                for k, val in {
                    "conversation_id": getattr(v, "conversation_id", None) or None,
                    "messages": getattr(v, "messages", None) or None,
                    "metadata": getattr(v, "metadata", None) or None,
                }.items()
                if val is not None
            },
        ),
        OpSpec(
            id="get_analytics",
            label="Get Analytics",
            method="GET",
            path="/analytics/topics",
            visible_fields=["start_date", "end_date"],
            query_builder=lambda v: {
                k: val
                for k, val in {
                    "start_date": getattr(v, "start_date", None) or None,
                    "end_date": getattr(v, "end_date", None) or None,
                }.items()
                if val is not None
            },
        ),
        OpSpec(
            id="scrape_markdown",
            label="Scrape URL as Markdown",
            method="GET",
            path="/scrape/markdown",
            visible_fields=["url"],
            query_builder=lambda v: {"url": getattr(v, "url", "") or ""},
        ),
        OpSpec(
            id="scrape_html",
            label="Scrape URL as HTML",
            method="GET",
            path="/scrape/html",
            visible_fields=["url"],
            query_builder=lambda v: {"url": getattr(v, "url", "") or ""},
        ),
        OpSpec(
            id="scrape_images",
            label="Scrape URL Images",
            method="GET",
            path="/scrape/images",
            visible_fields=["url"],
            query_builder=lambda v: {"url": getattr(v, "url", "") or ""},
        ),
        OpSpec(
            id="screenshot",
            label="URL Screenshot",
            method="GET",
            path="/screenshot",
            visible_fields=["url"],
            query_builder=lambda v: {"url": getattr(v, "url", "") or ""},
        ),
        OpSpec(
            id="crawl",
            label="Crawl URL",
            method="POST",
            path="/crawl",
            visible_fields=["url", "crawl_options"],
            body_builder=lambda v: {
                "url": getattr(v, "url", "") or "",
                "options": getattr(v, "crawl_options", None) or {},
            },
        ),
        OpSpec(
            id="map",
            label="Map URL (list links)",
            method="GET",
            path="/map",
            visible_fields=["url"],
            query_builder=lambda v: {"url": getattr(v, "url", "") or ""},
        ),
        OpSpec(
            id="search",
            label="Search Web",
            method="GET",
            path="/search",
            visible_fields=["query"],
            query_builder=lambda v: {"q": getattr(v, "query", "") or ""},
        ),
        OpSpec(
            id="extract",
            label="Extract Structured Data",
            method="POST",
            path="/extract",
            visible_fields=["url", "extract_schema"],
            body_builder=lambda v: {
                "url": getattr(v, "url", "") or "",
                "schema": getattr(v, "extract_schema", None) or {},
            },
        ),
        OpSpec(
            id="extract_product",
            label="Extract Product Data",
            method="POST",
            path="/extract/product",
            visible_fields=["url"],
            body_builder=lambda v: {"url": getattr(v, "url", "") or ""},
        ),
        OpSpec(
            id="extract_products",
            label="Extract Multiple Products",
            method="POST",
            path="/extract/products",
            visible_fields=["urls"],
            body_builder=lambda v: {"urls": getattr(v, "urls", []) or []},
        ),
        OpSpec(
            id="scrape_fonts",
            label="Scrape Fonts",
            method="GET",
            path="/scrape/fonts",
            visible_fields=["url"],
            query_builder=lambda v: {"url": getattr(v, "url", "") or ""},
        ),
        OpSpec(
            id="scrape_styleguide",
            label="Scrape Style Guide",
            method="GET",
            path="/scrape/styleguide",
            visible_fields=["url"],
            query_builder=lambda v: {"url": getattr(v, "url", "") or ""},
        ),
        OpSpec(
            id="classify_naics",
            label="Classify NAICS",
            method="GET",
            path="/classify/naics",
            visible_fields=["query"],
            query_builder=lambda v: {"query": getattr(v, "query", "") or ""},
        ),
        OpSpec(
            id="classify_sic",
            label="Classify SIC",
            method="GET",
            path="/classify/sic",
            visible_fields=["query"],
            query_builder=lambda v: {"query": getattr(v, "query", "") or ""},
        ),
        OpSpec(
            id="get_brand",
            label="Get Brand by Domain",
            method="GET",
            path="/brand",
            visible_fields=["domain"],
            query_builder=lambda v: {"domain": getattr(v, "domain", "") or ""},
        ),
        OpSpec(
            id="get_brand_by_name",
            label="Get Brand by Name",
            method="GET",
            path="/brand/name",
            visible_fields=["name"],
            query_builder=lambda v: {"name": getattr(v, "name", "") or ""},
        ),
        OpSpec(
            id="get_brand_by_email",
            label="Get Brand by Email",
            method="GET",
            path="/brand/email",
            visible_fields=["email"],
            query_builder=lambda v: {"email": getattr(v, "email", "") or ""},
        ),
        OpSpec(
            id="get_brand_by_ticker",
            label="Get Brand by Ticker",
            method="GET",
            path="/brand/ticker",
            visible_fields=["ticker"],
            query_builder=lambda v: {"ticker": getattr(v, "ticker", "") or ""},
        ),
        OpSpec(
            id="get_brand_simplified",
            label="Get Brand (simplified)",
            method="GET",
            path="/brand/simplified",
            visible_fields=["domain"],
            query_builder=lambda v: {"domain": getattr(v, "domain", "") or ""},
        ),
        OpSpec(
            id="identify_transaction",
            label="Identify Transaction",
            method="POST",
            path="/transactions/identify",
            visible_fields=["transaction_body"],
            body_builder=lambda v: getattr(v, "transaction_body", None) or {},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "id", "type": "string"},
        {"label": "status", "type": "string"},
    ],
    allow_error=True,
)
