"""AgentPhone action node — AgentPhone — AI voice agent (make/receive calls).

REST at https://api.agentphone.ai/v1. See sim-parity roadmap Phase 4.18/4.19.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.agentphone",
    name="AgentPhone",
    category="integration",
    description="AgentPhone — AI voice agent (make/receive calls).",
    icon_slug="agentphone",
    color="#1c1c1c",
    base_url="https://api.agentphone.ai/v1",
    credential_type="agentphone_api_key",
    token_field=["api_key"],
    auth="bearer",
    fields=[
        FieldSpec(name="inbox_id", label="Inbox ID", type="string"),
        FieldSpec(name="message_id", label="Message ID", type="string"),
        FieldSpec(
            name="to", label="To (comma-separated for email; phone number for call)", type="string"
        ),
        FieldSpec(name="from_", label="From", type="string"),
        FieldSpec(name="subject", label="Subject", type="string"),
        FieldSpec(name="text", label="Text / Message Body", type="string"),
        FieldSpec(name="username", label="Username", type="string"),
        FieldSpec(name="domain", label="Domain", type="string"),
        FieldSpec(name="assistant_id", label="Assistant ID", type="string"),
        FieldSpec(name="prompt", label="Prompt", type="string"),
        FieldSpec(name="call_id", label="Call ID", type="string"),
        FieldSpec(name="agent_id", label="Agent ID", type="string"),
        FieldSpec(name="session_id", label="Session ID", type="string"),
        FieldSpec(name="repo", label="Repo (owner/name)", type="string"),
        FieldSpec(name="model", label="Model", type="string"),
        FieldSpec(name="playbook_id", label="Playbook ID", type="string"),
        FieldSpec(name="conversation_id", label="Conversation ID", type="string"),
        FieldSpec(name="messages", label="Messages (JSON array)", type="json"),
        FieldSpec(name="metadata", label="Metadata (JSON)", type="json"),
        FieldSpec(name="start_date", label="Start Date", type="string"),
        FieldSpec(name="end_date", label="End Date", type="string"),
        FieldSpec(name="url", label="URL", type="string"),
        FieldSpec(name="file_id", label="File ID", type="string"),
        FieldSpec(name="query", label="Query", type="string"),
        FieldSpec(name="input", label="Input(s) (pipe-separated)", type="string"),
        FieldSpec(name="documents", label="Documents (JSON array)", type="json"),
        FieldSpec(name="config", label="Config (JSON)", type="json"),
        FieldSpec(name="job_id", label="Job ID", type="string"),
        FieldSpec(name="project_id", label="Project ID", type="string"),
        FieldSpec(name="dataset_id", label="Dataset ID", type="string"),
        FieldSpec(name="snapshot_id", label="Snapshot ID", type="string"),
        FieldSpec(name="program_id", label="Program ID", type="string"),
        FieldSpec(name="inputs", label="Inputs (JSON)", type="json"),
        FieldSpec(name="limit", label="Limit", type="number", default=25, mode="advanced"),
        FieldSpec(name="area_code", label="Area Code", type="string"),
        FieldSpec(name="ap_number_id", label="AgentPhone Number ID", type="string"),
        FieldSpec(name="from_number", label="From Number", type="string"),
        FieldSpec(name="to_number", label="To Number", type="string"),
        FieldSpec(
            name="conversation_body", label="Conversation Body (JSON)", type="json", default={}
        ),
        FieldSpec(name="message_body", label="Message Body", type="string"),
        FieldSpec(name="emoji", label="Emoji", type="string"),
        FieldSpec(name="contact_id", label="Contact ID", type="string"),
        FieldSpec(name="contact_body", label="Contact Body (JSON)", type="json", default={}),
    ],
    operations=[
        OpSpec(
            id="make_call",
            label="Make Call",
            method="POST",
            path="/calls",
            visible_fields=["to", "from_", "assistant_id", "prompt"],
            body_builder=lambda v: {
                k: val
                for k, val in {
                    "to": getattr(v, "to", None) or None,
                    "from": getattr(v, "from_", None) or None,
                    "assistant_id": getattr(v, "assistant_id", None) or None,
                    "prompt": getattr(v, "prompt", None) or None,
                }.items()
                if val
            },
        ),
        OpSpec(
            id="get_call",
            label="Get Call",
            method="GET",
            path="/calls/{call_id}",
            visible_fields=["call_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_calls",
            label="List Calls",
            method="GET",
            path="/calls",
            visible_fields=["limit"],
            query_builder=lambda v: {"limit": int(getattr(v, "limit", 25) or 25)},
        ),
        OpSpec(
            id="get_transcript",
            label="Get Call Transcript",
            method="GET",
            path="/calls/{call_id}/transcript",
            visible_fields=["call_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_number",
            label="Purchase Phone Number",
            method="POST",
            path="/numbers",
            visible_fields=["area_code"],
            body_builder=lambda v: {"area_code": getattr(v, "area_code", "") or ""},
        ),
        OpSpec(
            id="list_numbers",
            label="List Phone Numbers",
            method="GET",
            path="/numbers",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="release_number",
            label="Release Phone Number",
            method="DELETE",
            path="/numbers/{ap_number_id}",
            visible_fields=["ap_number_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_number_messages",
            label="Get Number Messages",
            method="GET",
            path="/numbers/{ap_number_id}/messages",
            visible_fields=["ap_number_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_call",
            label="Create Call",
            method="POST",
            path="/calls",
            visible_fields=["from_number", "to_number", "agent_id"],
            body_builder=lambda v: {
                "from": getattr(v, "from_number", "") or "",
                "to": getattr(v, "to_number", "") or "",
                "agent_id": getattr(v, "agent_id", None) or None,
            },
        ),
        OpSpec(
            id="get_call_transcript",
            label="Get Call Transcript",
            method="GET",
            path="/calls/{call_id}/transcript",
            visible_fields=["call_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_conversations",
            label="List Conversations",
            method="GET",
            path="/conversations",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_conversation",
            label="Get Conversation",
            method="GET",
            path="/conversations/{conversation_id}",
            visible_fields=["conversation_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="update_conversation",
            label="Update Conversation",
            method="PATCH",
            path="/conversations/{conversation_id}",
            visible_fields=["conversation_id", "conversation_body"],
            body_builder=lambda v: getattr(v, "conversation_body", None) or {},
        ),
        OpSpec(
            id="get_conversation_messages",
            label="Get Conversation Messages",
            method="GET",
            path="/conversations/{conversation_id}/messages",
            visible_fields=["conversation_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="send_message",
            label="Send Message",
            method="POST",
            path="/messages",
            visible_fields=["conversation_id", "message_body"],
            body_builder=lambda v: {
                "conversation_id": getattr(v, "conversation_id", "") or "",
                "content": getattr(v, "message_body", "") or "",
            },
        ),
        OpSpec(
            id="react_to_message",
            label="React to Message",
            method="POST",
            path="/messages/{message_id}/reactions",
            visible_fields=["message_id", "emoji"],
            body_builder=lambda v: {"emoji": getattr(v, "emoji", "") or ""},
        ),
        OpSpec(
            id="create_contact",
            label="Create Contact",
            method="POST",
            path="/contacts",
            visible_fields=["contact_body"],
            body_builder=lambda v: getattr(v, "contact_body", None) or {},
        ),
        OpSpec(
            id="list_contacts",
            label="List Contacts",
            method="GET",
            path="/contacts",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_contact",
            label="Get Contact",
            method="GET",
            path="/contacts/{contact_id}",
            visible_fields=["contact_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="update_contact",
            label="Update Contact",
            method="PATCH",
            path="/contacts/{contact_id}",
            visible_fields=["contact_id", "contact_body"],
            body_builder=lambda v: getattr(v, "contact_body", None) or {},
        ),
        OpSpec(
            id="delete_contact",
            label="Delete Contact",
            method="DELETE",
            path="/contacts/{contact_id}",
            visible_fields=["contact_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_usage",
            label="Get Usage",
            method="GET",
            path="/usage",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_usage_daily",
            label="Get Daily Usage",
            method="GET",
            path="/usage/daily",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_usage_monthly",
            label="Get Monthly Usage",
            method="GET",
            path="/usage/monthly",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "id", "type": "string"},
        {"label": "status", "type": "string"},
    ],
    allow_error=True,
)
