"""Quartr action node — Quartr — earnings-call transcripts + investor events.

REST at https://api.quartr.com/v1. See sim-parity roadmap Phase 4.32.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.quartr",
    name="Quartr",
    category="integration",
    description="Quartr — earnings-call transcripts + investor events.",
    icon_slug="quartr",
    color="#1c1c1c",
    base_url="https://api.quartr.com/v1",
    credential_type="quartr_api_key",
    token_field=["api_key"],
    auth="bearer",
    fields=[
        FieldSpec(name="table", label="Table", type="string"),
        FieldSpec(name="record_id", label="Record ID", type="string"),
        FieldSpec(name="filter", label="Filter", type="string"),
        FieldSpec(name="data", label="Data (JSON)", type="json", default={}),
        FieldSpec(name="config_id", label="Sync Config ID", type="string"),
        FieldSpec(name="query_text", label="Query Text", type="string"),
        FieldSpec(name="destination_id", label="Destination ID", type="string"),
        FieldSpec(name="property_id", label="Property ID", type="string"),
        FieldSpec(name="email", label="Email", type="string"),
        FieldSpec(name="right", label="Right (delete|access|...)", type="string", default="delete"),
        FieldSpec(name="source", label="LaTeX Source", type="string"),
        FieldSpec(name="query", label="Query", type="string"),
        FieldSpec(name="depth", label="Depth (standard|deep)", type="string", default="standard"),
        FieldSpec(name="output_type", label="Output Type", type="string", default="searchResults"),
        FieldSpec(name="supplier_id", label="Supplier ID", type="string"),
        FieldSpec(name="path", label="Path", type="string"),
        FieldSpec(name="content", label="Content", type="string"),
        FieldSpec(name="message", label="Message", type="string"),
        FieldSpec(name="project_id", label="Project ID", type="string"),
        FieldSpec(name="file_url", label="File URL", type="string"),
        FieldSpec(name="json_schema", label="Schema (JSON)", type="json", default={}),
        FieldSpec(name="job_id", label="Job ID", type="string"),
        FieldSpec(name="company_id", label="Company ID", type="string"),
        FieldSpec(name="event_id", label="Event ID", type="string"),
        FieldSpec(name="remote", label="Remote (github|gitlab)", type="string", default="github"),
        FieldSpec(name="repository", label="Repository (owner/repo)", type="string"),
        FieldSpec(name="branch", label="Branch", type="string", default="main"),
        FieldSpec(name="repositories", label="Repositories (JSON)", type="json", default=[]),
        FieldSpec(name="guard_name", label="Guard Name", type="string"),
        FieldSpec(name="llm_output", label="LLM Output", type="string"),
        FieldSpec(name="host_ids", label="Host IDs (JSON)", type="json", default=[]),
        FieldSpec(name="limit", label="Limit", type="number", default=50, mode="advanced"),
        FieldSpec(name="report_id", label="Report ID", type="string"),
        FieldSpec(name="slide_deck_id", label="Slide Deck ID", type="string"),
        FieldSpec(name="transcript_id", label="Transcript ID", type="string"),
        FieldSpec(name="audio_id", label="Audio ID", type="string"),
    ],
    operations=[
        OpSpec(
            id="get_company",
            label="Get Company",
            method="GET",
            path="/companies/{company_id}",
            visible_fields=["company_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_events",
            label="List Events for Company",
            method="GET",
            path="/companies/{company_id}/events",
            visible_fields=["company_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_transcript",
            label="Get Transcript",
            method="GET",
            path="/events/{event_id}/transcript",
            visible_fields=["event_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_companies",
            label="List Companies",
            method="GET",
            path="/companies",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_event_summary",
            label="Get Event Summary",
            method="GET",
            path="/events/{event_id}/summary",
            visible_fields=["event_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_event_types",
            label="List Event Types",
            method="GET",
            path="/events/types",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_documents",
            label="List Documents",
            method="GET",
            path="/documents",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_document_types",
            label="List Document Types",
            method="GET",
            path="/documents/types",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_reports",
            label="List Reports",
            method="GET",
            path="/reports",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_report",
            label="Get Report",
            method="GET",
            path="/reports/{report_id}",
            visible_fields=["report_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_slide_decks",
            label="List Slide Decks",
            method="GET",
            path="/slidedecks",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_slide_deck",
            label="Get Slide Deck",
            method="GET",
            path="/slidedecks/{slide_deck_id}",
            visible_fields=["slide_deck_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_transcripts",
            label="List Transcripts",
            method="GET",
            path="/transcripts",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_transcript_by_id",
            label="Get Transcript by ID",
            method="GET",
            path="/transcripts/{transcript_id}",
            visible_fields=["transcript_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_audio",
            label="List Audio",
            method="GET",
            path="/audio",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_audio",
            label="Get Audio",
            method="GET",
            path="/audio/{audio_id}",
            visible_fields=["audio_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_live_events",
            label="List Live Events",
            method="GET",
            path="/events/live",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "id", "type": "string"},
    ],
    allow_error=True,
)
