"""Square action node — manifest form.

Square Connect API at `https://connect.squareup.com/v2`. Bearer
auth + pinned `Square-Version` header. Five ops cover the common
commerce flows: customer CRUD, payment / order lookup, catalog list.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import (
    FieldSpec,
    OpSpec,
    ProviderManifest,
)

MANIFEST = ProviderManifest(
    type="action.square",
    name="Square",
    category="integration",
    description="Square Connect — payments, orders, customers, catalog.",
    icon_slug="square",
    color="#1c1c1c",
    base_url="https://connect.squareup.com/v2",
    credential_type="square_api_key",
    token_field=["api_key"],
    auth="bearer",
    extra_headers={"Square-Version": "2024-10-17"},
    fields=[
        FieldSpec(name="customer_id", label="Customer ID", type="string"),
        FieldSpec(name="payment_id", label="Payment ID", type="string"),
        FieldSpec(name="order_id", label="Order ID", type="string"),
        FieldSpec(name="given_name", label="Given Name", type="string"),
        FieldSpec(name="family_name", label="Family Name", type="string"),
        FieldSpec(name="email", label="Email", type="string"),
        FieldSpec(name="phone", label="Phone", type="string", mode="advanced"),
        FieldSpec(name="company", label="Company", type="string", mode="advanced"),
        FieldSpec(name="query", label="Search Query (JSON)", type="json", mode="advanced"),
        FieldSpec(name="limit", label="Limit", type="number", default=50, mode="advanced"),
        FieldSpec(name="location_id", label="Location ID", type="string"),
        FieldSpec(name="refund_id", label="Refund ID", type="string"),
        FieldSpec(name="idempotency_key", label="Idempotency Key", type="string"),
        FieldSpec(name="location_ids", label="Location IDs (JSON)", type="json", default=[]),
        FieldSpec(name="invoice_body", label="Invoice Body (JSON)", type="json", default={}),
        FieldSpec(name="invoice_id", label="Invoice ID", type="string"),
        FieldSpec(name="invoice_version", label="Invoice Version", type="number", default=0),
        FieldSpec(name="catalog_body", label="Catalog Object Body (JSON)", type="json", default={}),
        FieldSpec(name="catalog_object_id", label="Catalog Object ID", type="string"),
    ],
    operations=[
        OpSpec(
            id="create_customer",
            label="Create Customer",
            method="POST",
            path="/customers",
            visible_fields=["given_name", "family_name", "email", "phone", "company"],
            body_builder=lambda v: {
                k: val
                for k, val in {
                    "given_name": getattr(v, "given_name", None),
                    "family_name": getattr(v, "family_name", None),
                    "email_address": getattr(v, "email", None),
                    "phone_number": getattr(v, "phone", None),
                    "company_name": getattr(v, "company", None),
                }.items()
                if val is not None
            },
        ),
        OpSpec(
            id="get_customer",
            label="Get Customer",
            method="GET",
            path="/customers/{customer_id}",
            visible_fields=["customer_id"],
        ),
        OpSpec(
            id="search_customers",
            label="Search Customers",
            method="POST",
            path="/customers/search",
            visible_fields=["query", "limit"],
            body_builder=lambda v: {
                "query": getattr(v, "query", None) or {},
                "limit": int(getattr(v, "limit", 50) or 50),
            },
        ),
        OpSpec(
            id="list_customers",
            label="List Customers",
            method="GET",
            path="/customers",
            visible_fields=["limit"],
            query_fields=["limit"],
        ),
        OpSpec(
            id="get_payment",
            label="Get Payment",
            method="GET",
            path="/payments/{payment_id}",
            visible_fields=["payment_id"],
        ),
        OpSpec(
            id="list_payments",
            label="List Payments",
            method="GET",
            path="/payments",
            visible_fields=["location_id", "limit"],
            query_fields=["location_id", "limit"],
        ),
        OpSpec(
            id="get_order",
            label="Get Order",
            method="GET",
            path="/orders/{order_id}",
            visible_fields=["order_id"],
        ),
        OpSpec(
            id="search_orders",
            label="Search Orders",
            method="POST",
            path="/orders/search",
            visible_fields=["query", "limit"],
            body_builder=lambda v: {
                "query": getattr(v, "query", None) or {},
                "limit": int(getattr(v, "limit", 50) or 50),
            },
        ),
        OpSpec(
            id="list_catalog",
            label="List Catalog",
            method="GET",
            path="/catalog/list",
        ),
        OpSpec(
            id="list_locations",
            label="List Locations",
            method="GET",
            path="/locations",
        ),
        OpSpec(
            id="cancel_payment",
            label="Cancel Payment",
            method="POST",
            path="/v2/payments/{payment_id}/cancel",
            visible_fields=["payment_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="complete_payment",
            label="Complete Payment",
            method="POST",
            path="/v2/payments/{payment_id}/complete",
            visible_fields=["payment_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="refund_payment",
            label="Refund Payment",
            method="POST",
            path="/v2/refunds",
            visible_fields=["payment_id", "amount", "currency", "idempotency_key"],
            body_builder=lambda v: {
                "idempotency_key": getattr(v, "idempotency_key", "") or "",
                "payment_id": getattr(v, "payment_id", "") or "",
                "amount_money": {
                    "amount": int(getattr(v, "amount", 0) or 0),
                    "currency": getattr(v, "currency", None) or "USD",
                },
            },
        ),
        OpSpec(
            id="get_refund",
            label="Get Refund",
            method="GET",
            path="/v2/refunds/{refund_id}",
            visible_fields=["refund_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_refunds",
            label="List Refunds",
            method="GET",
            path="/v2/refunds",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="delete_customer",
            label="Delete Customer",
            method="DELETE",
            path="/v2/customers/{customer_id}",
            visible_fields=["customer_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="pay_order",
            label="Pay Order",
            method="POST",
            path="/v2/orders/{order_id}/pay",
            visible_fields=["order_id", "idempotency_key"],
            body_builder=lambda v: {"idempotency_key": getattr(v, "idempotency_key", "") or ""},
        ),
        OpSpec(
            id="create_invoice",
            label="Create Invoice",
            method="POST",
            path="/v2/invoices",
            visible_fields=["invoice_body"],
            body_builder=lambda v: getattr(v, "invoice_body", None) or {},
        ),
        OpSpec(
            id="get_invoice",
            label="Get Invoice",
            method="GET",
            path="/v2/invoices/{invoice_id}",
            visible_fields=["invoice_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_invoices",
            label="List Invoices",
            method="GET",
            path="/v2/invoices",
            visible_fields=["location_id"],
            query_builder=lambda v: {"location_id": getattr(v, "location_id", "") or ""},
        ),
        OpSpec(
            id="publish_invoice",
            label="Publish Invoice",
            method="POST",
            path="/v2/invoices/{invoice_id}/publish",
            visible_fields=["invoice_id", "invoice_version", "idempotency_key"],
            body_builder=lambda v: {
                "version": int(getattr(v, "invoice_version", 0) or 0),
                "idempotency_key": getattr(v, "idempotency_key", "") or "",
            },
        ),
        OpSpec(
            id="cancel_invoice",
            label="Cancel Invoice",
            method="POST",
            path="/v2/invoices/{invoice_id}/cancel",
            visible_fields=["invoice_id", "invoice_version"],
            body_builder=lambda v: {"version": int(getattr(v, "invoice_version", 0) or 0)},
        ),
        OpSpec(
            id="delete_invoice",
            label="Delete Invoice",
            method="DELETE",
            path="/v2/invoices/{invoice_id}",
            visible_fields=["invoice_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="upsert_catalog_object",
            label="Upsert Catalog Object",
            method="POST",
            path="/v2/catalog/object",
            visible_fields=["catalog_body", "idempotency_key"],
            body_builder=lambda v: {
                "idempotency_key": getattr(v, "idempotency_key", "") or "",
                "object": getattr(v, "catalog_body", None) or {},
            },
        ),
        OpSpec(
            id="get_catalog_object",
            label="Get Catalog Object",
            method="GET",
            path="/v2/catalog/object/{catalog_object_id}",
            visible_fields=["catalog_object_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="delete_catalog_object",
            label="Delete Catalog Object",
            method="DELETE",
            path="/v2/catalog/object/{catalog_object_id}",
            visible_fields=["catalog_object_id"],
            query_builder=lambda v: {},
        ),
    ],
    outputs_schema=[
        {"label": "customer", "type": "object"},
        {"label": "payment", "type": "object"},
        {"label": "order", "type": "object"},
        {"label": "customers", "type": "array"},
        {"label": "payments", "type": "array"},
        {"label": "orders", "type": "array"},
        {"label": "objects", "type": "array"},
        {"label": "locations", "type": "array"},
    ],
    allow_error=True,
)
