"""incident.io action node — incident.io — incident response + postmortems.

REST at https://api.incident.io/v2. See sim-parity roadmap Phase 4.22.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.incidentio",
    name="incident.io",
    category="integration",
    description="incident.io — incident response + postmortems.",
    icon_slug="incidentio",
    color="#1c1c1c",
    base_url="https://api.incident.io/v2",
    credential_type="incidentio_api_key",
    token_field=["api_key"],
    auth="bearer",
    fields=[
        FieldSpec(name="query", label="GraphQL Query / Search Query", type="string"),
        FieldSpec(name="variables", label="Variables (JSON)", type="json"),
        FieldSpec(name="run_config", label="Run Config (JSON)", type="json"),
        FieldSpec(name="workspace_id", label="Workspace ID", type="string"),
        FieldSpec(name="name", label="Name", type="string"),
        FieldSpec(name="repository", label="Repository URL", type="string"),
        FieldSpec(name="project_key", label="Project Key", type="string"),
        FieldSpec(name="flag_key", label="Feature Flag Key", type="string"),
        FieldSpec(name="environment_key", label="Environment Key", type="string"),
        FieldSpec(name="enabled", label="Enabled (true/false)", type="string"),
        FieldSpec(name="severity_id", label="Severity ID", type="string"),
        FieldSpec(name="severity", label="Severity (slug)", type="string"),
        FieldSpec(name="summary", label="Summary", type="string"),
        FieldSpec(name="visibility", label="Visibility", type="string", default="public"),
        FieldSpec(name="incident_id", label="Incident ID", type="string"),
        FieldSpec(name="title", label="Title", type="string"),
        FieldSpec(name="status", label="Status", type="string"),
        FieldSpec(name="page_size", label="Page Size", type="number", default=25, mode="advanced"),
        FieldSpec(name="incident_body", label="Incident Body (JSON)", type="json", default={}),
        FieldSpec(name="action_id", label="Action ID", type="string"),
        FieldSpec(name="action_body", label="Action Body (JSON)", type="json", default={}),
        FieldSpec(name="user_id", label="User ID", type="string"),
        FieldSpec(name="follow_up_id", label="Follow-up ID", type="string"),
        FieldSpec(
            name="incident_update_body",
            label="Incident Update Body (JSON)",
            type="json",
            default={},
        ),
        FieldSpec(name="alert_event_id", label="Alert Event ID", type="string"),
        FieldSpec(
            name="alert_event_body", label="Alert Event Body (JSON)", type="json", default={}
        ),
        FieldSpec(name="source_id", label="Alert Source ID", type="string"),
        FieldSpec(name="route_id", label="Alert Route ID", type="string"),
        FieldSpec(name="catalog_type_id", label="Catalog Type ID", type="string"),
        FieldSpec(name="catalog_entry_id", label="Catalog Entry ID", type="string"),
        FieldSpec(name="status_id", label="Status ID", type="string"),
    ],
    operations=[
        OpSpec(
            id="create_incident",
            label="Create Incident",
            method="POST",
            path="/incidents",
            visible_fields=["name", "severity_id", "summary", "visibility"],
            body_builder=lambda v: {
                "name": getattr(v, "name", "") or "",
                "severity_id": getattr(v, "severity_id", None) or None,
                "summary": getattr(v, "summary", None) or None,
                "visibility": getattr(v, "visibility", None) or "public",
                "idempotency_key": (getattr(v, "name", "") or "")
                + "-"
                + (getattr(v, "severity_id", None) or ""),
            },
        ),
        OpSpec(
            id="list_incidents",
            label="List Incidents",
            method="GET",
            path="/incidents",
            visible_fields=["page_size"],
            query_builder=lambda v: {"page_size": int(getattr(v, "page_size", 25) or 25)},
        ),
        OpSpec(
            id="get_incident",
            label="Get Incident",
            method="GET",
            path="/incidents/{incident_id}",
            visible_fields=["incident_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="update_incident",
            label="Update Incident",
            method="POST",
            path="/incident_updates",
            visible_fields=["incident_id", "summary"],
            body_builder=lambda v: {
                "incident_update": {
                    "incident_id": getattr(v, "incident_id", "") or "",
                    "message": getattr(v, "summary", "") or "",
                }
            },
        ),
        OpSpec(
            id="list_severities",
            label="List Severities",
            method="GET",
            path="/severities",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="close_incident",
            label="Close Incident",
            method="POST",
            path="/v2/incidents/{incident_id}/actions/close",
            visible_fields=["incident_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="create_action",
            label="Create Action",
            method="POST",
            path="/v2/actions",
            visible_fields=["action_body"],
            body_builder=lambda v: getattr(v, "action_body", None) or {},
        ),
        OpSpec(
            id="list_actions",
            label="List Actions",
            method="GET",
            path="/v2/actions",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_action",
            label="Get Action",
            method="GET",
            path="/v2/actions/{action_id}",
            visible_fields=["action_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="update_action",
            label="Update Action",
            method="PUT",
            path="/v2/actions/{action_id}",
            visible_fields=["action_id", "action_body"],
            body_builder=lambda v: getattr(v, "action_body", None) or {},
        ),
        OpSpec(
            id="list_users",
            label="List Users",
            method="GET",
            path="/v2/users",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_user",
            label="Get User",
            method="GET",
            path="/v2/users/{user_id}",
            visible_fields=["user_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_incident_types",
            label="List Incident Types",
            method="GET",
            path="/v1/incident_types",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_incident_roles",
            label="List Incident Roles",
            method="GET",
            path="/v1/incident_roles",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_incident_updates",
            label="List Incident Updates",
            method="GET",
            path="/v2/incident_updates",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_incident_update",
            label="Create Incident Update",
            method="POST",
            path="/v2/incident_updates",
            visible_fields=["incident_update_body"],
            body_builder=lambda v: getattr(v, "incident_update_body", None) or {},
        ),
        OpSpec(
            id="list_follow_ups",
            label="List Follow-ups",
            method="GET",
            path="/v2/follow_ups",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_follow_up",
            label="Get Follow-up",
            method="GET",
            path="/v2/follow_ups/{follow_up_id}",
            visible_fields=["follow_up_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_schedules",
            label="List Schedules",
            method="GET",
            path="/v2/schedules",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_alert_events",
            label="List Alert Events",
            method="GET",
            path="/v2/alert_events",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_alert_event",
            label="Get Alert Event",
            method="GET",
            path="/v2/alert_events/{alert_event_id}",
            visible_fields=["alert_event_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_alert_event",
            label="Create Alert Event",
            method="POST",
            path="/v2/alert_events",
            visible_fields=["alert_event_body"],
            body_builder=lambda v: getattr(v, "alert_event_body", None) or {},
        ),
        OpSpec(
            id="list_alert_sources",
            label="List Alert Sources",
            method="GET",
            path="/v2/alert_sources",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_alert_source",
            label="Get Alert Source",
            method="GET",
            path="/v2/alert_sources/{source_id}",
            visible_fields=["source_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_alert_routes",
            label="List Alert Routes",
            method="GET",
            path="/v2/alert_routes",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_alert_route",
            label="Get Alert Route",
            method="GET",
            path="/v2/alert_routes/{route_id}",
            visible_fields=["route_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_catalog_types",
            label="List Catalog Types",
            method="GET",
            path="/v3/catalog_types",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_catalog_type",
            label="Get Catalog Type",
            method="GET",
            path="/v3/catalog_types/{catalog_type_id}",
            visible_fields=["catalog_type_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_catalog_entries",
            label="List Catalog Entries",
            method="GET",
            path="/v3/catalog_entries",
            visible_fields=["catalog_type_id"],
            query_builder=lambda v: {
                k: val
                for k, val in {
                    "catalog_type_id": getattr(v, "catalog_type_id", None) or None
                }.items()
                if val
            },
        ),
        OpSpec(
            id="get_catalog_entry",
            label="Get Catalog Entry",
            method="GET",
            path="/v3/catalog_entries/{catalog_entry_id}",
            visible_fields=["catalog_entry_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_workflows",
            label="List Workflows",
            method="GET",
            path="/v1/workflows",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_custom_fields",
            label="List Custom Fields",
            method="GET",
            path="/v1/custom_fields",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_available_incident_statuses",
            label="List Available Incident Statuses",
            method="GET",
            path="/v1/incident_statuses",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_incident_status",
            label="Get Incident Status",
            method="GET",
            path="/v1/incident_statuses/{status_id}",
            visible_fields=["status_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_severity",
            label="Get Severity",
            method="GET",
            path="/v1/severities/{severity_id}",
            visible_fields=["severity_id"],
            query_builder=lambda v: {},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "id", "type": "string"},
        {"label": "status", "type": "string"},
    ],
    allow_error=True,
)
