"""Vercel action node — manifest form.

Vercel's REST API lives at `https://api.vercel.com`. Bearer auth using
a personal access token. Ops we expose:

  - Deployments — list, get, cancel
  - Projects — list, get
  - Domains — list, add, remove
  - Env vars — list, create

`team_id` is a query param the user passes when their token belongs to
a personal account but they want to act on a team. Optional everywhere.
"""

from __future__ import annotations

from apps.api.app.node_system.nodes.vercel import COLOR, ICON_SLUG, NAME
from apps.api.app.node_system.scaffolds import (
    FieldSpec,
    OpSpec,
    ProviderManifest,
)

MANIFEST = ProviderManifest(
    type="action.vercel",
    name=NAME,
    category="integration",
    description="Manage Vercel deployments, projects, domains, and env vars.",
    icon_slug=ICON_SLUG,
    color=COLOR,
    base_url="https://api.vercel.com",
    credential_type="vercel_api_key",
    token_field=["api_key"],
    auth="bearer",
    fields=[
        FieldSpec(name="team_id", label="Team ID (optional)", type="string", mode="advanced"),
        FieldSpec(name="project_id", label="Project ID or name", type="string"),
        FieldSpec(name="deployment_id", label="Deployment ID", type="string"),
        FieldSpec(name="domain", label="Domain", type="string"),
        FieldSpec(name="limit", label="Limit", type="number", default=20, mode="advanced"),
        FieldSpec(name="env_key", label="Env Var Key", type="string"),
        FieldSpec(name="env_value", label="Env Var Value", type="string", secret=True),
        FieldSpec(
            name="env_target",
            label="Env Target (JSON array)",
            type="json",
            mode="advanced",
            placeholder='["production", "preview"]',
        ),
        FieldSpec(
            name="env_type",
            label="Env Var Type",
            type="options",
            default="encrypted",
            mode="advanced",
            options=[
                {"label": "Encrypted", "value": "encrypted"},
                {"label": "Plain", "value": "plain"},
                {"label": "System", "value": "system"},
                {"label": "Sensitive", "value": "sensitive"},
            ],
        ),
        FieldSpec(name="env_id", label="Env Var ID", type="string"),
        FieldSpec(name="dns_name", label="DNS Record Name", type="string"),
        FieldSpec(name="dns_type", label="DNS Record Type", type="string"),
        FieldSpec(name="dns_value", label="DNS Record Value", type="string"),
        FieldSpec(name="dns_record_id", label="DNS Record ID", type="string"),
        FieldSpec(
            name="role",
            label="Role (OWNER|MEMBER|DEVELOPER|BILLING|VIEWER)",
            type="string",
            default="MEMBER",
        ),
        FieldSpec(name="secret_name", label="Secret Name", type="string"),
        FieldSpec(name="secret_value", label="Secret Value", type="string"),
        FieldSpec(name="cert_id", label="Certificate ID", type="string"),
        FieldSpec(name="url", label="URL", type="string"),
    ],
    operations=[
        OpSpec(
            id="list_deployments",
            label="List Deployments",
            method="GET",
            path="/v6/deployments",
            visible_fields=["project_id", "team_id", "limit"],
            query_fields=["project_id", "team_id", "limit"],
        ),
        OpSpec(
            id="get_deployment",
            label="Get Deployment",
            method="GET",
            path="/v13/deployments/{deployment_id}",
            visible_fields=["deployment_id", "team_id"],
            query_fields=["team_id"],
        ),
        OpSpec(
            id="cancel_deployment",
            label="Cancel Deployment",
            method="PATCH",
            path="/v12/deployments/{deployment_id}/cancel",
            visible_fields=["deployment_id", "team_id"],
            query_fields=["team_id"],
        ),
        OpSpec(
            id="list_projects",
            label="List Projects",
            method="GET",
            path="/v9/projects",
            visible_fields=["team_id", "limit"],
            query_fields=["team_id", "limit"],
        ),
        OpSpec(
            id="get_project",
            label="Get Project",
            method="GET",
            path="/v9/projects/{project_id}",
            visible_fields=["project_id", "team_id"],
            query_fields=["team_id"],
        ),
        OpSpec(
            id="list_domains",
            label="List Domains",
            method="GET",
            path="/v9/projects/{project_id}/domains",
            visible_fields=["project_id", "team_id"],
            query_fields=["team_id"],
        ),
        OpSpec(
            id="add_domain",
            label="Add Domain",
            method="POST",
            path="/v10/projects/{project_id}/domains",
            visible_fields=["project_id", "domain", "team_id"],
            query_fields=["team_id"],
            body_template={"name": "{domain}"},
        ),
        OpSpec(
            id="remove_domain",
            label="Remove Domain",
            method="DELETE",
            path="/v9/projects/{project_id}/domains/{domain}",
            visible_fields=["project_id", "domain", "team_id"],
            query_fields=["team_id"],
            success_payload_template={"deleted": True, "domain": "{domain}"},
        ),
        OpSpec(
            id="list_env_vars",
            label="List Env Vars",
            method="GET",
            path="/v9/projects/{project_id}/env",
            visible_fields=["project_id", "team_id"],
            query_fields=["team_id"],
        ),
        OpSpec(
            id="create_env_var",
            label="Create Env Var",
            method="POST",
            path="/v10/projects/{project_id}/env",
            visible_fields=[
                "project_id",
                "env_key",
                "env_value",
                "env_target",
                "env_type",
                "team_id",
            ],
            query_fields=["team_id"],
            body_builder=lambda props: {
                "key": getattr(props, "env_key", None),
                "value": getattr(props, "env_value", None),
                "type": getattr(props, "env_type", None) or "encrypted",
                "target": getattr(props, "env_target", None) or ["production"],
            },
        ),
        OpSpec(
            id="delete_deployment",
            label="Delete Deployment",
            method="DELETE",
            path="/v13/deployments/{deployment_id}",
            visible_fields=["deployment_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_deployment_events",
            label="Get Deployment Build Events",
            method="GET",
            path="/v3/deployments/{deployment_id}/events",
            visible_fields=["deployment_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_deployment_files",
            label="List Deployment Files",
            method="GET",
            path="/v6/deployments/{deployment_id}/files",
            visible_fields=["deployment_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="promote_deployment",
            label="Promote Deployment",
            method="POST",
            path="/v10/projects/{project_id}/promote/{deployment_id}",
            visible_fields=["project_id", "deployment_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="pause_project",
            label="Pause Project",
            method="POST",
            path="/v1/projects/{project_id}/pause",
            visible_fields=["project_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="unpause_project",
            label="Unpause Project",
            method="POST",
            path="/v1/projects/{project_id}/unpause",
            visible_fields=["project_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="verify_project_domain",
            label="Verify Project Domain",
            method="POST",
            path="/v9/projects/{project_id}/domains/{domain}/verify",
            visible_fields=["project_id", "domain"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="delete_env_var",
            label="Delete Env Var",
            method="DELETE",
            path="/v9/projects/{project_id}/env/{env_id}",
            visible_fields=["project_id", "env_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="update_env_var",
            label="Update Env Var",
            method="PATCH",
            path="/v9/projects/{project_id}/env/{env_id}",
            visible_fields=["project_id", "env_id", "env_value"],
            body_builder=lambda v: {"value": getattr(v, "env_value", "") or ""},
        ),
        OpSpec(
            id="get_domain",
            label="Get Domain",
            method="GET",
            path="/v5/domains/{domain}",
            visible_fields=["domain"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="delete_domain",
            label="Delete Domain",
            method="DELETE",
            path="/v6/domains/{domain}",
            visible_fields=["domain"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_dns_records",
            label="List DNS Records",
            method="GET",
            path="/v4/domains/{domain}/records",
            visible_fields=["domain"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_dns_record",
            label="Create DNS Record",
            method="POST",
            path="/v2/domains/{domain}/records",
            visible_fields=["domain", "dns_name", "dns_type", "dns_value"],
            body_builder=lambda v: {
                "name": getattr(v, "dns_name", "") or "",
                "type": getattr(v, "dns_type", "") or "",
                "value": getattr(v, "dns_value", "") or "",
            },
        ),
        OpSpec(
            id="delete_dns_record",
            label="Delete DNS Record",
            method="DELETE",
            path="/v2/domains/{domain}/records/{dns_record_id}",
            visible_fields=["domain", "dns_record_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_aliases",
            label="List Aliases",
            method="GET",
            path="/v4/aliases",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_edge_configs",
            label="List Edge Configs",
            method="GET",
            path="/v1/edge-config",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_teams",
            label="List Teams",
            method="GET",
            path="/v2/teams",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_team",
            label="Get Team",
            method="GET",
            path="/v2/teams/{team_id}",
            visible_fields=["team_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_team_members",
            label="List Team Members",
            method="GET",
            path="/v2/teams/{team_id}/members",
            visible_fields=["team_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="add_team_member",
            label="Add Team Member",
            method="POST",
            path="/v1/teams/{team_id}/members",
            visible_fields=["team_id", "email", "role"],
            body_builder=lambda v: {
                "email": getattr(v, "email", "") or "",
                "role": getattr(v, "role", None) or "MEMBER",
            },
        ),
        OpSpec(
            id="list_secrets",
            label="List Secrets",
            method="GET",
            path="/v3/secrets",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_secret",
            label="Create Secret",
            method="POST",
            path="/v3/secrets",
            visible_fields=["secret_name", "secret_value"],
            body_builder=lambda v: {
                "name": getattr(v, "secret_name", "") or "",
                "value": getattr(v, "secret_value", "") or "",
            },
        ),
        OpSpec(
            id="delete_secret",
            label="Delete Secret",
            method="DELETE",
            path="/v2/secrets/{secret_name}",
            visible_fields=["secret_name"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_certs",
            label="List Certificates",
            method="GET",
            path="/v4/certs",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_cert",
            label="Get Certificate",
            method="GET",
            path="/v4/certs/{cert_id}",
            visible_fields=["cert_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_deployment_checks",
            label="List Deployment Checks",
            method="GET",
            path="/v1/deployments/{deployment_id}/checks",
            visible_fields=["deployment_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_deployment_promote",
            label="List Recent Promotions",
            method="GET",
            path="/v1/projects/{project_id}/promote/aliases",
            visible_fields=["project_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_deployment_by_url",
            label="Get Deployment by URL",
            method="GET",
            path="/v13/deployments/get",
            visible_fields=["url"],
            query_builder=lambda v: {"url": getattr(v, "url", "") or ""},
        ),
        OpSpec(
            id="list_project_alias",
            label="List Project Aliases",
            method="GET",
            path="/v2/projects/{project_id}/aliases",
            visible_fields=["project_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_integrations",
            label="List Integrations",
            method="GET",
            path="/v1/integrations",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_log_drains",
            label="List Log Drains",
            method="GET",
            path="/v2/integrations/log-drains",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_analytics",
            label="Get Analytics",
            method="GET",
            path="/v1/analytics",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_user_events",
            label="List User Events",
            method="GET",
            path="/v3/user/events",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_domains_prices",
            label="List Domain Purchase Prices",
            method="GET",
            path="/v3/domains/prices",
            visible_fields=["domain"],
            query_builder=lambda v: {"name": getattr(v, "domain", "") or ""},
        ),
        OpSpec(
            id="check_domain_availability",
            label="Check Domain Availability",
            method="GET",
            path="/v4/domains/status",
            visible_fields=["domain"],
            query_builder=lambda v: {"name": getattr(v, "domain", "") or ""},
        ),
        OpSpec(
            id="buy_domain",
            label="Buy Domain",
            method="POST",
            path="/v4/domains/buy",
            visible_fields=["domain"],
            body_builder=lambda v: {"name": getattr(v, "domain", "") or ""},
        ),
        OpSpec(
            id="get_env_var",
            label="Get Env Var",
            method="GET",
            path="/v9/projects/{project_id}/env/{env_id}",
            visible_fields=["project_id", "env_id"],
            query_builder=lambda v: {},
        ),
    ],
    outputs_schema=[
        {"label": "id", "type": "string"},
        {"label": "name", "type": "string"},
        {"label": "url", "type": "string"},
        {"label": "state", "type": "string"},
        {"label": "items", "type": "array"},
        {"label": "deployments", "type": "array"},
        {"label": "projects", "type": "array"},
    ],
    allow_error=True,
)
