"""copilot session: nullable workflow_id + crew_id

Revision ID: 6964eabb8752
Revises: f5575a4461df
Create Date: 2026-07-13 10:50:29.922004

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6964eabb8752"
down_revision: str | None = "f5575a4461df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("copilotsession", sa.Column("crew_id", sa.UUID(), nullable=True))
    op.alter_column("copilotsession", "workflow_id", existing_type=sa.UUID(), nullable=True)
    op.create_foreign_key(
        "copilotsession_crew_id_fkey",
        "copilotsession",
        "crew",
        ["crew_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Named constraint so the downgrade actually works (autogen used None).
    op.drop_constraint("copilotsession_crew_id_fkey", "copilotsession", type_="foreignkey")
    op.alter_column("copilotsession", "workflow_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("copilotsession", "crew_id")
    # ### end Alembic commands ###
