"""add_tables

Revision ID: 735cac88aff1
Revises: a48b71261404
Create Date: 2026-05-21 02:03:12.945530

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "735cac88aff1"
down_revision: str | None = "a48b71261404"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("file_type", sa.String(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "datatable",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_datatable_workspace_id"), "datatable", ["workspace_id"], unique=False)
    op.create_table(
        "tablecolumn",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("table_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("col_type", sa.String(length=50), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["table_id"], ["datatable.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tablecolumn_table_id"), "tablecolumn", ["table_id"], unique=False)
    op.create_table(
        "tablerow",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("table_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["table_id"], ["datatable.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tablerow_table_id"), "tablerow", ["table_id"], unique=False)
    op.alter_column(
        "copilotsession", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "copilotsession", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.drop_index(op.f("ix_copilotsession_workflow_user"), table_name="copilotsession")
    op.alter_column(
        "execution",
        "snapshot",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.alter_column(
        "execution",
        "resume_schema",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("kbchunk_embedding_idx"),
        table_name="kbchunk",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="hnsw",
    )
    op.drop_index(op.f("ix_secret_user_id"), table_name="secret")
    op.drop_index(op.f("ix_skill_user_id"), table_name="skill")
    op.drop_constraint(op.f("uq_skill_user_name"), "skill", type_="unique")
    op.alter_column(
        "workflow",
        "env",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_workflowversion_workflow_id"), table_name="workflowversion")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_workflowversion_workflow_id"), "workflowversion", ["workflow_id"], unique=False
    )
    op.alter_column(
        "workflow",
        "env",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.create_unique_constraint(
        op.f("uq_skill_user_name"),
        "skill",
        ["user_id", "name"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("ix_skill_user_id"), "skill", ["user_id"], unique=False)
    op.create_index(op.f("ix_secret_user_id"), "secret", ["user_id"], unique=False)
    op.create_index(
        op.f("kbchunk_embedding_idx"),
        "kbchunk",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_using="hnsw",
    )
    op.alter_column(
        "execution",
        "resume_schema",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "execution",
        "snapshot",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_copilotsession_workflow_user"),
        "copilotsession",
        ["workflow_id", "user_id"],
        unique=False,
    )
    op.alter_column(
        "copilotsession", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "copilotsession", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_index(op.f("ix_tablerow_table_id"), table_name="tablerow")
    op.drop_table("tablerow")
    op.drop_index(op.f("ix_tablecolumn_table_id"), table_name="tablecolumn")
    op.drop_table("tablecolumn")
    op.drop_index(op.f("ix_datatable_workspace_id"), table_name="datatable")
    op.drop_table("datatable")
    op.drop_table("asset")
    # ### end Alembic commands ###
