"""update_secret_scope_default_to_workspace

Revision ID: 925bd6156941
Revises: cb5ff257f21d
Create Date: 2026-05-22 14:44:43.587729

"""

from collections.abc import Sequence

revision: str = "925bd6156941"
down_revision: str | None = "cb5ff257f21d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
