"""add trigger_fixture table

Revision ID: 988837851652
Revises: 56974735ad4f
Create Date: 2026-06-14 17:54:33.508872

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

from apps.api.app.shared.sqlmodel import UTCDateTime

revision: str = "988837851652"
down_revision: str | None = "56974735ad4f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "triggerfixture",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("captured_at", UTCDateTime(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("updated_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflow.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id", "node_id", name="uq_trigger_fixture_workflow_node"),
    )
    op.create_index(
        op.f("ix_triggerfixture_workflow_id"), "triggerfixture", ["workflow_id"], unique=False
    )
    op.create_index(
        op.f("ix_triggerfixture_workspace_id"), "triggerfixture", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_triggerfixture_workspace_id"), table_name="triggerfixture")
    op.drop_index(op.f("ix_triggerfixture_workflow_id"), table_name="triggerfixture")
    op.drop_table("triggerfixture")
    # ### end Alembic commands ###
