"""add_raw_content_to_kbdocument

Revision ID: a89caf9c6db4
Revises: c1dc1e8272fa
Create Date: 2026-05-22 16:21:10.815747

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'a89caf9c6db4'
down_revision: str | None = 'c1dc1e8272fa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kbdocument', sa.Column('raw_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kbdocument', 'raw_content')
    # ### end Alembic commands ###
