"""add_kb_chunking_strategy_min_size

Revision ID: c1dc1e8272fa
Revises: 6dc72c936f60
Create Date: 2026-05-22 15:21:32.441834

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c1dc1e8272fa"
down_revision: str | None = "6dc72c936f60"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("knowledgebase", sa.Column("min_chunk_size", sa.Integer(), nullable=False))
    op.add_column(
        "knowledgebase", sa.Column("chunking_strategy", sa.String(length=50), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("knowledgebase", "chunking_strategy")
    op.drop_column("knowledgebase", "min_chunk_size")
    # ### end Alembic commands ###
