"""add_scope_is_secret_to_secret

Revision ID: cb5ff257f21d
Revises: f7c87737cc4a
Create Date: 2026-05-22 14:39:29.402586

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'cb5ff257f21d'
down_revision: str | None = 'f7c87737cc4a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('secret', sa.Column('scope', sa.String(length=50), nullable=False))
    op.add_column('secret', sa.Column('is_secret', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('secret', 'is_secret')
    op.drop_column('secret', 'scope')
    # ### end Alembic commands ###
