"""add_status_to_kbdocument

Revision ID: f055021af1b5
Revises: a89caf9c6db4
Create Date: 2026-05-22 16:33:21.099593

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f055021af1b5'
down_revision: str | None = 'a89caf9c6db4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Add as nullable first to allow backfill of existing rows
    op.add_column('kbdocument', sa.Column('status', sa.String(length=20), nullable=True))

    # Backfill: docs with chunk_count > 0 are treated as indexed; others as pending
    op.execute("""
        UPDATE kbdocument
        SET status = CASE
            WHEN chunk_count > 0 THEN 'indexed'
            ELSE 'pending'
        END
        WHERE status IS NULL
    """)

    # Now tighten to NOT NULL with a server default for safety
    op.alter_column('kbdocument', 'status', nullable=False, server_default='pending')



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kbdocument', 'status')
    # ### end Alembic commands ###
