"""app_session crew source

Revision ID: f5575a4461df
Revises: e8b3f5c92a17
Create Date: 2026-07-10 14:11:34.068815

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f5575a4461df"
down_revision: str | None = "e8b3f5c92a17"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("app_session", sa.Column("crew_id", sa.Uuid(), nullable=True))
    op.alter_column("app_session", "workflow_id", existing_type=sa.UUID(), nullable=True)
    op.create_index(op.f("ix_app_session_crew_id"), "app_session", ["crew_id"], unique=False)
    op.create_foreign_key(
        "fk_app_session_crew_id", "app_session", "crew", ["crew_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_app_session_crew_id", "app_session", type_="foreignkey")
    op.drop_index(op.f("ix_app_session_crew_id"), table_name="app_session")
    op.alter_column("app_session", "workflow_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("app_session", "crew_id")
    # ### end Alembic commands ###
