"""add_api_key_table

Revision ID: f7c87737cc4a
Revises: 735cac88aff1
Create Date: 2026-05-22 14:04:02.900409

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f7c87737cc4a"
down_revision: str | None = "735cac88aff1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apikey",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("key_preview", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_apikey_key_hash"), "apikey", ["key_hash"], unique=True)
    op.create_index(op.f("ix_apikey_user_id"), "apikey", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_apikey_user_id"), table_name="apikey")
    op.drop_index(op.f("ix_apikey_key_hash"), table_name="apikey")
    op.drop_table("apikey")
    # ### end Alembic commands ###
