"""add integration_trigger_state for polling cursors

Revision ID: fb4e4bafc6d6
Revises: ac7b70410fb8
Create Date: 2026-06-16 00:42:28.380355

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

import apps.api.app.shared.sqlmodel  # noqa: F401 — UTCDateTime column type

revision: str = "fb4e4bafc6d6"
down_revision: str | None = "ac7b70410fb8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integrationtriggerstate",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workflow_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("cursor", sa.JSON(), nullable=True),
        sa.Column("last_polled_at", apps.api.app.shared.sqlmodel.UTCDateTime(), nullable=True),
        sa.Column("next_poll_at", apps.api.app.shared.sqlmodel.UTCDateTime(), nullable=True),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.Column("created_at", apps.api.app.shared.sqlmodel.UTCDateTime(), nullable=False),
        sa.Column("updated_at", apps.api.app.shared.sqlmodel.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflow.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspace.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workflow_id", "node_id", name="uq_integration_trigger_state_workflow_node"
        ),
    )
    op.create_index(
        op.f("ix_integrationtriggerstate_next_poll_at"),
        "integrationtriggerstate",
        ["next_poll_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integrationtriggerstate_provider"),
        "integrationtriggerstate",
        ["provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integrationtriggerstate_workflow_id"),
        "integrationtriggerstate",
        ["workflow_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integrationtriggerstate_workspace_id"),
        "integrationtriggerstate",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_integrationtriggerstate_workspace_id"), table_name="integrationtriggerstate"
    )
    op.drop_index(
        op.f("ix_integrationtriggerstate_workflow_id"), table_name="integrationtriggerstate"
    )
    op.drop_index(op.f("ix_integrationtriggerstate_provider"), table_name="integrationtriggerstate")
    op.drop_index(
        op.f("ix_integrationtriggerstate_next_poll_at"), table_name="integrationtriggerstate"
    )
    op.drop_table("integrationtriggerstate")
    # ### end Alembic commands ###
