"""Kalshi action node — Kalshi — prediction market events, markets, orders.

REST at https://trading-api.kalshi.com/trade-api/v2. See sim-parity roadmap Phase 4.30.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.kalshi",
    name="Kalshi",
    category="integration",
    description="Kalshi — prediction market events, markets, orders.",
    icon_slug="kalshi",
    color="#1c1c1c",
    base_url="https://trading-api.kalshi.com/trade-api/v2",
    credential_type="kalshi_api_key",
    token_field=["api_key"],
    auth="bearer",
    fields=[
        FieldSpec(name="tailnet", label="Tailnet", type="string", default="-"),
        FieldSpec(name="device_id", label="Device ID", type="string"),
        FieldSpec(name="tags", label="Tags (JSON array)", type="json", default=[]),
        FieldSpec(name="s3_bucket", label="S3 Bucket", type="string"),
        FieldSpec(name="s3_key", label="S3 Key", type="string"),
        FieldSpec(
            name="feature_types",
            label="Feature Types (JSON)",
            type="json",
            default=["TABLES", "FORMS"],
        ),
        FieldSpec(name="pipeline_name", label="Pipeline Name", type="string"),
        FieldSpec(name="task_id", label="Task ID", type="string"),
        FieldSpec(name="run_id", label="Run ID", type="string"),
        FieldSpec(name="payload", label="Payload (JSON)", type="json", default={}),
        FieldSpec(name="test_id", label="Test ID", type="string"),
        FieldSpec(name="status", label="Status", type="string"),
        FieldSpec(name="event_ticker", label="Event Ticker", type="string"),
        FieldSpec(name="ticker", label="Ticker", type="string"),
        FieldSpec(name="side", label="Side (yes|no|buy|sell)", type="string"),
        FieldSpec(name="count", label="Count", type="number", default=1),
        FieldSpec(name="price", label="Yes Price (¢)", type="number", default=50),
        FieldSpec(name="condition_id", label="Condition ID", type="string"),
        FieldSpec(name="token_id", label="Token ID", type="string"),
        FieldSpec(name="fixture_id", label="Fixture ID", type="string"),
        FieldSpec(name="app_user_id", label="App User ID", type="string"),
        FieldSpec(name="entitlement_id", label="Entitlement ID", type="string"),
        FieldSpec(name="duration", label="Duration", type="string", default="monthly"),
        FieldSpec(name="order_id", label="Order ID", type="string"),
        FieldSpec(name="series_ticker", label="Series Ticker", type="string"),
    ],
    operations=[
        OpSpec(
            id="list_events",
            label="List Events",
            method="GET",
            path="/events",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_markets",
            label="List Markets",
            method="GET",
            path="/markets",
            visible_fields=["event_ticker"],
            query_builder=lambda v: {
                k: val
                for k, val in {"event_ticker": getattr(v, "event_ticker", None) or None}.items()
                if val
            },
        ),
        OpSpec(
            id="get_market",
            label="Get Market",
            method="GET",
            path="/markets/{ticker}",
            visible_fields=["ticker"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="place_order",
            label="Place Order",
            method="POST",
            path="/portfolio/orders",
            visible_fields=["ticker", "side", "count", "price"],
            body_builder=lambda v: {
                "ticker": getattr(v, "ticker", "") or "",
                "side": getattr(v, "side", "") or "",
                "count": int(getattr(v, "count", 1) or 1),
                "yes_price": int(getattr(v, "price", 50) or 50),
            },
        ),
        OpSpec(
            id="get_balance",
            label="Get Portfolio Balance",
            method="GET",
            path="/portfolio/balance",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_positions",
            label="Get Positions",
            method="GET",
            path="/portfolio/positions",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_orders",
            label="Get Orders",
            method="GET",
            path="/portfolio/orders",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_order",
            label="Get Order",
            method="GET",
            path="/portfolio/orders/{order_id}",
            visible_fields=["order_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="cancel_order",
            label="Cancel Order",
            method="DELETE",
            path="/portfolio/orders/{order_id}",
            visible_fields=["order_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="amend_order",
            label="Amend Order",
            method="POST",
            path="/portfolio/orders/{order_id}/amend",
            visible_fields=["order_id", "count", "price"],
            body_builder=lambda v: {
                "count": int(getattr(v, "count", 1) or 1),
                "yes_price": int(getattr(v, "price", 50) or 50),
            },
        ),
        OpSpec(
            id="get_orderbook",
            label="Get Orderbook",
            method="GET",
            path="/markets/{ticker}/orderbook",
            visible_fields=["ticker"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_trades",
            label="Get Trades",
            method="GET",
            path="/markets/trades",
            visible_fields=["ticker"],
            query_builder=lambda v: {
                k: val for k, val in {"ticker": getattr(v, "ticker", None) or None}.items() if val
            },
        ),
        OpSpec(
            id="get_candlesticks",
            label="Get Market Candlesticks",
            method="GET",
            path="/markets/{ticker}/candlesticks",
            visible_fields=["ticker"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_event_candlesticks",
            label="Get Event Candlesticks",
            method="GET",
            path="/events/{event_ticker}/candlesticks",
            visible_fields=["event_ticker"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_fills",
            label="Get Fills",
            method="GET",
            path="/portfolio/fills",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_settlements",
            label="Get Settlements",
            method="GET",
            path="/portfolio/settlements",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_series_by_ticker",
            label="Get Series by Ticker",
            method="GET",
            path="/series/{series_ticker}",
            visible_fields=["series_ticker"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_series_list",
            label="List Series",
            method="GET",
            path="/series",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_exchange_status",
            label="Get Exchange Status",
            method="GET",
            path="/exchange/status",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_exchange_schedule",
            label="Get Exchange Schedule",
            method="GET",
            path="/exchange/schedule",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_exchange_announcements",
            label="Get Exchange Announcements",
            method="GET",
            path="/exchange/announcements",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "id", "type": "string"},
    ],
    allow_error=True,
)
