import type { NodeDefinition, NodeProperty } from '../../types'

const DEFAULT_MODELS = {
  openai: 'gpt-4o-mini',
  anthropic: 'claude-3-5-sonnet-latest',
  google: 'gemini-1.5-flash',
  groq: 'llama-3.1-8b-instant',
}

const credentialProperties: NodeProperty[] = [
  {
    name: 'openaiCredential',
    label: 'OpenAI API Key',
    type: 'credential',
    credentialType: 'openai_api_key',
    required: { field: 'provider', value: 'openai' },
    condition: { field: 'provider', value: 'openai' },
  },
  {
    name: 'anthropicCredential',
    label: 'Anthropic API Key',
    type: 'credential',
    credentialType: 'anthropic_api_key',
    required: { field: 'provider', value: 'anthropic' },
    condition: { field: 'provider', value: 'anthropic' },
  },
  {
    name: 'googleCredential',
    label: 'Google API Key',
    type: 'credential',
    credentialType: 'google_api_key',
    required: { field: 'provider', value: 'google' },
    condition: { field: 'provider', value: 'google' },
  },
  {
    name: 'groqCredential',
    label: 'Groq API Key',
    type: 'credential',
    credentialType: 'groq_api_key',
    required: { field: 'provider', value: 'groq' },
    condition: { field: 'provider', value: 'groq' },
  },
]

export const AgentDefinition: NodeDefinition = {
  type: 'action.agent',
  name: 'Agent',
  category: 'ai',
  description: 'Run an AI agent with provider selection, tools, memory, and structured output.',
  icon: 'Bot',
  color: '#8b5cf6',
  inputs: 1,
  outputs: 1,
  properties: [
    {
      name: 'provider',
      label: 'Provider',
      type: 'options',
      default: 'openai',
      required: true,
      options: [
        { label: 'OpenAI', value: 'openai' },
        { label: 'Anthropic', value: 'anthropic' },
        { label: 'Google Gemini', value: 'google' },
        { label: 'Groq', value: 'groq' },
      ],
    },
    ...credentialProperties,
    {
      name: 'model',
      label: 'Model',
      type: 'string',
      default: DEFAULT_MODELS.openai,
      required: true,
      placeholder: 'Type or select a model ID',
      loadOptions: '/ai/models',
      loadOptionsDependsOn: [
        'provider',
        'openaiCredential',
        'anthropicCredential',
        'googleCredential',
        'groqCredential',
      ],
    },
    {
      name: 'messages',
      label: 'Messages',
      type: 'json',
      required: true,
      default: [
        { role: 'system', content: 'You are a helpful workflow agent.' },
        { role: 'user', content: '{{trigger.output}}' },
      ],
      description: 'Array of messages with role and content.',
    },
    {
      name: 'tools',
      label: 'Tools',
      type: 'json',
      default: [],
      description: 'Function tools: [{ name, description, parameters }].',
    },
    {
      name: 'toolChoice',
      label: 'Tool Choice',
      type: 'options',
      default: 'auto',
      options: [
        { label: 'Auto', value: 'auto' },
        { label: 'Required', value: 'required' },
        { label: 'None', value: 'none' },
      ],
    },
    {
      name: 'memoryType',
      label: 'Memory',
      type: 'options',
      default: 'none',
      options: [
        { label: 'None', value: 'none' },
        { label: 'Workflow', value: 'workflow' },
      ],
    },
    {
      name: 'memoryKey',
      label: 'Memory Key',
      type: 'string',
      placeholder: 'customer-123',
      condition: { field: 'memoryType', value: 'workflow' },
    },
    {
      name: 'memoryLimit',
      label: 'Memory Limit',
      type: 'number',
      default: 10,
      condition: { field: 'memoryType', value: 'workflow' },
    },
    { name: 'temperature', label: 'Temperature', type: 'number', default: 0.3 },
    { name: 'maxTokens', label: 'Max Output Tokens', type: 'number', default: 4096 },
    {
      name: 'responseFormat',
      label: 'Response Format',
      type: 'json',
      required: false,
      description: 'Optional JSON Schema or provider response-format object.',
    },
    { name: 'timeout', label: 'Timeout (ms)', type: 'number', default: 60000 },
  ],
  outputsSchema: [
    { label: 'content', type: 'string' },
    { label: 'provider', type: 'string' },
    { label: 'model', type: 'string' },
    { label: 'tokens', type: 'object' },
    { label: 'toolCalls', type: 'array' },
    { label: 'structured', type: 'object' },
    { label: 'memory', type: 'array' },
    { label: 'raw', type: 'object' },
  ],
  allowError: true,
}
