"""RB2B action node — RB2B — identify anonymous website visitors (B2B).

REST at https://api.rb2b.com/v1. See sim-parity roadmap Phase 4-close-5.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.rb2b",
    name="RB2B",
    category="integration",
    description="RB2B — identify anonymous website visitors (B2B).",
    icon_slug="rb2b",
    color="#1c1c1c",
    base_url="https://api.rb2b.com/v1",
    credential_type="rb2b_api_key",
    token_field=["api_key"],
    auth="bearer",
    fields=[
        FieldSpec(name="model", label="Model", type="string"),
        FieldSpec(name="messages", label="Messages (JSON array)", type="json", default=[]),
        FieldSpec(name="temperature", label="Temperature", type="number", default=1),
        FieldSpec(name="max_tokens", label="Max Tokens", type="number", default=0),
        FieldSpec(name="input", label="Input", type="string"),
        FieldSpec(name="instructions", label="Instructions", type="string"),
        FieldSpec(name="prompt", label="Prompt", type="string"),
        FieldSpec(name="size", label="Size", type="string", default="1024x1024"),
        FieldSpec(name="quality", label="Quality", type="string", default="high"),
        FieldSpec(name="n", label="Count", type="number", default=1),
        FieldSpec(name="file_url", label="File URL", type="string"),
        FieldSpec(name="image_url", label="Image URL", type="string"),
        FieldSpec(name="mask_url", label="Mask URL", type="string"),
        FieldSpec(name="voice_id", label="Voice ID", type="string"),
        FieldSpec(name="text", label="Text", type="string"),
        FieldSpec(name="model_id", label="Model ID", type="string"),
        FieldSpec(name="user_id", label="User ID", type="string"),
        FieldSpec(name="memory_id", label="Memory ID", type="string"),
        FieldSpec(name="metadata", label="Metadata (JSON)", type="json", default={}),
        FieldSpec(name="query", label="Query", type="string"),
        FieldSpec(name="limit", label="Limit", type="number", default=10, mode="advanced"),
        FieldSpec(name="session_id", label="Session ID", type="string"),
        FieldSpec(name="email", label="Email", type="string"),
        FieldSpec(name="first_name", label="First Name", type="string"),
        FieldSpec(name="last_name", label="Last Name", type="string"),
        FieldSpec(name="task_spec", label="Task Spec (JSON)", type="json", default={}),
        FieldSpec(name="processor", label="Processor", type="string", default="core"),
        FieldSpec(name="input_data", label="Input Data (JSON)", type="json", default={}),
        FieldSpec(name="run_id", label="Run ID", type="string"),
        FieldSpec(name="objective", label="Objective", type="string"),
        FieldSpec(name="page_size", label="Page Size", type="number", default=100),
        FieldSpec(
            name="person_fields",
            label="Person Fields",
            type="string",
            default="names,emailAddresses,phoneNumbers",
        ),
        FieldSpec(name="resource_name", label="Resource Name", type="string"),
        FieldSpec(name="given_name", label="Given Name", type="string"),
        FieldSpec(name="family_name", label="Family Name", type="string"),
        FieldSpec(name="phone", label="Phone", type="string"),
        FieldSpec(name="engine_id", label="Search Engine ID (cx)", type="string"),
        FieldSpec(name="num", label="Num Results", type="number", default=10),
        FieldSpec(name="start", label="Start Index", type="number", default=1),
        FieldSpec(name="search_type", label="Search Type (image or blank)", type="string"),
        FieldSpec(name="to", label="To", type="string"),
        FieldSpec(name="from_number", label="From", type="string"),
        FieldSpec(name="body_text", label="Body Text", type="string"),
        FieldSpec(name="media_url", label="Media URL", type="string"),
        FieldSpec(name="message_sid", label="Message SID", type="string"),
        FieldSpec(name="application_id", label="Application ID", type="string"),
        FieldSpec(name="environment_id", label="Environment ID", type="string"),
        FieldSpec(name="profile_id", label="Configuration Profile ID", type="string"),
        FieldSpec(name="version_number", label="Version Number", type="string"),
        FieldSpec(name="deployment_strategy_id", label="Deployment Strategy ID", type="string"),
        FieldSpec(name="visitor_id", label="Visitor ID", type="string"),
        FieldSpec(name="since", label="Since (ISO)", type="string"),
        FieldSpec(name="host", label="SAP Host", type="string"),
        FieldSpec(name="username", label="Username", type="string"),
        FieldSpec(name="business_partner", label="Business Partner ID", type="string"),
        FieldSpec(name="sales_order", label="Sales Order ID", type="string"),
        FieldSpec(name="top", label="Top", type="number", default=20, mode="advanced"),
        FieldSpec(name="filter", label="Filter", type="string", mode="advanced"),
        FieldSpec(name="hem", label="Hashed Email (HEM)", type="string"),
        FieldSpec(name="maid", label="Mobile Advertiser ID", type="string"),
        FieldSpec(name="linkedin_url", label="LinkedIn URL", type="string"),
        FieldSpec(name="linkedin_slug", label="LinkedIn Slug", type="string"),
        FieldSpec(name="ip_address", label="IP Address", type="string"),
    ],
    operations=[
        OpSpec(
            id="list_visitors",
            label="List Recent Visitors",
            method="GET",
            path="/visitors",
            visible_fields=["limit", "since"],
            query_builder=lambda v: {
                k: val
                for k, val in {
                    "limit": int(getattr(v, "limit", 25) or 25),
                    "since": getattr(v, "since", None) or None,
                }.items()
                if val is not None
            },
        ),
        OpSpec(
            id="get_visitor",
            label="Get Visitor",
            method="GET",
            path="/visitors/{visitor_id}",
            visible_fields=["visitor_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="identify_by_email",
            label="Identify by Email",
            method="GET",
            path="/identify",
            visible_fields=["email"],
            query_builder=lambda v: {"email": getattr(v, "email", "") or ""},
        ),
        OpSpec(
            id="credit_check",
            label="Credit Check",
            method="GET",
            path="/credits",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="ip_to_hem",
            label="IP to Hashed Email",
            method="GET",
            path="/ip-to-hem",
            visible_fields=["ip_address"],
            query_builder=lambda v: {"ip": getattr(v, "ip_address", "") or ""},
        ),
        OpSpec(
            id="ip_to_maid",
            label="IP to MAID",
            method="GET",
            path="/ip-to-maid",
            visible_fields=["ip_address"],
            query_builder=lambda v: {"ip": getattr(v, "ip_address", "") or ""},
        ),
        OpSpec(
            id="hem_to_business_profile",
            label="HEM to Business Profile",
            method="GET",
            path="/hem-to-business",
            visible_fields=["hem"],
            query_builder=lambda v: {"hem": getattr(v, "hem", "") or ""},
        ),
        OpSpec(
            id="hem_to_best_linkedin",
            label="HEM to Best LinkedIn",
            method="GET",
            path="/hem-to-best-linkedin",
            visible_fields=["hem"],
            query_builder=lambda v: {"hem": getattr(v, "hem", "") or ""},
        ),
        OpSpec(
            id="hem_to_linkedin",
            label="HEM to LinkedIn",
            method="GET",
            path="/hem-to-linkedin",
            visible_fields=["hem"],
            query_builder=lambda v: {"hem": getattr(v, "hem", "") or ""},
        ),
        OpSpec(
            id="hem_to_maid",
            label="HEM to MAID",
            method="GET",
            path="/hem-to-maid",
            visible_fields=["hem"],
            query_builder=lambda v: {"hem": getattr(v, "hem", "") or ""},
        ),
        OpSpec(
            id="email_to_activity",
            label="Email to Activity",
            method="GET",
            path="/email-to-activity",
            visible_fields=["email"],
            query_builder=lambda v: {"email": getattr(v, "email", "") or ""},
        ),
        OpSpec(
            id="linkedin_to_business_profile",
            label="LinkedIn to Business Profile",
            method="GET",
            path="/linkedin-to-business",
            visible_fields=["linkedin_url"],
            query_builder=lambda v: {"linkedin_url": getattr(v, "linkedin_url", "") or ""},
        ),
        OpSpec(
            id="linkedin_to_best_personal_email",
            label="LinkedIn to Best Personal Email",
            method="GET",
            path="/linkedin-to-best-personal-email",
            visible_fields=["linkedin_url"],
            query_builder=lambda v: {"linkedin_url": getattr(v, "linkedin_url", "") or ""},
        ),
        OpSpec(
            id="linkedin_to_personal_email",
            label="LinkedIn to Personal Email",
            method="GET",
            path="/linkedin-to-personal-email",
            visible_fields=["linkedin_url"],
            query_builder=lambda v: {"linkedin_url": getattr(v, "linkedin_url", "") or ""},
        ),
        OpSpec(
            id="linkedin_to_hashed_emails",
            label="LinkedIn to Hashed Emails",
            method="GET",
            path="/linkedin-to-hashed-emails",
            visible_fields=["linkedin_url"],
            query_builder=lambda v: {"linkedin_url": getattr(v, "linkedin_url", "") or ""},
        ),
        OpSpec(
            id="linkedin_to_mobile_phone",
            label="LinkedIn to Mobile Phone",
            method="GET",
            path="/linkedin-to-mobile-phone",
            visible_fields=["linkedin_url"],
            query_builder=lambda v: {"linkedin_url": getattr(v, "linkedin_url", "") or ""},
        ),
        OpSpec(
            id="linkedin_slug_search",
            label="LinkedIn Slug Search",
            method="GET",
            path="/linkedin-slug-search",
            visible_fields=["linkedin_slug"],
            query_builder=lambda v: {"slug": getattr(v, "linkedin_slug", "") or ""},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "id", "type": "string"},
    ],
    allow_error=True,
)
