"""Enrich.so action node — Enrich.so — LinkedIn scraper + email finder.

REST at https://api.enrich.so/v1. See sim-parity roadmap §4.15.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.enrich",
    name="Enrich.so",
    category="integration",
    description="Enrich.so — LinkedIn scraper + email finder.",
    icon_slug="enrich",
    color="#1c1c1c",
    base_url="https://api.enrich.so/v1",
    credential_type="enrich_api_key",
    token_field=["api_key"],
    auth="bearer",
    fields=[
        FieldSpec(name="email", label="Email", type="string"),
        FieldSpec(name="first_name", label="First Name", type="string"),
        FieldSpec(name="last_name", label="Last Name", type="string"),
        FieldSpec(name="linkedin_url", label="LinkedIn URL", type="string"),
        FieldSpec(name="domain", label="Domain", type="string"),
        FieldSpec(name="company", label="Company Name", type="string"),
        FieldSpec(name="company_name", label="Company Name", type="string"),
        FieldSpec(name="post_url", label="LinkedIn Post URL", type="string"),
        FieldSpec(name="search_query", label="Search Query (JSON)", type="json", default={}),
        FieldSpec(name="ip_address", label="IP Address", type="string"),
        FieldSpec(name="emails", label="Emails (JSON array)", type="json", default=[]),
    ],
    operations=[
        OpSpec(
            id="person_by_linkedin",
            label="Person by LinkedIn URL",
            method="POST",
            path="/person",
            visible_fields=["linkedin_url"],
            body_builder=lambda v: {"linkedin_url": getattr(v, "linkedin_url", "") or ""},
        ),
        OpSpec(
            id="person_by_email",
            label="Person by Email",
            method="POST",
            path="/person",
            visible_fields=["email"],
            body_builder=lambda v: {"email": getattr(v, "email", "") or ""},
        ),
        OpSpec(
            id="company_by_domain",
            label="Company by Domain",
            method="POST",
            path="/company",
            visible_fields=["domain"],
            body_builder=lambda v: {"domain": getattr(v, "domain", "") or ""},
        ),
        OpSpec(
            id="email_finder",
            label="Email Finder",
            method="POST",
            path="/email-finder",
            visible_fields=["first_name", "last_name", "domain"],
            body_builder=lambda v: {
                k: val
                for k, val in {
                    "first_name": getattr(v, "first_name", None) or None,
                    "last_name": getattr(v, "last_name", None) or None,
                    "domain": getattr(v, "domain", None) or None,
                }.items()
                if val is not None
            },
        ),
        OpSpec(
            id="email_to_profile",
            label="Email to Profile",
            method="GET",
            path="/email-to-profile",
            visible_fields=["email"],
            query_builder=lambda v: {"email": getattr(v, "email", "") or ""},
        ),
        OpSpec(
            id="email_to_person_lite",
            label="Email to Person Lite",
            method="GET",
            path="/email-to-person-lite",
            visible_fields=["email"],
            query_builder=lambda v: {"email": getattr(v, "email", "") or ""},
        ),
        OpSpec(
            id="linkedin_profile",
            label="LinkedIn Profile Lookup",
            method="GET",
            path="/linkedin",
            visible_fields=["linkedin_url"],
            query_builder=lambda v: {"url": getattr(v, "linkedin_url", "") or ""},
        ),
        OpSpec(
            id="find_email",
            label="Find Email",
            method="GET",
            path="/find-email",
            visible_fields=["first_name", "last_name", "domain"],
            query_builder=lambda v: {
                "first_name": getattr(v, "first_name", "") or "",
                "last_name": getattr(v, "last_name", "") or "",
                "domain": getattr(v, "domain", "") or "",
            },
        ),
        OpSpec(
            id="linkedin_to_work_email",
            label="LinkedIn to Work Email",
            method="GET",
            path="/linkedin-to-work-email",
            visible_fields=["linkedin_url"],
            query_builder=lambda v: {"url": getattr(v, "linkedin_url", "") or ""},
        ),
        OpSpec(
            id="linkedin_to_personal_email",
            label="LinkedIn to Personal Email",
            method="GET",
            path="/linkedin-to-personal-email",
            visible_fields=["linkedin_url"],
            query_builder=lambda v: {"url": getattr(v, "linkedin_url", "") or ""},
        ),
        OpSpec(
            id="phone_finder",
            label="Phone Finder",
            method="GET",
            path="/phone-finder",
            visible_fields=["email", "linkedin_url"],
            query_builder=lambda v: {
                k: val
                for k, val in {
                    "email": getattr(v, "email", None) or None,
                    "linkedin_url": getattr(v, "linkedin_url", None) or None,
                }.items()
                if val
            },
        ),
        OpSpec(
            id="email_to_phone",
            label="Email to Phone",
            method="GET",
            path="/email-to-phone",
            visible_fields=["email"],
            query_builder=lambda v: {"email": getattr(v, "email", "") or ""},
        ),
        OpSpec(
            id="verify_email",
            label="Verify Email",
            method="GET",
            path="/verify-email",
            visible_fields=["email"],
            query_builder=lambda v: {"email": getattr(v, "email", "") or ""},
        ),
        OpSpec(
            id="disposable_email_check",
            label="Disposable Email Check",
            method="GET",
            path="/disposable-email",
            visible_fields=["email"],
            query_builder=lambda v: {"email": getattr(v, "email", "") or ""},
        ),
        OpSpec(
            id="domain_to_company",
            label="Domain to Company",
            method="GET",
            path="/domain-to-company",
            visible_fields=["domain"],
            query_builder=lambda v: {"domain": getattr(v, "domain", "") or ""},
        ),
        OpSpec(
            id="company_lookup",
            label="Company Lookup",
            method="GET",
            path="/company",
            visible_fields=["company_name"],
            query_builder=lambda v: {"name": getattr(v, "company_name", "") or ""},
        ),
        OpSpec(
            id="linkedin_post_engagement",
            label="LinkedIn Post Engagement",
            method="GET",
            path="/linkedin-post-engagement",
            visible_fields=["post_url"],
            query_builder=lambda v: {"post_url": getattr(v, "post_url", "") or ""},
        ),
        OpSpec(
            id="person_search",
            label="Person Search",
            method="POST",
            path="/search/people",
            visible_fields=["search_query"],
            body_builder=lambda v: getattr(v, "search_query", None) or {},
        ),
        OpSpec(
            id="company_search",
            label="Company Search",
            method="POST",
            path="/search/companies",
            visible_fields=["search_query"],
            body_builder=lambda v: getattr(v, "search_query", None) or {},
        ),
        OpSpec(
            id="technographic_lookup",
            label="Technographic Lookup",
            method="GET",
            path="/technographics",
            visible_fields=["domain"],
            query_builder=lambda v: {"domain": getattr(v, "domain", "") or ""},
        ),
        OpSpec(
            id="company_employees",
            label="Get Company Employees",
            method="GET",
            path="/company/employees",
            visible_fields=["domain"],
            query_builder=lambda v: {"domain": getattr(v, "domain", "") or ""},
        ),
        OpSpec(
            id="company_funding",
            label="Get Company Funding",
            method="GET",
            path="/company/funding",
            visible_fields=["domain"],
            query_builder=lambda v: {"domain": getattr(v, "domain", "") or ""},
        ),
        OpSpec(
            id="company_intent",
            label="Company Intent Signals",
            method="GET",
            path="/company/intent",
            visible_fields=["domain"],
            query_builder=lambda v: {"domain": getattr(v, "domain", "") or ""},
        ),
        OpSpec(
            id="linkedin_company_lookup",
            label="LinkedIn Company Lookup",
            method="GET",
            path="/linkedin/company",
            visible_fields=["linkedin_url"],
            query_builder=lambda v: {"url": getattr(v, "linkedin_url", "") or ""},
        ),
        OpSpec(
            id="ip_to_company",
            label="IP to Company",
            method="GET",
            path="/ip-to-company",
            visible_fields=["ip_address"],
            query_builder=lambda v: {"ip": getattr(v, "ip_address", "") or ""},
        ),
        OpSpec(
            id="bulk_email_verify",
            label="Bulk Email Verify",
            method="POST",
            path="/bulk/verify-email",
            visible_fields=["emails"],
            body_builder=lambda v: {"emails": getattr(v, "emails", []) or []},
        ),
        OpSpec(
            id="bulk_email_to_profile",
            label="Bulk Email to Profile",
            method="POST",
            path="/bulk/email-to-profile",
            visible_fields=["emails"],
            body_builder=lambda v: {"emails": getattr(v, "emails", []) or []},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "email", "type": "string"},
        {"label": "status", "type": "string"},
    ],
    allow_error=True,
)
