"""Trigger.dev action node — Trigger.dev — trigger background job runs, inspect runs.

REST at https://api.trigger.dev/api/v1. See sim-parity roadmap Phase 4.30.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.trigger_dev",
    name="Trigger.dev",
    category="integration",
    description="Trigger.dev — trigger background job runs, inspect runs.",
    icon_slug="trigger_dev",
    color="#1c1c1c",
    base_url="https://api.trigger.dev/api/v1",
    credential_type="trigger_dev_api_key",
    token_field=["api_key"],
    auth="bearer",
    fields=[
        FieldSpec(name="tailnet", label="Tailnet", type="string", default="-"),
        FieldSpec(name="device_id", label="Device ID", type="string"),
        FieldSpec(name="tags", label="Tags (JSON array)", type="json", default=[]),
        FieldSpec(name="s3_bucket", label="S3 Bucket", type="string"),
        FieldSpec(name="s3_key", label="S3 Key", type="string"),
        FieldSpec(
            name="feature_types",
            label="Feature Types (JSON)",
            type="json",
            default=["TABLES", "FORMS"],
        ),
        FieldSpec(name="pipeline_name", label="Pipeline Name", type="string"),
        FieldSpec(name="task_id", label="Task ID", type="string"),
        FieldSpec(name="run_id", label="Run ID", type="string"),
        FieldSpec(name="payload", label="Payload (JSON)", type="json", default={}),
        FieldSpec(name="test_id", label="Test ID", type="string"),
        FieldSpec(name="status", label="Status", type="string"),
        FieldSpec(name="event_ticker", label="Event Ticker", type="string"),
        FieldSpec(name="ticker", label="Ticker", type="string"),
        FieldSpec(name="side", label="Side (yes|no|buy|sell)", type="string"),
        FieldSpec(name="count", label="Count", type="number", default=1),
        FieldSpec(name="price", label="Yes Price (¢)", type="number", default=50),
        FieldSpec(name="condition_id", label="Condition ID", type="string"),
        FieldSpec(name="token_id", label="Token ID", type="string"),
        FieldSpec(name="fixture_id", label="Fixture ID", type="string"),
        FieldSpec(name="app_user_id", label="App User ID", type="string"),
        FieldSpec(name="entitlement_id", label="Entitlement ID", type="string"),
        FieldSpec(name="duration", label="Duration", type="string", default="monthly"),
        FieldSpec(name="delay_seconds", label="Delay (seconds)", type="number", default=0),
        FieldSpec(name="run_options", label="Run Options (JSON)", type="json", default={}),
        FieldSpec(name="batch_items", label="Batch Items (JSON)", type="json", default=[]),
        FieldSpec(name="schedule_id", label="Schedule ID", type="string"),
        FieldSpec(name="schedule_body", label="Schedule Body (JSON)", type="json", default={}),
        FieldSpec(name="project_ref", label="Project Ref", type="string"),
        FieldSpec(name="environment", label="Environment (dev|staging|prod)", type="string"),
        FieldSpec(name="env_name", label="Env Var Name", type="string"),
        FieldSpec(name="env_value", label="Env Var Value", type="string"),
        FieldSpec(name="deploy_id", label="Deployment ID", type="string"),
        FieldSpec(name="alert_id", label="Alert ID", type="string"),
    ],
    operations=[
        OpSpec(
            id="trigger_task",
            label="Trigger Task Run",
            method="POST",
            path="/tasks/{task_id}/trigger",
            visible_fields=["task_id", "payload"],
            body_builder=lambda v: {"payload": getattr(v, "payload", {}) or {}},
        ),
        OpSpec(
            id="get_run",
            label="Get Run",
            method="GET",
            path="/runs/{run_id}",
            visible_fields=["run_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="cancel_run",
            label="Cancel Run",
            method="POST",
            path="/runs/{run_id}/cancel",
            visible_fields=["run_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="list_runs",
            label="List Runs",
            method="GET",
            path="/runs",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="replay_run",
            label="Replay Run",
            method="POST",
            path="/runs/{run_id}/replay",
            visible_fields=["run_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="reschedule_run",
            label="Reschedule Run",
            method="POST",
            path="/runs/{run_id}/reschedule",
            visible_fields=["run_id", "delay_seconds"],
            body_builder=lambda v: {"delay": int(getattr(v, "delay_seconds", 0) or 0)},
        ),
        OpSpec(
            id="trigger_with_context",
            label="Trigger Task with Context",
            method="POST",
            path="/tasks/{task_id}/trigger",
            visible_fields=["task_id", "payload", "run_options"],
            body_builder=lambda v: {
                "payload": getattr(v, "payload", None) or {},
                "options": getattr(v, "run_options", None) or {},
            },
        ),
        OpSpec(
            id="batch_trigger",
            label="Batch Trigger Task",
            method="POST",
            path="/tasks/{task_id}/batch",
            visible_fields=["task_id", "batch_items"],
            body_builder=lambda v: {"items": getattr(v, "batch_items", []) or []},
        ),
        OpSpec(
            id="list_schedules",
            label="List Schedules",
            method="GET",
            path="/schedules",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_schedule",
            label="Get Schedule",
            method="GET",
            path="/schedules/{schedule_id}",
            visible_fields=["schedule_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="create_schedule",
            label="Create Schedule",
            method="POST",
            path="/schedules",
            visible_fields=["schedule_body"],
            body_builder=lambda v: getattr(v, "schedule_body", None) or {},
        ),
        OpSpec(
            id="update_schedule",
            label="Update Schedule",
            method="PUT",
            path="/schedules/{schedule_id}",
            visible_fields=["schedule_id", "schedule_body"],
            body_builder=lambda v: getattr(v, "schedule_body", None) or {},
        ),
        OpSpec(
            id="delete_schedule",
            label="Delete Schedule",
            method="DELETE",
            path="/schedules/{schedule_id}",
            visible_fields=["schedule_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="deactivate_schedule",
            label="Deactivate Schedule",
            method="POST",
            path="/schedules/{schedule_id}/deactivate",
            visible_fields=["schedule_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="activate_schedule",
            label="Activate Schedule",
            method="POST",
            path="/schedules/{schedule_id}/activate",
            visible_fields=["schedule_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="list_env_vars",
            label="List Env Vars",
            method="GET",
            path="/projects/{project_ref}/envvars/{environment}",
            visible_fields=["project_ref", "environment"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="upsert_env_var",
            label="Upsert Env Var",
            method="POST",
            path="/projects/{project_ref}/envvars/{environment}",
            visible_fields=["project_ref", "environment", "env_name", "env_value"],
            body_builder=lambda v: {
                "name": getattr(v, "env_name", "") or "",
                "value": getattr(v, "env_value", "") or "",
            },
        ),
        OpSpec(
            id="delete_env_var",
            label="Delete Env Var",
            method="DELETE",
            path="/projects/{project_ref}/envvars/{environment}/{env_name}",
            visible_fields=["project_ref", "environment", "env_name"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_project",
            label="Get Project",
            method="GET",
            path="/projects/{project_ref}",
            visible_fields=["project_ref"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_projects",
            label="List Projects",
            method="GET",
            path="/projects",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_run_stream",
            label="Get Run Stream (final)",
            method="GET",
            path="/runs/{run_id}/stream",
            visible_fields=["run_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_task",
            label="Get Task",
            method="GET",
            path="/tasks/{task_id}",
            visible_fields=["task_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_tasks",
            label="List Tasks in Project",
            method="GET",
            path="/projects/{project_ref}/tasks",
            visible_fields=["project_ref"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_deploys",
            label="List Deployments",
            method="GET",
            path="/projects/{project_ref}/deploys",
            visible_fields=["project_ref"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_deploy",
            label="Get Deployment",
            method="GET",
            path="/deploys/{deploy_id}",
            visible_fields=["deploy_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="promote_deploy",
            label="Promote Deployment",
            method="POST",
            path="/deploys/{deploy_id}/promote",
            visible_fields=["deploy_id"],
            body_builder=lambda v: {},
        ),
        OpSpec(
            id="list_run_tags",
            label="List Run Tags in Project",
            method="GET",
            path="/projects/{project_ref}/run-tags",
            visible_fields=["project_ref"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="wait_for_run",
            label="Wait for Run Completion",
            method="GET",
            path="/runs/{run_id}/waitpoints",
            visible_fields=["run_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_alerts",
            label="List Alerts in Project",
            method="GET",
            path="/projects/{project_ref}/alerts",
            visible_fields=["project_ref"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_alert",
            label="Get Alert",
            method="GET",
            path="/alerts/{alert_id}",
            visible_fields=["alert_id"],
            query_builder=lambda v: {},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "id", "type": "string"},
    ],
    allow_error=True,
)
