"""Profound action node — Profound — AI-answer / share-of-voice analytics.

REST at https://api.tryprofound.com/v1. See sim-parity roadmap Phase 4.32.
"""

from __future__ import annotations

from apps.api.app.node_system.scaffolds import FieldSpec, OpSpec, ProviderManifest

MANIFEST = ProviderManifest(
    type="action.profound",
    name="Profound",
    category="integration",
    description="Profound — AI-answer / share-of-voice analytics.",
    icon_slug="profound",
    color="#1c1c1c",
    base_url="https://api.tryprofound.com/v1",
    credential_type="profound_api_key",
    token_field=["api_key"],
    auth="bearer",
    fields=[
        FieldSpec(name="table", label="Table", type="string"),
        FieldSpec(name="record_id", label="Record ID", type="string"),
        FieldSpec(name="filter", label="Filter", type="string"),
        FieldSpec(name="data", label="Data (JSON)", type="json", default={}),
        FieldSpec(name="config_id", label="Sync Config ID", type="string"),
        FieldSpec(name="query_text", label="Query Text", type="string"),
        FieldSpec(name="destination_id", label="Destination ID", type="string"),
        FieldSpec(name="property_id", label="Property ID", type="string"),
        FieldSpec(name="email", label="Email", type="string"),
        FieldSpec(name="right", label="Right (delete|access|...)", type="string", default="delete"),
        FieldSpec(name="source", label="LaTeX Source", type="string"),
        FieldSpec(name="query", label="Query", type="string"),
        FieldSpec(name="depth", label="Depth (standard|deep)", type="string", default="standard"),
        FieldSpec(name="output_type", label="Output Type", type="string", default="searchResults"),
        FieldSpec(name="supplier_id", label="Supplier ID", type="string"),
        FieldSpec(name="path", label="Path", type="string"),
        FieldSpec(name="content", label="Content", type="string"),
        FieldSpec(name="message", label="Message", type="string"),
        FieldSpec(name="project_id", label="Project ID", type="string"),
        FieldSpec(name="file_url", label="File URL", type="string"),
        FieldSpec(name="json_schema", label="Schema (JSON)", type="json", default={}),
        FieldSpec(name="job_id", label="Job ID", type="string"),
        FieldSpec(name="company_id", label="Company ID", type="string"),
        FieldSpec(name="event_id", label="Event ID", type="string"),
        FieldSpec(name="remote", label="Remote (github|gitlab)", type="string", default="github"),
        FieldSpec(name="repository", label="Repository (owner/repo)", type="string"),
        FieldSpec(name="branch", label="Branch", type="string", default="main"),
        FieldSpec(name="repositories", label="Repositories (JSON)", type="json", default=[]),
        FieldSpec(name="guard_name", label="Guard Name", type="string"),
        FieldSpec(name="llm_output", label="LLM Output", type="string"),
        FieldSpec(name="host_ids", label="Host IDs (JSON)", type="json", default=[]),
        FieldSpec(name="limit", label="Limit", type="number", default=50, mode="advanced"),
        FieldSpec(name="category_id", label="Category ID", type="string"),
        FieldSpec(name="prompt_id", label="Prompt ID", type="string"),
        FieldSpec(name="optimization_id", label="Optimization ID", type="string"),
    ],
    operations=[
        OpSpec(
            id="list_projects",
            label="List Projects",
            method="GET",
            path="/projects",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="get_project_share",
            label="Get Project Share of Voice",
            method="GET",
            path="/projects/{project_id}/share-of-voice",
            visible_fields=["project_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_answers",
            label="List AI Answers",
            method="GET",
            path="/projects/{project_id}/answers",
            visible_fields=["project_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_categories",
            label="List Categories",
            method="GET",
            path="/categories",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_regions",
            label="List Regions",
            method="GET",
            path="/regions",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_models",
            label="List Models",
            method="GET",
            path="/models",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_domains",
            label="List Domains",
            method="GET",
            path="/domains",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_assets",
            label="List Assets",
            method="GET",
            path="/assets",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_personas",
            label="List Personas",
            method="GET",
            path="/personas",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="category_topics",
            label="Category Topics",
            method="GET",
            path="/categories/{category_id}/topics",
            visible_fields=["category_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="category_tags",
            label="Category Tags",
            method="GET",
            path="/categories/{category_id}/tags",
            visible_fields=["category_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="category_prompts",
            label="Category Prompts",
            method="GET",
            path="/categories/{category_id}/prompts",
            visible_fields=["category_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="category_assets",
            label="Category Assets",
            method="GET",
            path="/categories/{category_id}/assets",
            visible_fields=["category_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="category_personas",
            label="Category Personas",
            method="GET",
            path="/categories/{category_id}/personas",
            visible_fields=["category_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="visibility_report",
            label="Visibility Report",
            method="GET",
            path="/reports/visibility",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="sentiment_report",
            label="Sentiment Report",
            method="GET",
            path="/reports/sentiment",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="citations_report",
            label="Citations Report",
            method="GET",
            path="/reports/citations",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="query_fanouts",
            label="Query Fanouts",
            method="GET",
            path="/fanouts",
            visible_fields=["query_text"],
            query_builder=lambda v: {"q": getattr(v, "query_text", "") or ""},
        ),
        OpSpec(
            id="prompt_answers",
            label="Prompt Answers",
            method="GET",
            path="/prompts/{prompt_id}/answers",
            visible_fields=["prompt_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="bots_report",
            label="Bots Report",
            method="GET",
            path="/reports/bots",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="referrals_report",
            label="Referrals Report",
            method="GET",
            path="/reports/referrals",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="raw_logs",
            label="Raw Logs",
            method="GET",
            path="/logs/raw",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="bot_logs",
            label="Bot Logs",
            method="GET",
            path="/logs/bots",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="list_optimizations",
            label="List Optimizations",
            method="GET",
            path="/optimizations",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="optimization_analysis",
            label="Optimization Analysis",
            method="GET",
            path="/optimizations/{optimization_id}/analysis",
            visible_fields=["optimization_id"],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="prompt_volume",
            label="Prompt Volume",
            method="GET",
            path="/prompts/volume",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
        OpSpec(
            id="citation_prompts",
            label="Citation Prompts",
            method="GET",
            path="/citations/prompts",
            visible_fields=[],
            query_builder=lambda v: {},
        ),
    ],
    outputs_schema=[
        {"label": "data", "type": "object"},
        {"label": "id", "type": "string"},
    ],
    allow_error=True,
)
